vars/build.groovy

Add the cause for the build exception
Avoid to obfuscate the exception
Closes #ISSUE

Add causes for the exception

---

src/test/groovy/IsInternalCIStepTests.groovy
vars/README.md
vars/isInternalCI.groovy
vars/isInternalCI.txt

New step for running releases in the internal-ci
Encapsulate the logic in the library
Closes #ISSUE

isInternalCI step

---

resources/github-comment-markdown.template

Add some verbose explanation regarding the badge links
People might think they are just cosmetic icons

[DOCS] Add badge details

---

.ci/validateWorkersBeatsCi.groovy
resources/JenkinsfileTemplate.groovy

* It adds new workers to test to the beats pipeline
* it refactor and add missing workers to the apm-ci pipeline.
Test, test, test ...

ci: add workers to the infra test

---

src/co/elastic/NotificationManager.groovy

Fixes a formatting problem which can be seen here: https://github.com/elastic/e2e-testing/pull/340#issuecomment-705741994
Just cleaner output.

Fix formatting in flake report

---

src/test/groovy/GithubCreatePullRequestStepTests.groovy
vars/README.md
vars/githubCreatePullRequest.groovy
vars/githubCreatePullRequest.txt

Return the URL of the just created PR
See https://github.com/elastic/apm-agent-php/pull/215/files#diff-8db37e8fcea0f1a8f2f39667e94ebcc4R498-R499

Return PR URL with githubCreatePullRequest step

---

.ci/Jenkinsfile
.ci/validateWorkersBeatsCi.groovy

- Add new darwin workers
- Notify status of the test-infra pipeline
Test everything and get notifictions when things are getting broken
Closes #ISSUE

[test-infra] add new darwin workers and slack notifications

---

.ci/buildDockerImages.groovy

* clean Docker images after push
* use new nodes for parallel tasks
we are using the same node for the whole pipeline, so the parallel tasks are not parallel and we fill the disk with all the docker images.
```
[2020-10-20T06:06:56.034Z] #   go: finding sigs.k8s.io/structured-merge-diff/v3 v3.0.0
[2020-10-20T06:06:56.034Z] #   go: finding sigs.k8s.io/yaml v1.2.0
[2020-10-20T06:06:56.034Z] #   go: finding sourcegraph.com/sqs/pbtypes v0.0.0-20180604144634-d3ebe8f20ae4
[2020-10-20T06:06:56.034Z] #   Error processing tar file(exit status 1): write /go/pkg/mod/github.com/mozilla/tls-observatory@v0.0.0-20190404164649-a3c1b6cfecfd/conf/cisco-top-1m.csv: no space left on device
[2020-10-20T06:06:56.034Z] # --
[2020-10-20T06:06:56.034Z] # 
[2020-10-20T06:06:56.034Z] ok 2 golang-mage - clean test …
```

fix: clean Docker images after push

---

.ci/buildDockerImages.groovy

it fixes the reference expression, it is not correct.

fix: reference expression

---

.ci/buildDockerImages.groovy

We are no login on the new nodes and we need it.

fix: make Docker login on the nodes

---

resources/JenkinsfileTemplate.groovy
resources/scripts/jenkins/apm-ci/test.ps1

Fix issue when python2 is already installed and older.
Add slack communication
Otherwise the pipeline is broken
[build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-test-pipeline-mbp/detail/master/79/pipeline)

[CI] windows-2019 got python2 newer

---

.ci/Jenkinsfile

Enable flaky analyser for the apm pipeline library
To run the same validations we also do for other projects.

[flaky] enable for the apm-pipeline-library

---

vars/beatsWhen.groovy

Cosmetic change in the markdown and default value 
Help with the markdown format
There is a wrong format in the markdown and also missing when disabled by default

cosmetic change to highlight when disabled

---

.ci/jobs/apm-ui-e2e-tests-mbp.yml

cover Kibana PRs from 7*10^4 up to 10^7-1

ci: cover Kibana PRs from 7*10^4 up to 10^7-1

---

resources/scripts/generate-build-data.sh

Filter some fields that we don't need 
Less data to be populated.

Exclude _class,_links,latestRun,permissions and parameters to be populated

---

vars/README.md
vars/sendDataToElasticsearch.groovy
vars/sendDataToElasticsearch.txt

Reverts elastic/apm-pipeline-library#839

Revert "New ES index"

---

resources/flaky-github-comment-markdown.template
src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
src/test/groovy/NotifyBuildResultStepTests.groovy
vars/README.md
vars/notifyBuildResult.groovy
vars/notifyBuildResult.txt

Aggregate the flaky and build details in one single comment
This will avoid two different comments, although it allows to customise it if required :)
Closes https://github.com/elastic/apm-pipeline-library/issues/834
See https://github.com/v1v/apm-agent-php/pull/2#issuecomment-726143784

Aggregate GH Comments

---

src/test/groovy/BuildStatusTests.groovy
vars/buildStatus.groovy
vars/buildStatus.txt
vars/nexusCloseStagingRepository.groovy
vars/nexusFindStagingId.groovy
vars/nexusReleaseStagingRepository.groovy

Fixes an error where the key for the username was failing to lookup.

Fix nexus username key lookup

---

src/test/groovy/GitCmdStepTests.groovy
vars/gitCmd.groovy

Store logs in the .git folder when possible
To avoid adding dirty files in the git repo

[ignore] gitcmd files with the .git folder

---

vars/gitCmd.groovy

.git folder cannot be achived
See a build from the ITs:

fix archive files inside .git folder

---

vars/isBranch.groovy

Return a boolean, since it returned a string somehow
See https://github.com/elastic/e2e-testing/pull/469

Fix isBranch type

---

.ci/dockerImagesOpbeans.groovy
.ci/packer_cache.sh
vars/opbeansPipeline.groovy

Build and cache opbeans-php docke rimages
Faster
https://github.com/elastic/opbeans-php/issues/1

[opbeans-php] Add docker build and cache

---

src/test/groovy/BeatsWhenStepTests.groovy
vars/beatsWhen.groovy

Add a new beats when condition to exclude changeset matches
Support linting stages between beats project without running any mandatory stages.
Blocks https://github.com/elastic/beats/pull/23378

[beats] Support changeset exclusion

---

src/test/groovy/FilebeatStepTests.groovy
src/test/resources/filebeatTest/filebeat_container_config.json
vars/README.md
vars/filebeat.groovy
vars/filebeat.txt

use docker stop not kill
To kill the container directly is a little overwhelming, the default signal for `docker kill` is KILL

fix: use docker stop not kill

---

resources/webhook-template.groovy

It add a example of how to manage a webhook with `generic-webhook-trigger`
It can process the webhook payload into a job to implement functionality we do not have in Multibranch pipelines.

feat: example job to manane webhooks

---

vars/notifyBuildResult.groovy

Refactor `notifyBuildResult`
Helping with the maintainability.

[refactor] notifyBuildResult

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithGoEnvUnixStepTests.groovy
vars/withGoEnvUnix.groovy

Support ARM arch for installing Go/Mage with the withGoEnv step.
Fine granularity what to do
Blocks https://github.com/elastic/beats/pull/23592

[beats][go] support for ARM arch64

---

vars/withGoEnvUnix.groovy

Add debug traces for the go environment
Help to debug what's causing the issues with the arm builds for Beats
https://github.com/elastic/beats/pull/23592

Debug Go Environment

---

.ci/Jenkinsfile

Support /test trigger comment
Help with the onboarding similar to what other teams use.
Closes #ISSUE

Add /test trigger comment

---

.ci/buildDockerImages.groovy

Fix issue cased by small typo in path.

Docker integrations

---

resources/JenkinsfileTemplate.groovy

Explain the matrix step and dog-food in our pipeline
Facilitate the onboarding

[docs][matrix] explain the new step

---

local/workers/linux/Vagrantfile

* add some commands to resize the size of the main partition.
We are using only 12GB of 100GB

fix: resize the partition size to 100GB to use all the space

---

vars/githubPrCheckApproved.groovy

Allow mergify bot to run in our CI

Add mergify bot

---

vars/README.md
vars/setEnvVar.txt

It adds a side note to setEnvVar step
This side note avoid making mistakes using the step.

docs: side note to setEnvVar step

---

.ci/Jenkinsfile
.ci/jobDSL/jobs/customKibana.groovy
.ci/jobDSL/jobs/customKibanaUndeploy.groovy
.pre-commit-config.yaml

* is adds a stage to test the jobDSL jobs on PRs and merges.
Test the jobDSL is important to avoid errors when we trigger the job generator.

test: taest jobDSL job when them changed

---

vars/goDefaultVersion.groovy

chore: bump Go version

---

.grenrc.js
CHANGELOG.md

Exclude labels from the mergify in the changelog
Update changelog
Exclude commits with the `bc` message caused with the mergify automation
Make our changelog readable.

[release] changelog exclude some labels

---

.ci/buildDockerImages.groovy

Adds Docker build pipeline for [build analyzer](https://github.com/elastic/observability-dev/tree/master/apps/automation/build-analyzer).
Required for deployment.

Docker build pipeline for build analzyer

---

.ci/Jenkinsfile
vars/preCommit.groovy

Use python3 when possible to install the pre-commit
EOL for python2 with the pre-commit
Closes #ISSUE

Use python3 for installing the pre-commit

---

.ci/jobs/populate-github.yml
.ci/populateGithub.groovy
.ci/schedule-daily.groovy

Enable job to populate the data from the different obs11 repositories
Build dashboards with some insights , initially started with some of the ideas from the Kibana team

Populate GitHub issues/prs into ES

---

.ci/jobs/populate-github.yml

Fix the script name to camelcase syntax
Otherwise the pipeline will fail

[jjbb] Fix pipeline name with CamelCase syntax

---

src/test/groovy/NodeOSStepTests.groovy
vars/nodeOS.groovy

Categorise Darwin for ARM64 arch
Otherwise

Support arm64 MacOS M1 workers

---

.ci/populateGithub.groovy

Fix typo
Runtime error, so the linting didn't catch it :/ 
See [build](https://apm-ci.elastic.co/job/apm-shared/job/populate-github/3/console)

Fix pipeline syntax and make goal

---

CHANGELOG.md

It adds the missing entry in the changelog file
I forgot to add the right labels to the PR
- Will send another PR adding info about labels in PRs for the automated changelog generation
- The Github release has been updated in consequence

docs: manually update changelog

---

.ci/buildDockerImages.groovy

Build docker image for the rebuild analyzer
To be able to use it :)

Add rebuild analyzer docker generation

---

resources/scripts/beats/filebeat.yml
resources/scripts/beats/run_filebeat.sh
resources/scripts/beats/wait_for_beat.sh
src/test/groovy/FilebeatStepTests.groovy
vars/filebeat.groovy

* Minor refactor of the output variable use
* Avoid hiding errors when the container is not launched.
* * Bump the container version
When an error happens during the execution of the Docker container, it always shows an error reading the config file but there is one error before that.

chore: refactor filebeat step

---

resources/scripts/beats/metricbeat.yml
resources/scripts/beats/run_metricbeat.sh
resources/scripts/beats/wait_for_beat.sh
src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/MetricbeatStepTests.groovy
src/test/resources/metricbeatTest/metricbeat_container_worker-0676d01d9601f8191.json
src/test/resources/metricbeatTest_2/metricbeat_container_worker-0676d01d9601f8191.json
vars/README.md
vars/metricbeat.groovy
vars/metricbeat.txt

* add a new step to launch metricbeat and grab the host metrics.
This allows us to correlate logs, metrics and tests results

feat: metricbeat step

---

local/configs/google.yaml

Support linux workers which were not working recently as a consequence of the disk space issue.
Enable ephemeral workers

Add GCE JCasC

---

vars/stackVersions.groovy
vars/stackVersions.txt

chore: bump Elastic Stack versions

---

.mergify.yml

mergify: priority is now a pro feature

---

src/test/groovy/Base64encodeStepTests.groovy
vars/README.md
vars/base64encode.groovy
vars/base64encode.txt

It adds a parameter to disable base64 padding.
When you disable padding the base64 string contains only a-z, A-Z, 0-9 characters.

feat: allow to remove padding

---

vars/README.md
vars/metricbeat.txt

Updates the docs related to metricbeat step.

docs: update metricbeat step docs

---

.ci/Jenkinsfile

We are not really doing anything with the super-linter and it takes quite sometime to finish
Faster builds

Remove super-linter since it takes 20 minutes

---

.ci/schedule-weekly.groovy

Git checkout with credentials since it's a private repo
Enable dry-run mode if needed
Fix the automation and enable to dry-run

fix git checkout with credentials and add dry run

---

.ci/githubSyncupLabelsObsDev.groovy
.ci/jobs/github-syncup-labels-obs-dev-pipeline.yml

Create a pipeline for the syncup process
Weekly pipeline should trigger other pipelines instead of implementing how to do so.
Closes #ISSUE
In my local instance:
Failures related to some GitHub permissions in some repos

Specific pipeline for the Sync GitHub Labels automation

---

.ci/bumpStackVersion.groovy
src/test/groovy/GhStepTests.groovy
src/test/groovy/GithubPullRequestsStepTests.groovy
vars/githubPullRequests.groovy

- Different title
- `7.x` == `7.<minor>`
- If null avoid the validation.

Support 7.x == 7.<minor>

---

resources/scripts/install-with-choco.ps1

If a new version exists already in the workers it will fail
Workers are now using a newer version so let's allow to downgrade with chocolatey

[choco] allow-downgrade

---

.ci/bumpStackVersion.groovy
resources/scripts/artifacts-api-latest-versions.sh

In linux the script does not work
While it worked fine in MacOS.
I tested in linux and mac now:

Fix jq format for linux

---

.mergify.yml

Set title for the backported PRs with the branch target
Assign label
Test changes before merging them in some other projects

[mergify] change title to highlight the target branch

---

.ci/jobs/license-scan.yml

Tiny spelling error fix.
It's not even remotely important.

Fix spelling error in license job name

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithAPMEnvStepTests.groovy
vars/README.md
vars/withAPMEnv.groovy
vars/withAPMEnv.txt

Step to prepare the APM context that will be used by the body to send the data accordingly to the APM server.
Avoid duplicated code in some of the existing pipelines.
Closes #ISSUE

Step withAPMEnv

---

resources/JenkinsfileTemplate.groovy

[test-infra] no more ubuntu:16

---

resources/JenkinsfileTemplate.groovy

Run the build.bat on windows
To help with debugging what tools/versions tuples are installed.

[test-infra] enable runbuild on Windows

---

src/test/groovy/IsGitRegionMatchStepTests.groovy

Test the complex regex patter for the beats docs
Help with some UTs

test the beats docs pattern

---

vars/stackVersions.groovy

Bump stack version with the latest release. 
[6.8.16, 7.13.0, 7.13.1]

[automation] update elastic stack release version [6.8.16, 7.13.0, 7.13.1]

---

src/test/groovy/NotifyBuildResultStepTests.groovy
vars/notifyBuildResult.groovy

Avoid duplicated filters in the email manipulation
Only one filter

Avoid duplicated filters with custom emails

---

test-infra/apm-ci/test_installed_tools_docker.py
test-infra/apm-ci/test_installed_tools_extra.py
test-infra/beats-ci/test_beats_installed_tools.py

Validate if the docker daemon is up and running
This will help to mitigate any issues if the docker daemon was not active.
For the MacOS, there is pre-requisite to prepare the context -> https://github.com/elastic/apm-pipeline-library/blob/7e99ac14e26926c43b02da97870951ddb4e53c65/resources/scripts/jenkins/apm-ci/test-mac.sh#L26-L31

[test-infra] test docker is running

---

vars/stackVersions.groovy

Bump stack version with the latest release. 
[6.8.16, 7.13.0, 7.13.1, 7.13.2]

[automation] update elastic stack release version [6.8.16, 7.13.0, 7.13.1, 7.13.2]

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithClusterEnvStepTests.groovy
vars/README.md
vars/withClusterEnv.groovy
vars/withClusterEnv.txt

withClusterEnv step to be consumed by 
Simplify the pipeline with some logic in the shared library
Required by https://github.com/elastic/azure-vm-extension/pull/13

withClusterEnv step

---

src/test/groovy/RandomStringStepTest.groovy
vars/README.md
vars/randomString.groovy
vars/randomString.txt

Create a random string with the given size.
To help with https://github.com/elastic/azure-vm-extension/pull/13

Random String step

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithCloudEnvStepTests.groovy
vars/README.md
vars/withCloudEnv.groovy
vars/withCloudEnv.txt

withCloudEnv step to be consumed by 
Simplify the pipeline with some logic in the shared library
Required by https://github.com/elastic/azure-vm-extension/pull/13

withCloudEnv step

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithAzureEnvStepTests.groovy
vars/README.md
vars/withAzureEnv.groovy
vars/withAzureEnv.txt

withAzureEnv step to be consumed by 
Simplify the pipeline with some logic in the shared library
Required by https://github.com/elastic/azure-vm-extension/pull/13e

withAzureEnv step

---

.ci/bumpGoReleaseVersion.groovy

Bump pipeline are a kind of similar but with minor changes. Fix the goVersion format from a list to a string.
Fixes a bug in the pipeline

fix C&P, goVersion is not a list

---

.ci/bumpGoReleaseVersion.groovy
.ci/bumpStackReleaseVersion.groovy

Elvis operator was using the inverse logic
Otherwise empty titles with the goversion only

Title was not shown, inverse logic

---

.ci/jobs/apm-ui-pipeline-inline.yml

Remove unused pipeline

---

resources/scripts/beats/run_filebeat.sh
resources/scripts/beats/run_metricbeat.sh
src/test/groovy/FilebeatStepTests.groovy
src/test/groovy/MetricbeatStepTests.groovy
vars/filebeat.groovy
vars/metricbeat.groovy

It print some env vars to debug issues.
Without this info, we do not know where the info will be write/read

chore: add some more logs

---

.ci/validateWorkersBeatsCi.groovy

Reverts elastic/apm-pipeline-library#1172

Revert "chore: enable macOS workers again"

---

.ci/validateWorkersBeatsCi.groovy

Reverts elastic/apm-pipeline-library#1173

Revert "Revert "chore: enable macOS workers again""

---

.ci/bumpGoReleaseVersion.groovy
.ci/bumpStackReleaseVersion.groovy
.ci/bumpStackVersion.groovy

Title argument to contain the version then the `prepareArguments` function is the one to prepare all the arguments consumed by other functions.
Otherwise the title validation does not contain the version and therefore cannot create the PRs

Title argument should contain the version in it

---

vars/opbeansPipeline.groovy

Run on a weekly basis if master branch
To detect any breaking changes in case it uses snapshots or non-fixed dependencies.

CI: run on a weekly basis master branch

---

resources/scripts/build-kibana-docker-image.sh

* Removes the `--no-oss` flag is no longer used.
the compilation fails with that option.

fix: remove --no-oss flag

---

.ci/Jenkinsfile

Test https://github.com/elastic/apm-pipeline-library/pull/1193
Ensure we test before we release it
Closes #ISSUE

Test the validation in the google-storage-ext step

---

resources/JenkinsfileTemplate.groovy

* It increases the timeout of the test pipeline.

fix: increase timeout

---

local/Dockerfile

Update jenkins version with the latest available one
Update our services with the ones in production

bump version and use plugin-manager-cli

---

src/test/groovy/GoogleStorageUploadExtStepTests.groovy
vars/googleStorageUploadExt.groovy

Reverts elastic/apm-pipeline-library#1193
Somehow beats packaging started failing, so let's see if this is somehow wrong

Revert "Validate if pattern in googleStorageUploadExt returns any matches"

---

.ci/Jenkinsfile

Reverts elastic/apm-pipeline-library#1204

Revert "Test the validation in the google-storage-ext step"

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/destroy_oblt_cluster.groovy

New pipeline to destroy clusters

feat: pipeline to destroy clusters

---

.ci/jobDSL/build.gradle
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/custom_kibana_deploy.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/custom_kibana_undeploy.groovy
.ci/jobdsl-generator.groovy

* It adds parameters to the jobDSL definition
*
This avoids having to run the pipeline once to have the parameters

Add parameters

---

vars/README.md
vars/withOtelEnv.groovy
vars/withOtelEnv.txt

Add `service.name` env variable. See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration
Use the otel context from the Jenkins controller.

Add OTEL_SERVICE_NAME env variable

---

vars/withOtelEnv.groovy

Fixes serialisation issue when using the `withOtelEnv` step
It fails silently
Unblocks https://github.com/elastic/apm-agent-java/pull/2103

Fix serialisation in JenkinsOpenTelemetryPluginConfiguration

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithOtelEnvStepTests.groovy
src/test/groovy/co/elastic/mock/OtelHelperMock.groovy
vars/otelHelper.groovy
vars/otelHelper.txt
vars/withOtelEnv.groovy

Added UTs for the `withOtelEnv`, for such, I refactored and created a private shared library step called `otelHelper` to be able to mock the access to the `Jenkins` object.
Ensure we cover all the test cases

UTs for the withOtelEnv

---

vars/isPluginInstalled.groovy
vars/otelHelper.groovy

Fixes
```
[2021-09-08T15:31:36.799Z] Caused: java.io.NotSerializableException: hudson.PluginWrapper
[2021-09-08T15:31:36.799Z] 	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:926)
[2021-09-08T15:31:36.799Z] 	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
[2021-09-08T15:31:36.799Z] 	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
[2021-09-08T15:31:36.799Z] 	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
[2021-09-08T15:31:36.799Z] 	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
[2021-09-08T15:31:36.799Z] 	at …
```

Fix serialisation with hudson.PluginWrapper

---

.ci/beats-webhook.groovy
.ci/jobs/beats-webhook.yml

Use https://plugins.jenkins.io/generic-webhook-trigger/ to listen for events that will cause some actions
To iterate in the script in charge of the backport.

Beats webhook proof of concept

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/create_ccs_oblt_cluster.groovy

* change the pipeline branch to master
Related to https://github.com/elastic/observability-robots/issues/631

chore: update the branch of the ccs pipeline

---

vars/nexusFindStagingId.groovy
vars/nexusFindStagingId.txt

Add more log traces for `nexusFindStagingId`
Help to debug what's going on

Add more debugging traces for nexusFindStagingId

---

.gitignore
local/.gitignore
local/Makefile
resources/scripts/generate-build-data.sh
src/test/groovy/GenerateBuildDataIntegrationTests.groovy

It translates the comments in `GenerateBuildDataIntegrationTests` to automation scripts to simplify the execution of the tests based on Wiremock.
For that a few Make goals have been created trying to reproduce the steps described in that Groovy file, updating the comments in consequence.
Simplify the execution of the tests using wiremock

feat: automate preparation of wiremock tests

---

.mergify.yml

Add backport policy
Test https://github.com/elastic/apm-server/pull/6186

[mergify] test the backport policy

---

.mergify.yml

Reverts elastic/apm-pipeline-library#1283

Revert "[mergify] test the backport policy"

---

.ci/Jenkinsfile
.ci/buildDockerImages.groovy
.ci/dockerImagesOpbeans.groovy
resources/JenkinsfileTemplate.groovy
vars/opbeansPipeline.groovy

Use obltGitHubComments
Remove hardcoded GitHub comments

Use obltGitHubComments

---

src/co/elastic/NotificationManager.groovy

Add the `apm-server` GitHub commands
See https://github.com/elastic/apm-server/pull/6206

GitHub commands for the apm-server

---

src/co/elastic/NotificationManager.groovy

Fix GitHub command for the apm-agent-nodejs as stated in https://github.com/elastic/apm-agent-nodejs/pull/2345#pullrequestreview-762157365

Fix nodejs GitHub command

---

.ci/dockerImagesOpbeans.groovy
vars/retryWithSleep.groovy
vars/retryWithSleep.txt

Allows the use of an optional closure to be run before each retry. This is useful for things like resetting the environment prior to a retry.
Refs https://github.com/elastic/apm-agent-nodejs/issues/2293

Retry side effect

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/GsutilStepTests.groovy
src/test/groovy/WithGCPEnvStepTests.groovy
vars/README.md
vars/gsutil.groovy
vars/withGCPEnv.groovy
vars/withGCPEnv.txt

Refactor `gsutil` in order to support a new step called withGCPEnv
Help to interact with the GCP.

Add withGCPEnv step

---

.ci/updateStackReleaseVersion.groovy

Set the empty hash
Otherwise it will fail with a NPE

bump release version: fix NPE

---

vars/beatsWhen.groovy

Similar to https://github.com/elastic/apm-pipeline-library/pull/1336
Fix the current issue

Fix serialisation issue with java.util.regex.Matcher 

---

.ci/bumpGoReleaseVersion.groovy
.ci/bumpStackReleaseVersion.groovy
.ci/bumpStackVersion.groovy
.ci/updateStackReleaseVersion.groovy
.pre-commit-config.yaml
src/test/groovy/BumpUtilsStepTests.groovy
vars/bumpUtils.groovy
vars/bumpUtils.txt

Refactor common functionality.
Fix undefined env variables.
Fix codespell

Refactor parseArguments for the bump automation

---

.ci/updateStackReleaseVersion.groovy

Define message otherwise it will fail

Set the message for the updateStackReleaseVersion

---

.ci/bumpStackReleaseVersion.groovy
.ci/updateStackReleaseVersion.groovy
src/test/groovy/BumpUtilsStepTests.groovy
vars/bumpUtils.groovy

New functions to support:
- areStackVersionsAvailable -> to validate if the given list of releases/snapshots are available
-  current7Key
- current6Key
- nextMinor7Key
- nextPatch7Key
Fix missing arguments
Initial support for 8.x branches
Back to business the bump automation

Refactor properties key and search for all the docker images

---

resources/ci-builds-mapping.json
resources/scripts/generate-build-data.sh
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_abort_runs_1_log-8af6681b-d3a1-4a7e-9a4f-217d6ff17541.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_empty_runs_1_log-5112a750-8f3f-4fde-8051-7d88f508da5f.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_error_runs_1_log-844f7f75-8fcf-41e4-80f8-4fa1bd4be506.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_multitestfailures_runs_1_log-f78c0b1b-c892-4c95-8b42-0fd3a0cf5204.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_success_runs_1_log-dd0fd32c-55a5-45e3-880c-25d188dfde63.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_unstable_runs_1_log-5cd4b2df-95a8-49af-8443-9732239d5959.json
src/test/resources/mappings/mapping-blue-rest-organizations-jenkins-pipelines-it-getBuildInfoJsonFiles-cobertura-runs-1-log-iMg03.json

Analyse the console output in order to count the number of exceptions that could be potentially related to the flakiness in the CI.
Ideally, we can build some dashboards to monitor the number of failures and correlate them with the exceptions detected in the build logs.
Easy to visualise errors
```bash
resources/scripts/generate-build-data.sh \
https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/apm-agent-nodejs-mbp/master/ \
https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-nodejs/apm-agent-nodejs-mbp/master/runs/1151 \
SUCCESS \
5794469
```
produces:
```json
"analysis": {
"reusedWorkers": 0,
"closedChannelException": 0,
"liveNode": 0,
"missingContextVariableException": 0,
"interruptedException": 2
},
``` …

Gather environmental errors with the workers

---

src/test/groovy/GhStepTests.groovy
vars/README.md
vars/gh.groovy
vars/gh.txt

Set the gh version to be installed and whether to force the installation regardless
GH output might differ between versions so let's help the consumers to deefine what version to be used.

Add gh version and forceInstallation paramters

---

resources/versions/releases.properties

Bump stack version with the latest one. 
[current_6:6.8.20, current_7:7.15.1, next_minor_7:7.16.0, next_patch_7:7.15.2, current_8:8.0.0, next_minor_8:8.1.0, next_patch_8:8.0.1]

[automation] Update Elastic stack release version source of truth

---

vars/getModulesFromCommentTrigger.groovy
vars/githubPrLatestComment.groovy
vars/isGitRegionMatch.groovy
vars/preCommitToJunit.groovy

A third attempt to solve the serialisation issue with the Matcher
Solve eventual build errors that are not that common but painful!
Similar to https://github.com/elastic/apm-pipeline-library/pull/1344/

Fix serialisation issue with the Matcher pattern

---

src/test/resources/jobs/gce-test.dsl

this job fails to load due to concurrentBuild(boolean) is not valid

fix: remove concurrentBuild

---

src/test/groovy/BuildKibanaDockerImageStepTests.groovy
vars/buildKibanaDockerImage.groovy

* Pushes a new label with the Stack version in it.
This helps to identify which version is the Docker image.

feat: push a tag with the Stack version

---

src/co/elastic/NotificationManager.groovy

* Add new commands to the GitHub comment we post in PRs
This helps to do not have to remember the GitHub comments to trigger build

feat: report apm Python chatOps

---

.mergify.yml

Test the schedule works with this format

mergify: once a week

---

src/test/groovy/GithubReleasePublishTests.groovy
vars/githubReleasePublish.groovy

Fix the publishing by transition a draft one to ready
Otherwise, releases are not published

Fix publishing github release

---

.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/stack_docker_images.groovy

* fix: add branch_specifier parameter 
* fix: add a trigger to Elastic Stack…docker images job

fix: add branch_specifier parameter 

---

.mergify.yml

I don't know if the `updated` could be related to no just changes in the files but added/removed labels, github comments.
So let's also try with created

[mergify] verify the creation

---

.ci/updateStackReleaseVersion.groovy

Bump the versions in the pipeline in charge to update them

Bump versions

---

vars/buildKibanaDockerImage.groovy

* Refactor tag and push Docker images
* tag/push Kibana-cloud Docker images
It'd allow us to use the kibana-cloud Docker image in our Deeploy Kibana PRs

feat: push kibana-cloud Docker images

---

vars/githubWorkflowRun.groovy
vars/githubWorkflowRun.txt

Deleted setting runner parameter as mandatory argument for workflow.
This parameter is specific to the workflow so it should not be set by default and added to any workflows mandatory.

Deleted setting runner parameter as mandatory argument for workflow.

---

.ci/schedule-weekly.groovy

Automate the versions for the emails with the flaky tests, for such, it consumes https://github.com/elastic/apm-pipeline-library/blob/master/resources/versions/releases.properties through the existing API contract.
`7.<next>` will be removed eventually, once `7.16` is cut and replaced with `8.<next>`
One step closer to avoid updating them manually.
Customise the watchers to support parameters therefore the branch could be passed when calling the watcher
So far I enabled the branches until 8.5

[weekly] support for the source of truth

---

.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* Set the correct name for the parameters names

fix: params names

---

src/test/groovy/IsInstalledStepTests.groovy
vars/isInstalled.groovy

Support the corner case when the tool is not available and the version is provided...
Otherwise it will fail

Support when the tool is not installed

---

.ci/build-docker-images.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* fix: support branches 
* fix: support ssh checkouts

fix: support checkout branches 

---

.ci/docker/kibana-devmode/Dockerfile
.ci/docker/kibana-yarn/Dockerfile

* set main as default Kibana refspec

fix: set main as default Kibana refspec

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/DownloadStepTests.groovy
src/test/groovy/WithGCPEnvStepTests.groovy
src/test/groovy/WithGhEnvStepTests.groovy
vars/README.md
vars/download.groovy
vars/download.txt
vars/withGCPEnv.groovy
vars/withGhEnv.groovy

Add new step to download either using wget or curl.
Refactor the consumers
Keep our code simpler

Add download step

---

.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* change docker_build_opts to build_opts

fix: change docker_build_opts to build_opts

---

vars/githubWorkflowRun.groovy

Reduce default sleep to 2 minutes
When actions take a few minutes it's not worthy to wait for another 4 minutes

reduce sleep from 5 minutes to 2 minutes

---

.ci/build-docker-images.groovy
.ci/docker/apache-ant/Dockerfile
.ci/docker/kibana-devmode/Dockerfile
.ci/docker/kibana-yarn/Dockerfile
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* Fix some Docker image builds https://apm-ci.elastic.co/job/apm-shared/job/docker-images/

fix: Fix docker images

---

.ci/Jenkinsfile

Skip stage if no changes in those files
Speed up builds
Supersedes https://github.com/elastic/apm-pipeline-library/pull/1437

only if changes in the files

---

CHANGELOG.md

Fix spelling so lint job passes.

Fix spelling

---

.ci/build-docker-images.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* Fix an issue during the checkout of repos on a different branch than the Jenkinsfile
* Fix an issue related to the timeout in some Docker builds

fix: latest issues on Docker images 

---

.ci/updateStackReleaseVersion.groovy

Manually bump the references to the new releases for 7 and 6 major branches
No yet automated how to gather those details, so for the time being we do this manually

manually bump releases

---

.ci/buildDockerImages.groovy
.ci/jobs/gather-ci-metrics-pipeline.yml

Rename master to main
Neutral naming of git branches

[jjbb][main] neutral naming for observability-robots

---

.ci/dockerImagesOpbeans.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
src/test/groovy/OpbeansPipelineStepTests.groovy
vars/opbeansPipeline.groovy

Rename master branch for the opbeans projects

Opbeans: rename master for main

---

.ci/buildDockerImages.groovy

obs-robots main branch

---

vars/runE2E.groovy

Use main rather than master for the e2e-testing call
Fixes

Support main for e2e-testing

---

.ci/updateStackReleaseVersion.groovy
resources/versions/releases.properties

Bump the versions for the upcoming release

Bump releases [6.8.23, 7.16.3, 8.0.0-rc]

---

.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

Change some references to use the `main` branch

chore: change to use the main branch

---

.ci/updateStackReleaseVersion.groovy

7.17.0 is now out, let's update the file
Automate this

release: 7.17.0

---

.ci/.bump-go-release-version.yml
.ci/.bump-stack-release-version.yml
.ci/.bump-stack-version.yml
.ci/beats-webhook.groovy
.ci/buildBeatsDockerImages.groovy
.ci/buildDockerImages.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
.ci/schedule-weekly.groovy
resources/flaky-watcher.json
resources/webhook-template.groovy
src/test/groovy/GitChangelogStepTests.groovy
vars/README.md
vars/gitChangelog.groovy
vars/githubReleaseCreate.groovy
vars/githubWorkflowRun.txt

Update final bits regarding the automation for Beats/FleetServer/APM Server and some other projects that have been migrated to use main instead master.

main: references in beats and other projects

---

.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* Fix the APM proxy Docker image build pipeline

fix: apm proxy Docker image build

---

.ci/build-docker-images.groovy
.ci/docker/kibana-yarn/Dockerfile
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

Fixes some Docker image builds

fix: some mistakes

---

.ci/build-docker-images.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

fix: login in DockerHub
* fix clone of Docker images from docker.io to docker.elastic.co

fix: remove variables

---

INTEGRATIONS.md
README.md

Digest existing support steps in categories of integrations
Help to list what's supported in this library

docs: list of supported integrations

---

.ci/schedule-daily.groovy

fix: remove deleted jobs

---

.ci/.bump-stack-version.yml
.ci/updateStackReleaseVersion.groovy

release: 6 major branch reached EOL

---

resources/scripts/build-kibana-docker-image.sh

* update the Kibana build script to the latest changes
The old command does not generate the kibana-cloud images anymore.

fix: update the Kibana build script to the latest changes

---

vars/buildKibanaDockerImage.groovy
vars/buildKibanaDockerImage.txt

*  add depth and reference parameters to buildKibanaDockerImage
This allows grabbing commit SHA other than the latest

feat: add depth and reference parameters to buildKibanaDockerImage

---

vars/buildKibanaDockerImage.groovy
vars/buildKibanaDockerImage.txt

* allow disable shallow cloning

feat: allow disable shallow cloning

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/GoogleStorageUploadExtStepTests.groovy
src/test/groovy/UploadPackagesToGoogleBucketExtStepTests.groovy
vars/README.md
vars/googleStorageUploadExt.groovy
vars/googleStorageUploadExt.txt
vars/uploadPackagesToGoogleBucket.groovy
vars/uploadPackagesToGoogleBucket.txt

Provide a step to interact with a Google Bucket.
DRY

Enable uploadPackagesToGoogleBucket step for Beats/ElasticAgent

---

src/test/groovy/UploadPackagesToGoogleBucketExtStepTests.groovy
src/test/groovy/WithGCPEnvStepTests.groovy
vars/uploadPackagesToGoogleBucket.groovy
vars/withGCPEnv.groovy

Fix null values
Help with debugging since it fails but it's hard to know what's the genuine reason

Ensure null values are captured

---

.ci/updateStackReleaseVersion.groovy

Manual step to bump the next patch release
To syncup with the upcoming releases

Bump to the next patch release

---

src/co/elastic/NotificationManager.groovy

Add GitHub commands for the elastic-agent project
Better usability in the GitHub comments with the build status

GitHub commands for the elastic-agent project

---

resources/scripts/build-kibana-docker-image.sh

* Show time of each command
* Fix nvm command check
* Fix node install in case the version exists
* Fix global folder creation

fix: Node.js install issues

---

.ci/updateStackReleaseVersion.groovy

7.17.1 is the next patch release for the 7 line
Keep the automation in place

[automation] 7.17.1 is now available

---

.ci/bumpStackReleaseVersion.groovy

Support for `8`
So far only 7 releases

automation: support 8 and 7 major branches

---

.ci/schedule-weekly.groovy

Use getBranchesFromAliases and enable 8.1 branch
8.1 was not enabled and `getBranchesFromAliases` provides all the internals to use the alises.

weekly: refactor with getBranchesFromAliases

---

src/co/elastic/NotificationManager.groovy

Add GitHub command for https://github.com/elastic/apm-server
Enables GitHub commands for https://github.com/elastic/apm-server/pull/7375

github command: test on windows

---

.ci/bumpGoReleaseVersion.groovy

Add a link to the changelog for the Golang
Help with the decision to merge the changes
Caused by https://github.com/elastic/beats/pull/30703

Add Golang changelog in the PR

---

.ci/fleet-ci-jobdsl-generator.groovy
.ci/jobDSL/jobs/fleet-ci/k8s/apm_agent_java_mbp.groovy

Use the workaround from https://github.com/jenkinsci/job-dsl-plugin/pull/1193
To avoid the delete/create issues with JobDSL
Closes https://github.com/elastic/apm-pipeline-library/issues/1586

jobdsl: avoid delete

---

.ci/bumpGoReleaseVersion.groovy

Fix golang version pointing to a wrong version in the PR title and description, the changes and commit are correct
https://github.com/elastic/golang-crossbuild/pull/165 pointed to `1.17.8`:
Avoid any misleading
https://github.com/elastic/apm-pipeline-library/pull/1591 was the original change but missed some env variables...

fix golang bump with misleading go version in description

---

.ci/Jenkinsfile
src/co/elastic/NotificationManager.groovy
src/test/groovy/WithGCPEnvStepTests.groovy
vars/withGCPEnv.groovy

Platform agnostic while tearing down the GCP configuration.
Support to validate CI stages more dynamically (with a github command)
Fixes
See https://github.com/elastic/beats/pull/30907#issuecomment-1073805076

withGCPEnv: solve path separator on windows

---

vars/beatsWhen.groovy
vars/getGitMatchingGroup.groovy
vars/getModulesFromCommentTrigger.groovy
vars/preCommitToJunit.groovy

Solve the serialisation issue that happens sometimes in the Beats pipeline
Reduce failed builds
Closes https://github.com/elastic/apm-pipeline-library/issues/1635

Fix serialisation issues

---

resources/scripts/release-manager-analyser.sh
resources/scripts/release-manager.sh
src/test/groovy/ReleaseManagerStepTests.groovy
vars/releaseManager.groovy
vars/releaseManager.txt
vars/releaseManagerAnalyser.groovy

Cosmetic changes in the UI
Add a new flag to configure the branch
Redirect the stderr to the file to be analysed afterwards
To help with debugging the DRA execution

cosmetic changes in the release manager 

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/update_oblt_cluster.groovy

We are going to reuse the update cluster pipeline to make the daily test updates

chore: test update cluster pipeline

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/update_oblt_cluster.groovy

It adds the parameters to the jobDSL definition

chore: update parameters

---

src/co/elastic/NotificationManager.groovy

Add a new github command for https://github.com/elastic/synthetics-recorder/
Caused by https://github.com/elastic/synthetics-recorder/pull/227

github command for synthetics-recorder

---

vars/preCommit.groovy

Help to debug what files are found to be linted when using the pre-commit
Debug what's going on under the hood
Closes #ISSUE

print list of files to be linted

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/update_dev_clusters.groovy

Fix issue in update developer clusters job.

Update dev clusters

---

.ci/docker/dind-buildx/Dockerfile
.ci/docker/dind-buildx/build-example.sh
.ci/docker/dind-buildx/config.json
.ci/docker/dind-buildx/docker-credential-env
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* It adds a Docker in Docker image with support for build and Docker compose
This Docker image homogenizes the tools we use across pipelines.

feat: DinD buildx Docker image

---

src/test/groovy/WithTerraformEnvStepTests.groovy
vars/README.md
vars/withTerraformEnv.groovy
vars/withTerraformEnv.txt

Add withTerraformEnv step.
Refactor Beats and the apm-agent-dotnet
If the tool is installed and matches with the given version the report about it. This should help to use the installation from the worker if the version matches.
https://github.com/elastic/apm-agent-dotnet/pull/1707
https://github.com/elastic/beats/pull/31663

withTerraformEnv step

---

src/test/groovy/PushDockerImagesStepTests.groovy
vars/pushDockerImages.groovy

Add for debugging purposes
Somehow some docker images are not published, so likely their docker image name has changed but we don't have a way to know this easily.

List existing docker images

---

resources/scripts/pytest_otel/CHANGELOG.md
resources/scripts/pytest_otel/README.md
resources/scripts/pytest_otel/tests/it/utils/__init__.py

it updates the README and the CHANGELOG with the latest changes after the release
Those files should be upated

feat: pytest-otel 1.1.0 release notes

---

src/test/groovy/ApmBasePipelineTest.groovy
vars/apmCli.groovy
vars/getTestClusterSecret.groovy
vars/getTestClusterSecret.txt
vars/withCloudEnv.groovy
vars/withClusterEnv.groovy

Add getTestClusterSecret to store the vault secret location 
Avoid hardcoded paths in different places

Refactor getTestClusterSecret

---

src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy

Add new label in the automated github issues
Help with the filtering

[github] add label for filtering build errors as github issues

---

.ci/schedule-daily.groovy
.ci/schedule-weekly.groovy

Run daily instead
Avoid gaps in the labels for longer than 1 day

github label: run on a daily basis instead

---

.ci/Jenkinsfile

disable skip checkout since we use the `checkout/stash` pattern
Remove unrequired checkouts per stage

ci: skip default checkout

---

resources/pods/dind-golang.yml
resources/pods/dind-python.yml
resources/pods/golang.yml
resources/pods/python.yml

* It adds 4 pod examples 
This pod templates can be used to launch Jenkins agents pods

feat: pod templates

---

.ci/jobDSL/build.gradle
.ci/jobDSL/gradle.properties
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/custom_kibana_undeploy.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge_lite.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/release.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/test_mbp.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/updatecli.groovy
.ci/jobDSL/templates/mbp.groovy.j2
.github/dependabot.yml

* [fix: remove comment trigger from updeploy Kibana](https://github.com/elastic/apm-pipeline-library/pull/1765/commits/b630b0c2d7396f32c0d922beda7534aabbba50ee)
* [feat: enable Github Webhook Trigger](https://github.com/elastic/apm-pipeline-library/pull/1765/commits/00c3e003592a42ac85f95eaa5438a448f3440c5f)
* [feat: updatecli job](https://github.com/elastic/apm-pipeline-library/pull/1765/commits/d5e4c97969d39aa03433853cad1705e5df38e95c)
* [chore: oblt clusters release pipeline moved](https://github.com/elastic/apm-pipeline-library/pull/1765/commits/efc933d057551b953e6ed1627ea60e96b7cc5ec6)
* [test: MBR jobs again](https://github.com/elastic/apm-pipeline-library/pull/1765/commits/f6672ea23d9ecb0f6b33ca5d05e7299017c64ba0)
* update gradle dependencies
* configure dependabot for gradle

feat: updatecli job

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/IsDarwinStepTests.groovy
vars/isDarwin.groovy
vars/isDarwin.txt

Step to know if the existing worker is a darwin based one
Simplify consumers

Support for isDarwin step

---

resources/scripts/pytest_otel/docs/demos/jaeger/config/otel-collector-config.yaml
resources/scripts/pytest_otel/docs/demos/jaeger/docker-compose.yml

It updates the pytest_otel demo it was broken, the Otel Collector used was outdated.

fix: update the pytest_otel demo

---

.github/workflows/build-test.yml
.github/workflows/job-dsl.yml
.github/workflows/licenses.yml
.github/workflows/pre-commit.yml

Filter when to run actions (on PRs by default , and on branches on main only)
If a branch in the upstream with a PR, then it will run twice
Closes https://github.com/elastic/apm-pipeline-library/issues/1808

actions: push on main and pull requests

---

.ci/docker/jenkins-agent/Dockerfile

Update the docker base image to a non EOL one
Security!

Update base image to alma

---

.ci/docker/jenkins-agent/Dockerfile

Add gh/hub for automating some actions
It's used implicitly by the go bump automation

Install gh and hub in the docker k8s 

---

src/test/groovy/IsBranchUnifiedReleaseAvailableStepTests.groovy
vars/isBranchUnifiedReleaseAvailable.groovy

Attempts to fix the broken check for `isBranchUnifiedReleaseAvailable`.
builds are broken
N/A

fix unified-release branch check

---

.ci/bumpGoReleaseVersion.groovy
.ci/bumpStackReleaseVersion.groovy
.ci/chatops.groovy
.ci/fleet-ci-schedule-daily.groovy
.ci/schedule-daily.groovy
.ci/schedule-weekly.groovy
.ci/validateWorkersBeatsCi.groovy

This reverts commit d50798dd4acf3192e6e4060314d71e351c4065b9.

Revert ci: enable k8s workers (#1775)"

---

resources/JenkinsfileTemplate.groovy
test-infra/apm-ci/test_installed_tools.py

Update the list of baremetals and fix the java10 
Closes https://github.com/elastic/apm-pipeline-library/issues/1836

infra-test: update test pipeline

---

.github/dependabot.yml

It adds the pytest_otel dependabot configuration.

feat: add pytest_otel dependabot configuration

---

.github/CODEOWNERS
.github/workflows/pytest_otel.yml

It adds a workflow to lint and test the pytest_otel plugin

feat: pytest_otel workflow

---

vars/githubPrCheckApproved.groovy

It add the `github-actions[bot]` to authorized bots

feat: add github-actions[bot] to authorized bot

---

.github/workflows/pytest_otel.yml

* it fixes the filter path 
* it reports JUnit test results

fix: path filter incorrect

---

.github/workflows/pytest_otel.yml
.gitignore
resources/scripts/pytest_otel/Makefile
resources/scripts/pytest_otel/mypy.ini
resources/scripts/pytest_otel/pyproject.toml
resources/scripts/pytest_otel/requirements.txt
resources/scripts/pytest_otel/setup.cfg
resources/scripts/pytest_otel/tests/docker-compose.yml

It updates the OpenTelemetry SDK to 1.12.0

chore: bump Otel 1.12.0

---

resources/scripts/pytest_otel/README.md

missing change in the README before the release

docs: update readme with the new Otel versions required

---

resources/scripts/pytest_otel/Makefile

it adds a missing file to the clean target

fix: delete src/pytest_otel.egg-info on clean

---

src/test/groovy/WithNodeJSEnvUnixStepTests.groovy
vars/withNodeJSEnvUnix.groovy

Report error if nodejs version installed with nvm cannot be accessed.
Help with reporting environmental issues when installing nodejs on the fly.

report error if nodejs version cannot be found

---

.github/workflows/build-test.yml
.github/workflows/job-dsl.yml
.github/workflows/opentelemetry.yml
.github/workflows/test-reporter.yml

Report the test results that were executed in GitHub actions
Help to visualise the test results

action: report test results

---

src/test/groovy/PreCommitStepTests.groovy
vars/preCommit.groovy

Use the official installation with pip for the `pre-commit`
Move away from the deprecated installation and support for `ubuntu-22` with `python-3.10` since it fails otherwise
```
[2022-11-01T14:04:12.332Z] + PYTHON_COMMAND=python
[2022-11-01T14:04:12.332Z] + command -v python3
[2022-11-01T14:04:12.332Z] /bin/python3
[2022-11-01T14:04:12.332Z] + PYTHON_COMMAND=python3
[2022-11-01T14:04:12.332Z] + + python3curl - -s
[2022-11-01T14:04:12.332Z]  https://pre-commit.com/install-local.py
[2022-11-01T14:04:13.740Z] Using base prefix '/usr'
[2022-11-01T14:04:13.740Z] New python executable in /var/lib/jenkins/workspace/apm-pipeline-library-mbp_PR-1928/.pre-commit-venv/bin/python3
[2022-11-01T14:04:13.740Z] Also creating executable in /var/lib/jenkins/workspace/apm-pipeline-library-mbp_PR-1928/.pre-c …
```

install pre-commit with pip

---

.github/actions/test-report/action.yml

GitHub action for the test reporting
to help with what version to be used

action: test-report

---

.github/actions/version-framework/action.yml

ExcludeFile is optional
Otherwise:
```
Run import json
Traceback (most recent call last):
File "/home/runner/work/_temp/7c72b4e4-4897-4274-ab8b-540537baa31f.py", line 5, in <module>
excludes = yaml.safe_load(Path('').read_text())
File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
with self.open(mode='r', encoding=encoding, errors=errors) as f:
File "/usr/lib/python3.8/pathlib.py", line 1222, in open
return io.open(self, mode, buffering, encoding, errors, newline,
IsADirectoryError: [Errno 21] Is a directory: '.'
```

action: exclude is optional

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/SnapshotyStepTests.groovy
vars/README.md
vars/snapshoty.groovy
vars/snapshoty.txt

Enable `snapshoty` to upload artifacts
Simplify consumers such as https://github.com/elastic/apm-agent-python/pull/1700/

Support snapshoty step

---

.github/actions/docker-layer-caching/action.yml
.github/workflows/actions-test.yml

Adds a github action facade for https://github.com/marketplace/actions/docker-layer-caching
Will be used in https://github.com/elastic/ecs-logging-ruby/pull/28
- https://github.com/elastic/ecs-logging-ruby/pull/28

Add docker-layer-caching action facade

---

.github/workflows/opentelemetry.yml

Use secrets explicitly
They cannot be accessed from outside the original workflow, hence it cannot be accessed from a composite action

action: use with secrets parameters

---

.ci/Jenkinsfile
.github/workflows/opentelemetry.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml

Run pre-commit in a GitHub action
downside: removed support for validating jjbb and pipelines as part of the pre-commit for this project
although we don't change them often

action: use pre-commit

---

src/test/groovy/IsBeforeGo1_16StepTests.groovy
vars/isBeforeGo1_16.groovy

Support for versions with rc
Otherwise we cannot test those rc versions in advance

support for golang rc versions

---

.github/actions/buildkite/README.md
.github/actions/buildkite/action.yml
.github/actions/buildkite/run.sh

Action to run buildkite pipelines from GitHub
Help with the transition
- Use docker instead?
- Use typescript action instead?

action: buildkite composite action

---

.github/actions/buildkite/README.md
.github/actions/buildkite/action.yml
.github/actions/buildkite/run.sh

Customise commit and message in addition to use the outputs
Those fields are needed so when running a pipeline from a different github repository

action: support pipeline version in BK

---

.github/actions/snapshoty/package-lock.json

Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
* Update npm dependencies
* Fix security issues
Closes #1994

Update snapshoty dependencies (Closes #1994)

---

README.md
docs/DEVELOPMENT.md

Clarify what's the status for supporting Jenkins in terms of adding support for new features or bugs
Add entry for GitHub actions
Clear message about this particular repository.

chore: add GitHub reference and update Jenkins status

---

.github/workflows/generate-elastic-stack-snapshots.yml

I badly added the `rm` but it's not required

action: leftover from a local test

---

.github/actions/updatecli/action.yml

Configure env with the secrets
They are not automatically populated within the composite action

action: it's required to pass those secrets

---

.github/actions/comment-reaction/README.md
.github/actions/comment-reaction/action.yml
.github/workflows/test-comment-reaction.yml

Composite GitHub action to react to any given comment with an emoji
This will help us to provide feedback to any GitHub command, so the user will know if the command has been listened by the automation
Relates https://github.com/elastic/apm-pipeline-library/issues/1904
See  https://github.com/v1v/apm-pipeline-library/pull/150#issuecomment-1436814779
https://github.com/v1v/apm-pipeline-library/actions/runs/4223008810/jobs/7332209838

action: comment-reaction composite action

---

.github/actions/comment-reaction/action.yml
.github/actions/is-member-elastic-org/action.yml

Use GH_TOKEN for the gh cli
Avoid header but using env variables for simplicity

action: use GH_TOKEN

---

.github/actions/notify-build-status/README.md

Update README of notify-build-status action with a better example.
Closes #ISSUE

Add better notify-build-status example

---

.github/actions/snapshoty-simple/action.yml

Send slack notification and ping the CI robots team if something bad happened when running Snapshoty
We own the Snapshoty process, let's get notified if something bad happens.

snapshoty-simple: report any failures with snapshoty

---

.github/actions/test-report/action.yml

See https://github.com/elastic/apm-pipeline-library/issues/2063
Use https://github.com/phoenix-actions/test-reporting

action: use  https://github.com/phoenix-actions/test-reporting

---

.ci/bump-golang.yml

Use default pattern similarly done in other bump automations
Honour the title field in the right location
Otherwise, no PR title is set

updatecli: use default pattern and honour title

---

.github/actions/oblt-cli-create-custom/README.md
.github/actions/oblt-cli-create-custom/action.yml
.github/workflows/test-oblt-cli-create-custom.yml

Action in charge of the oblt-cli create custom
to help with the automation regarding the deploy my kibana

action: oblt-cli-create-custom

---

.github/actions/oblt-cli-create-custom/action.yml

fix: missing comma

---

.github/actions/deploy-my-kibana/action.yml

use `deploykibana` user
to help with the clean up automation

action: use deploykibana

---

.github/actions/deploy-my-kibana/action.yml

Add a more comprehensive title
Help identifying what PR and cluster was used when listing GH issues:
From 
and with this proposal

action: add PR and cluster in the deploy-my-kibana

---

.ci/.docker-images.yml

Fix scripts in docker publish image config.
Closes #ISSUE

Fix docker images publish script

---

.github/workflows/bump-aliases.yml
.github/workflows/bump-elastic-stack.yml
.github/workflows/bump-golang.yml
updatecli/updatecli.d/bump-aliases.yml
updatecli/updatecli.d/bump-elastic-stack.yml
updatecli/updatecli.d/bump-golang.yml

Add what workflow generated the PR
I see some duplicated PRs, so this might help in addition this can help contributors so they know how things are generated.

updatecli: add what CI workflow generated the PR

---

.github/workflows/test-is-pr-approved.yml
.pre-commit-config.yaml

* Correct pre-commit lint configuration after #2201
* Avoid pre-commit false positive errors.

build: correct pre-commit lint

---

.github/workflows/test-deploy-my-kibana.yml

To help with validating changes are good enough

test: github action

---

.github/actions/is-pr-approved/package.json

fix: correct incorrect entrypoint

---

.github/workflows/test-notify-build-status-integration.yml

Removes the `pull_request_target` trigger
Security

Remove pull_request_target trigger

---

.github/actions/deploy-my-kibana/action.yml

feat: support for serverless deployments
Recently we have added the possiblity of customize the images deployed. The PR allow to deploy real serverless deployments.

feat: support for serverless deployments

---

.github/workflows/publish-docker-images.yml

run the GitHub action  once a day
otherwise it ran twice per day

action: run once a day

---

.github/workflows/test-oblt-cli-create-custom.yml

Add flag
To help with testing the new flag in the GH composite action. See https://github.com/elastic/apm-pipeline-library/pull/2320

action: add flag to test the action

---

.github/workflows/licenses.yml
.github/workflows/lint.yml
.github/workflows/opentelemetry.yml
.github/workflows/publish-docker-images.yml

Lint github workflows with https://github.com/rhysd/actionlint/ and with some annotation supports
Get some insights

action: lint github workflows

---

.github/dependabot.yml

Those github actions didn't have this

dependabot: add some other actions

---

.github/actions/oblt-cli-create-serverless/README.md
.github/actions/oblt-cli-create-serverless/action.yml
.github/workflows/test-oblt-cli-create-serverless.yml

GitHub action so we can leverage the existing oblt-cli integration to create serverless clusters
To use the Github issue automation

action: create serverless cluster

---

.github/actions/slack-message/action.yml

It adds an output for the slack-message action to return the thread ts and an input to pass it.
The thread ts allows to reply inside a thread, so using the thread ts we can group messages related in a thread.

feat: return thread ts

---

.github/actions/oblt-cli-create-ccs/action.yml
.github/actions/oblt-cli-create-custom/action.yml
.github/actions/oblt-cli-create-serverless/action.yml

Add EphemeralCluster=true
To help with identifying when clusters are ephemeral
Closes #ISSUE

action: add EphemeralCluster=true

---

.github/workflows/scorecard.yml

As explained in https://github.com/ossf/scorecard-action#installation
Use scorecard to run some analysis for this project
Help to see how well the integration works

ci(action): add scorecard automation

---

.github/actions/buildkite/action.yml

Update buildkite secret
Use the machine account with less restricted access
Closes #ISSUE

secret: update the buildkite api access token

---

.github/actions/deploy-my-kibana/action.yml

Add some logs for the serverless
To help with knowing what's going on and address any future questions regarding where this is coming from.

chore: add details about keep_serverless-qa-oblt

---

.github/actions/buildkite/run.sh

fix empty buildenvs parameter
otherwise consumers need to workaround the issue with:
```bash
buildenvs:
something_something=true
```
Closes https://github.com/elastic/apm-pipeline-library/issues/2344
Given an empty parameter:
```bash
bash -x .github/actions/buildkite/run.sh \
'elastic' \
'apm-agent-java-release' \
'' \
'true' \
'false' \
'***' \
'Triggered automatically with GH actions' \
'HEAD' \
'main'
+ set -euo pipefail
+ MSG='parameter missing.'
+ ORG=elastic
+ PIPELINE=apm-agent-java-release
+ BUILD_VARS=
+ WAIT_FOR=true
+ PRINT_BUILD=false
+ BK_TOKEN='***'
+ MESSAGE='Triggered automatically with GH actions'
+ PIPELINE_VERSION=HEAD
+ PIPELINE_BRANCH=main
++ jq -c -n --arg COMMIT HEAD --arg BRANCH main --arg MESSAGE 'Triggered automatically with GH actions' '{
"commit": $COMMIT, …
```

action(buildkite): fix empty buildenvs parameter

---

.github/workflows/opentelemetry.yml
.github/workflows/test-comment-reaction.yml
.github/workflows/test-deploy-my-kibana.yml
.github/workflows/test-elastic-stack-snapshot-branches.yml
.github/workflows/test-is-member-elastic-org.yml
.github/workflows/test-is-pr-author-member-elastic-org.yml
.github/workflows/test-kibana-docker-image-action.yml
.github/workflows/test-oblt-cli-cluster-credentials.yml
.github/workflows/test-oblt-cli-cluster-name-validation.yml
.github/workflows/test-oblt-cli-create-ccs.yml
.github/workflows/test-oblt-cli-create-custom.yml
.github/workflows/test-oblt-cli-create-serverless.yml
.github/workflows/test-oblt-cli.yml
.github/workflows/test-reporter.yml
.github/workflows/test-workflow-run.yml

Add general read permissions
Fix some security flags

actions: add read permission

---

.github/workflows/test-reporter.yml

See https://github.com/dorny/test-reporter/issues/168\#issuecomment-1537331650
Grant permissions
Otherwise
https://github.com/elastic/apm-pipeline-library/actions/runs/7183686561
Closes #ISSUE

ci: support test-reporting

---

.github/actions/opentelemetry/README.md
.github/workflows/opentelemetry.yml

Use `*` so we can listen to all the workflows
Avoid maintaining the list of workflows.
Closes #ISSUE

action: opentelemetry use wildcards

---

.github/workflows/test-kibana-docker-image-action.yml

Add mention to slack notification
Closes #ISSUE

Add mention to slack notification

---

.github/actions/await-maven-artifact/README.md
.github/actions/docker-login/README.md
.github/actions/github-token/README.md
.github/actions/github-token/action.yml
.github/actions/is-member-elastic-org/README.md
.github/actions/is-member-elastic-org/action.yml
.github/actions/setup-git/README.md
.github/actions/setup-vault-cli/README.md
.github/actions/slack-message/README.md
.github/actions/slack-message/action.yml

Explain how to use the undocumented github actions
Docs
Closes #ISSUE

docs: github actions

---

.github/workflows/lint.yml
.github/workflows/publish-docker-images.yml
.github/workflows/test-oblt-cli-cluster-credentials.yml

Fix some linting issues.
Ignore the false positive  `property "uploaded" is not defined in object type {}`
Fix the linting check
See https://github.com/rhysd/actionlint/issues/18

fix: linting issues

---

.github/actions/buildkite/run.sh

Add retries in curl and avoid failing when retrieving the Buildkite logs but add a warning message
Avoid environmental issues

github-action(buildkite): retry curl if failures and avoid failing if errors with logs

---

.github/actions/buildkite/run.sh

Missed parameter
Otherwise
```
curl: option --retry-delay: expected a proper numerical parameter
curl: try 'curl --help' or 'curl --manual' for more information
Error: Process completed with exit code 2.
```
Closes #ISSUE

fix retry with curl

---

.ci/.docker-images.yml

Add `.` explicitly
Otherwise,
```
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.
```
Closes #ISSUE

docker: use the Dockerfile in the local directory

---

.github/workflows/publish-docker-images.yml

Set env variables
Otherwise
```
ERROR: invalid tag "docker.elastic.co/observability-ci/:": invalid reference format
Error: Process completed with exit code 1.
```
Closes #ISSUE

action: env variables are required for functional-opbeans

---

.ci/.docker-images.yml

Add image that will be created in https://github.com/elastic/observability-robots/pull/2093/

Add opentelemetry-collector-contrib image

---

.ci/.docker-images.yml

Add yaml-language-server to .docker-images.yml
UX
Closes #ISSUE

Add yaml-language-server to .docker-images.yml

---

.github/actions/oblt-cli-create-ccs/README.md
.github/actions/oblt-cli-create-ccs/action.yml
.github/actions/oblt-cli-create-custom/README.md
.github/actions/oblt-cli-create-custom/action.yml
.github/actions/oblt-cli-create-serverless/README.md
.github/actions/oblt-cli-create-serverless/action.yml
.github/actions/oblt-cli/README.md
.github/actions/oblt-cli/action.yml
.github/actions/setup-git/README.md
.github/actions/setup-git/action.yml
.github/actions/setup-oblt-cli/README.md
.github/actions/setup-oblt-cli/action.yml
.github/workflows/actions-test.yml
.github/workflows/test-is-member-elastic-org.yml

Replace `apmmachine` with `obltmachine`
We are now using `obltmachine` for our automation

github-action: use obltmachine

---

.ci/scripts/validate.sh

pre-commit: change the Jenkins instance

---

.github/actions/setup-git/action.yml

To debug what's going on
Closes #ISSUE

action: debug gh auth

---

.github/actions/test-report/action.yml

https://github.com/phoenix-actions/test-reporting/pull/49
Closes #ISSUE

github-action: fix test-reporting

---

.github/dependabot.yml

Reverts elastic/apm-pipeline-library#2594
I'm afraid it's not working

Revert "dependabot: use directories"

---

.github/workflows/bump-aliases.yml
updatecli/updatecli.d/bump-aliases.yml

Support verified commits
Fixes CLA validation:
- https://github.com/elastic/apm-pipeline-library/pull/2617

updatecli: verify commits

---

.github/actions/buildkite/action.yml
.github/actions/docker-login/action.yml
.github/actions/notify-build-status/action.yml
.github/actions/oblt-cli-cluster-credentials/action.yml
.github/actions/oblt-cli-cluster-name-validation/action.yml
.github/actions/oblt-cli-create-ccs/action.yml
.github/actions/oblt-cli-create-custom/action.yml
.github/actions/oblt-cli-create-serverless/action.yml
.github/actions/oblt-cli-destroy-cluster/action.yml
.github/actions/oblt-cli/action.yml
.github/actions/setup-git/action.yml
.github/actions/setup-oblt-cli/action.yml
.github/actions/updatecli/action.yml

Create warning with the alternative
Help consumers our strategy
See

Add deprecation warning

---

.github/workflows/bump-aliases.yml

Trying to figure out whether the `repositories` could be used

github-app: use repositories
