elastic/apm-pipeline-library

src/test/groovy/JunitAndStoreStepTests.groovy
src/test/groovy/RunbldStepTests.groovy
src/test/resources/jobs/runbld.dsl
vars/README.md
vars/junitAndStore.groovy
vars/junitAndStore.txt
vars/runbld.groovy
vars/runbld.txt

Add functions that were created in the beats repo to support the `runbld` reporting that exposes the JUnit reporting in `Elasticsearch`.
Refactor the beats pipeline to keep it simple
Caused by https://github.com/elastic/beats/pull/18037
runbld binary is not available in the local workers
- [build](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-21256/3/)

runbld wrappers

---

local/configs/jenkins.yaml
local/docker-compose.yml

Folder definition in JCasC should run firstly.
Docker compose reports an error:
```
services.jenkins.deploy.resources.reservations.cpus contains an invalid type, it should be a number
```
Otherwise, make -C local <command> won't work
```
$ make -C local stop 
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.jenkins.deploy.resources.reservations.cpus contains an invalid type, it should be a number
make: *** [stop] Error 1
```

Fix docker-compose and JCasC

---

src/test/resources/jobs/beats/beatsWhen.dsl
vars/beatsWhen.groovy

Use [global variables](https://www.jenkins.io/doc/book/pipeline/shared-libraries/#defining-global-variables) to reduce the read/write accesses to the build reasons.
Faster builds approx 10x less i/o accesses
From 149 accesses to the `build.md` file (`99` i/o calls + `50` fileExists calls) in the ITs
To 14 accesses to the `build.md` file (`9` i/o calls + `5` fileExists calls) in the ITs 
Generates the same markdown file

reduce build reasons i/o accesses with global variables

---

src/test/groovy/BeatsWhenStepTests.groovy
vars/beatsWhen.groovy

Support the scenario:
```
As a contributor I want my PR to be skipped in the CI when I configured it with a github label.
```
Talking more precisely for `Beats` this change won't affect the `Lint` stage since it runs always before the `mono-repo` stage dynamic generation that happens when using `beatsWhen` and `beatsStages`
Provide fine granularity to configure the builds based on the user expectations too
Caused by https://github.com/elastic/beats/pull/20104

Support skip-ci-build label for beatsWhen

---

src/test/groovy/BeatsWhenStepTests.groovy
vars/beatsWhen.groovy

Fixes a bug
PRs in beats-ci are building in all the platforms
```
BRANCH_NAME
For a multibranch project, this will be set to the name of the branch being built, for example in case you wish to deploy to production from master but not from feature branches; if corresponding to some kind of change request, the name is generally arbitrary (refer to CHANGE_ID and CHANGE_TARGET).
```

Fix beatsWhen on PR basis

---

resources/scripts/generate-build-data.sh
src/test/groovy/GenerateBuildDataIntegrationTests.groovy

BO returns 500 in some cases let's avoid fetching an html page instead a json one, let's use `--fail` even though 404 might happen but it should behave as no file to be processed. 
`--fail` does not require to tweak the ITs, while the other approach required to use wireshark to fetch `HEAD` requests.
Avoid fetching wrong data.
```
curl -LI https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/beats/7.x/runs/382/blueTestSummary/ -o /dev/null -w '%{http_code}\n' -s
500
```
```
$ curl https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/beats/7.x/runs/382/blueTestSummary/ --fail -o file.txt1
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0 …
```

Fix 500 http errors in BO

---

resources/github-comment-markdown.template
resources/groovy-html-custom.template

PRComment reports the steps that failed, some of those steps are not important but some wrappers.
JUnit reporting failed if tests were not executed for instance.
GH notify fails if the closure failed, aka another step.  
For instance

Exclude GH Notifies and JUnit from reported failed steps

---

local/docker-compose.yml

Avoid slowness in the docker instance
It is really, really really slow. It seems previous versions of docker didn't have that particular impact, most likely those configuration details were not used for some reason.

[local] remove resources limitations in docker

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/IsBranchStepTests.groovy
src/test/groovy/IsTagStepTests.groovy
vars/README.md
vars/beatsWhen.groovy
vars/isBranch.groovy
vars/isBranch.txt
vars/isTag.groovy
vars/isTag.txt

Provide steps to query if the MBP was running for a branch or a tag.
Avoid to access to env variables to know what kind of build.
Caused by https://github.com/elastic/apm-agent-php/pull/204

isBranch and isTag helpers

---

resources/slack-markdown.template

List only the number of failures and a link where to look for further details.
Cosmetic changes in the format
Avoid massive slack messages
for instance with a few test failures
and a few steps failures:
See the raw message as an example of the outcome from the ITs
```
*Build*: <http://jenkins.example.com:8080/blue/organizations/jenkins/folder%2Fmbp/detail/master/1/pipeline|49> for branch `develop` got the status `ABORTED`
*Changes*: 8a2fd55 has been merged (see <https://github.com/elastic/apm-server/commit/8a2fd55f40dbcb279911e3f2237312baf1508019|fix 7.x changelog links (#2207)>) (PR owner `someone`)
*Tests*: 121 passed of 121 with `0` failure/s (Click <http://jenkins.example.com:8080/blue/organizations/jenkins/folder%2Fmbp/detail/master/1/tests|here> for further details)
*Steps …
```

[cosmetic] less verbose test and step failures in the slack message

---

resources/github-comment-markdown.template
resources/scripts/generate-build-data.sh

Beats-CI got some issues when the test-summary BO entrypoint is returning 500. 
Even the tests that are failing are reported the overall summary of tests executions is not shown correctly.

Resilience when test-summary is not accessible.

---

resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy

Visualise when there are test failures and step failures without the need to expand the report
Notify easily when things are going bad!

highlight step and test failures in GH comments

---

resources/slack-markdown.template

- Highlight test errors
- Explicitly add the job name
When notifying in a common channel then the build refererence to the job was not included, therefore it was not easy to debug what's the pipeline unless clicking on the links.
See. 
```
*Build*: `folder/mbp/master` <http://jenkins.example.com:8080/blue/organizations/jenkins/folder%2Fmbp/detail/master/1/pipeline|#49> for branch `develop` got the status `ABORTED`
*Changes*: <https://github.com/elastic/apm-server/commit/8a2fd55f40dbcb279911e3f2237312baf1508019|fix 7.x changelog links (#2207)> (by `someone`)
*Tests*: `0` test/s failed out of 121 (click <http://jenkins.example.com:8080/blue/organizations/jenkins/folder%2Fmbp/detail/master/1/tests|here> for further details)
*Steps failures*: `3` (click …
```

cosmetic change slack comment

---

vars/githubPrCheckApproved.groovy

Grant access to the CI for PRs that are generated by the `bot` dependabot.
To support dependabot for security bumps
Notifies https://github.com/elastic/apm-pipeline-library/pull/766

Grant running access for the dependabot user

---

vars/githubPrCheckApproved.groovy

Use `dependabot[bot]`
Otherwise the user does not match
See https://github.com/elastic/apm-pipeline-library/pull/769

Enable dependabot[bot]

---

resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy
src/test/resources/steps-errors-with-multiple.json

When there are more than 10 tests failures or steps failures then show only the first 10 of each as a GitHub comment and add a quote comment regarding this filter
Avoid creating GitHub comments with thousands of lines.
For instance, 7.x branch got a few hundred of test failures:
and PRs got massive GitHub comments that were hard to debug, see https://github.com/elastic/beats/pull/21637#issuecomment-705027324
UTs output

[notification] show only up to 10 tests/steps failures

---

vars/notifyBuildResult.groovy

Use linux workers rather than the generic immutable label that might also include the windows workers.
Sometimes the post build step runs in windows and don't notify the status.
See [this](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-21857/1/pipeline)
- [linux](https://apm-ci.elastic.co/label/linux/) for the apm-ci
- [linux](https://beats-ci.elastic.co/label/linux/) for the beats-ci
Although it seems `gobld doesn't support master||immutable label ` so not sure the reason why it worked in this case... so this PR fixes our issue now

Avoid using windows immutable workers

---

src/test/groovy/NotifyBuildResultStepTests.groovy
vars/notifyBuildResult.groovy

Builds that got aborted (normally a new build with new changes are in place) then no flaky test analyser should happen since there might not be tests to be analysed.
Avoid any kind of misleading 
For instance 
Closes #ISSUE

[flaky] enable if no aborted

---

src/test/groovy/JunitAndStoreStepTests.groovy
vars/junitAndStore.groovy

Fix warning when using args that are not defined
```
[2020-10-13T16:50:43.188Z] [Pipeline] junit
[2020-10-13T16:50:43.188Z] WARNING: Unknown parameter(s) found for class type 'hudson.tasks.junit.pipeline.JUnitResultsStep': id,stashedTestReports
[2020-10-13T16:50:43.192Z] Recording test results
[2020-10-13T16:50:43.618Z] None of the test reports contained any result
```
Let's see if that could be the reason with the BO issues and corrupted data.
Relates to https://github.com/elastic/beats/pull/21888

Avoid warning in JUnit when using args that are not defined

---

src/test/groovy/GithubApiCallStepTests.groovy
vars/README.md
vars/githubApiCall.groovy
vars/githubApiCall.txt
vars/githubPrLatestComment.groovy

Add noCache for API calls when using the GitHub PR comment
This will allow us to generate multiple GH comments 
Otherwise
And the call happens once and the archive twice reusing the same file
```bash
$ curl -s https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-21853/3/artifact/flaky.id/\*view\*/                                                                                                
709473180%                                                                                                                                                                                                                                                                                         $ curl -s https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-21853/3/artifact/comment.id/\*view\*/ …
```

Support API calls without caching

---

resources/flaky-github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy

Add more comment categories for the flaky test analysis GitHub comments, such as: when there are known test failures and known flaky failures, versus non executed tests builds and builds without any test failures
To ensure the message got enough context about what it happened
- @elastic/observablt-robots , what do you think if the icon 🐛 💚 and ❕ are moved to the main header? For instance
vs
Closes #ISSUE
- No executed tests
- No failed tests
- With failed tests

[flaky] categorise comments in failed or not failed tests

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/GhStepTests.groovy
vars/gh.groovy

Install `gh` if it's not installed in the CI worker.
Unblock the flaky reporting since the ansible role installation has not been applied yet.

Install gh if not available

---

resources/slack-markdown.template
src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
vars/notifyBuildResult.groovy
vars/notifyBuildResult.txt

It adds a `slackHeader` parameter to the `notifyBuildResult`, creating a unit test verifying that the template engine renders the header if it's passed to the script.
It will allow client code to add a custom header to a Slack message
Closes #783
Could an attacker inject a string that will be rendered to display secrets, like environment? I'd like to hear your voice before merging it

feat: support client code to prepend a custom header in slack message

---

test-infra/apm-ci/test_windows.py
test-infra/beats-ci/test_beats_windows.py

Avoid running gh validation on Windows since we don't need it for the `notifyBuildResult`
Initially though to support it with test-infra way of doing, but windows is a kind of special though 
```
[2020-10-22T10:55:00.024Z]     def test_gh_installed(host):
[2020-10-22T10:55:00.024Z] >     if host.system_info.arch == "x86_64" :
[2020-10-22T10:55:00.024Z] E     AttributeError: 'SystemInfo' object has no attribute 'arch'
```
`environment` for windows
```
[2020-10-22T12:19:32.356Z]     def __call__(self):
[2020-10-22T12:19:32.356Z]         ret_val = dict(
[2020-10-22T12:19:32.356Z] >           i.split('=', 1) for i in self.check_output('env -0').split(
[2020-10-22T12:19:32.356Z]                 '\x00') if i
[2020-10-22T12:19:32.356Z]         )
[2020-10-22T12:19:32.356Z] E       AssertionError: …
```

[test-infra] gh not validated on Windows

---

resources/flaky-github-comment-markdown.template
src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
src/test/resources/flake-tests-errors-without-match.json

Collapse further reporting.
Report `genuine` test failures, aka those failures that were not reported as flaky
Help to categorise
For instance, the below comment when no flaky tests but test failures
```
:grey_exclamation: There are test failures but not known flaky tests.
<details><summary>Expand to view the summary</summary>
<p>
| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 1  |
| Passed       | 120  |
| Skipped      | 0 |
| Total        | 121   |
:broken_heart: There are test failures but not known flaky tests, most likely a genuine test failure.
* **Name**: `Test / windows-3.6-none / test_send - notfound`
</p>
</details}
```

[flaky] report genuine test failures

---

resources/flaky-github-comment-markdown.template

Fixes required markdown space to format the message correctly
Otherwise

[flaky] fix markdown formatting

---

vars/githubPrComment.groovy
vars/githubTraditionalPrComment.groovy

Since today I suddenly see the GitHub comments for the elastic/beats.git to miss one of the comments for some reason :_(
Not sure if that's related to the recent beats-ci reboot or upgrade of the plugins
The `pr` object failed when creating the comment and therefore it fall back to the traditional GH comment approach using the API calls which doesn't use the `noCache` flag 
```
18:06:21  [DEBUG] githubPrComment: pullRequest.comment failed with message: java.io.UncheckedIOException: org.eclipse.egit.github.core.client.RequestException: Resource not accessible by integration (403)
```
To restart the GH PR comments as used to be
https://github.com/elastic/apm-pipeline-library/pull/776 fixed one of the use cases and it worked until sometime today :/ . So my guess is something has changed with …

Fix cache for GH comments

---

src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
vars/notifyBuildResult.groovy
vars/notifyBuildResult.txt

It adds support for receiving a comma-separated list of slack channels in the `channel` attribute of the `notifyBuildResult` step.
It also increases the code coverage, adding tests checking for the existence of certain attributes of the notifyToSlack method.
It will allow client pipelines to send messages to multiple channels if desired.
We avoided using `log` in tests, but checking that `slackSend` was invoked. This is important in the sense that we discovered an internal conflict with the `log` step, which seems a reserved key in the unit test library used for mocking Jenkins.
Closes #793

feat: support passing a comma-separated list of slack channels

---

resources/github-comment-markdown.template

- BO links don't show all the logs for a given step if the logs are massive, for such it's required to use `/?start=0`
- On the other hand, I took the chance to aggregate the duration, logs within the name section.
- Add `errorStackTrace` for the failed tests.
- Remove `startTime` for the failed steps.
- Remove empty lines when fields are empty. 
People should not use the CI UI by default, but the BO links.
@SergeyKleyman reported this issue
- Using the UI tests
| PROPOSAL | CURRENT |
|------------|------------|
|![image](https://user-images.githubusercontent.com/2871786/97857729-17b1e880-1cf6-11eb-9ac0-b1051bc9e238.png)|![image](https://user-images.githubusercontent.com/2871786/97858146-a0c91f80-1cf6-11eb-94e2-778c5b091c64.png)

GH comment with links to the the entire logs and cosmetic changes

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/BeatsWhenStepTests.groovy
src/test/groovy/GetGitMatchingGroupStepTests.groovy
src/test/groovy/IsGitRegionMatchStepTests.groovy
vars/README.md
vars/beatsWhen.groovy
vars/getGitMatchingGroup.groovy
vars/getGitMatchingGroup.txt
vars/isGitRegionMatch.groovy
vars/isGitRegionMatch.txt

Fix a corner case with a branch running for the very first time since the env variables are unset
Otherwise it won't work
Fixes
[build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2F6.8/detail/6.8/2/pipeline/147#step-70-log-1)
Relates https://github.com/elastic/apm-pipeline-library/pull/298

Fix git diff for first builds in branches

---

.github/dependabot.yml

Enable dependabot on a weekly basis to monitor maven and docker dependencies
Dependabot is now an official service from GitHub.
See https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-dependabot-version-updates

[dependabot] Enable for maven and docker images

---

.ci/buildDockerImages.groovy

Adds the ability to build and push a Docker image for the [Bandstand project](https://github.com/elastic/observability-dev/tree/master/apps/automation/bandstand) which orchestrates load tests for APM agents.
Part of the deployment which will live in Elastic Apps.
Refs: https://github.com/elastic/observability-robots/issues/255

Add docker build for bandstand orch

---

.github/dependabot.yml

Disable docker bump
As long as we don't run tests for the docker images we cannot warranty this is a valid use case

[dependabot] disable docker images

---

resources/flaky-github-comment-markdown.template
resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy

Collapse the error details and stacktrace.
Remove the age/took section for the failed tests, since it seems we don't need it.
- Test errors comment
|used-to-be|proposal|
|-----------|---------|
|![image](https://user-images.githubusercontent.com/2871786/98549354-92e54280-2292-11eb-93ef-3e7158609463.png)|![image](https://user-images.githubusercontent.com/2871786/98549312-8365f980-2292-11eb-95b8-8b6eb87e8a7a.png)|
- Flaky comment
|used-to-be|proposal|
|-----------|---------|
|![image](https://user-images.githubusercontent.com/2871786/98549629-f96a6080-2292-11eb-87b4-7c7bda2ef402.png)|![image](https://user-images.githubusercontent.com/2871786/98549441-b3150180-2292-11eb-8a13-ffd255910d66.png)|

[cosmetic] simplify test errors report

---

resources/github-comment-markdown.template

Use html formatting to solve some cosmetic issues with the sublists in markdown format, since the last element of the list somehow is closer to the next element in the list. 
Using the output from `mvn clean test -Dtest=NotificationManagerStepTests#test_notify_pr_with_unstable_and_multiple_steps_failures -Pdebug`
|proposal|used to be|
|--------|-----------|
|![image](https://user-images.githubusercontent.com/2871786/98566603-de095080-22a6-11eb-8308-acdd0d631536.png)|![image](https://user-images.githubusercontent.com/2871786/98566801-1e68ce80-22a7-11eb-83d2-845a9717464c.png)|
The reason is to solve some cosmetic weirdness such as the below screenshot, that got long commands and description details

[cosmetic] simplify UI for steps

---

resources/scripts/generate-build-data.sh

Remove the right field
Otherwise
```bash
16:35:14  + jq 'map(del(._class))' job-info.json
16:35:14  jq: error (at job-info.json:0): Cannot index string with string "_class"
```
```bash
$ curl -s 'https://apm-ci.elastic.co/job/apm-shared/job/apm-pipeline-library-mbp/job/master/1194/artifact/job-info.json/\*view\*/' | jq 'del(.parameters)' | jq 'del(._links)' | jq 'del(._class)' | jq 'del(.latestRun)' | jq 'del(.permissions)'
{
"actions": [],
"disabled": false,
"displayName": "master",
"estimatedDurationInMillis": 407498,
"fullDisplayName": "apm-shared/APM%20Pipeline%20Library/master",
"fullName": "apm-shared/apm-pipeline-library-mbp/master",
"name": "master",
"organization": "jenkins",
"weatherScore": 100,
"branch": {
"isPrimary": true,
"issues": [],
"url": …
```

Remove field rather than maps

---

resources/scripts/generate-build-data.sh
src/test/groovy/GenerateBuildDataIntegrationTests.groovy
src/test/resources/env-info.json

Populate some CI env variables and remove some metadata
This will help us to simplify our queries to the ES
For instance,
The below query could be simplified:
```
"query": {
"bool": {
"must": [
{
"term": {
"build.branch.isPrimary": "true"
}
},
{
"match_phrase": {
"job.branch.url": "https://github.com/elastic/beats"
}
},
{
"match_phrase": {
"build.artifactsZipFile": "/job/Beats/job/beats/"
}
},
}
]
}
}
```
```
"query": {
"bool": {
"must": [
{
"term": {
"build.branch.isPrimary": "true"
}
},
{
"term": {
"env.REPO_NAME": "beats"
}
}
}
]
}
}
```

Add env variable to easily search in the future

---

src/test/groovy/GithubCreatePullRequestStepTests.groovy
vars/githubCreatePullRequest.groovy

Fail if there are single quotes in the title or description
Fail with more details
Caused by https://github.com/elastic/apm-agent-php/pull/289
To follow up with a fix to support more cases, probably using the -F
```
-F, --file FILE
Read the pull request title and description from FILE. Pass "-" to read from standard input instead. See --message for the formatting rules.
```
ITs

Error if single quotes when using githubCreatePullRequest

---

local/Dockerfile

Fix the version to the latest stable docker image that matches the existing production jenkins instnace
Latest cannot be used as long as the producers don't run some validations.
```
$ docker run --rm -ti -p 8080:8080 docker.elastic.co/infra/jenkins:latest
...
2020-11-11 09:33:07.640+0000 [id=31]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Pipeline: Basic Steps v2.23 (workflow-basic-steps)
java.io.IOException: Failed to load: Pipeline: Basic Steps (2.23)
- Jenkins (2.263) or higher required
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at …
```

[local] docker instance with fixed version

---

resources/scripts/generate-build-data.sh
src/test/groovy/GenerateBuildDataIntegrationTests.groovy

Remove some unused metadata such as:
- duplicated entries in build/jobs for the changeset branch and pull requests.
- remove _class and _links
- remove some metadata from the changeSet
- remove some metadata from the artifacts
- Append JENKINS_URL to the artifacts
Reduce the amount of unnecessary data

Remove duplicated metadata

---

vars/README.md
vars/sendDataToElasticsearch.groovy
vars/sendDataToElasticsearch.txt

Create a new index for populating all the data from the CI
Normalising the data might help us easily to apply the same format.
I created a new index and alias, so we will need only to use the alias in the shared library
```
PUT jenkins-metadata
POST /_aliases
{
"actions" : [
{ "add" : { "index" : "jenkins-metadata", "alias" : "ci-builds" } }
]
}
```

New ES index

---

resources/slack-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy

Skip steps failures if no steps failures
It does not add any value
Closes https://github.com/elastic/apm-pipeline-library/issues/790

[notification] skip steps comment in slack if none

---

src/test/groovy/NotifyBuildResultStepTests.groovy
vars/notifyBuildResult.groovy

As a consequence of adding a new feature then notifications were not double checked and some notifications were sent when they should not.
Thanks @brianseeders

Skip notifications if no notifications are in the list to send

---

src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
src/test/resources/flake-empty-results.json

- Skip flaky analysis if no test failures
- Fix NPE
```
17:46:09  ERROR: There were some failures when generating flakey test results
17:46:09  java.lang.NullPointerException: Cannot get property 'hits' on null object
17:46:09  	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
17:46:09  	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
17:46:09  	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:257)
17:46:09  	at org.codehaus.groovy.runtime.dgm$242.doMethodInvoke(Unknown Source)
17:46:09  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
17:46:09  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
17:46:09  	at …
```

Flaky causes NPE

---

vars/googleStorageUpload.groovy
vars/googleStorageUpload.txt

Try to reduce the number of concurrency calls for the same step that causes some issues
See if we can mitigate the environmental issue as long as no new release of the plugins is released
I'm not 100% sure whether this particular workaround will reduce the number of times we face that issue, but it should be pretty much harmless in the worst case scenario, but adding certain sleep time.
Caused by https://github.com/jenkinsci/google-storage-plugin/issues/61
Manually tried in my local instance:

Add certain latency to access to the google storage

---

vars/lookForGitHubIssues.groovy

Add default flaky tests if no issues to query, so far it was only enabled if something bad happened with the step, but what if no issues are retrieved without any failures?
Add more coverage to report flakiness even if no issues have been fetched.

If no GH Issues then use flaky test details

---

.ci/buildDockerImages.groovy

It simply reads the `.node-version` file in the RUM agent workspace, instead of iterating through multiple versions of Node (which is not done at this moment)
There is only one NodeJS version, defined in one single file
>YAGNI
- Depends on https://github.com/elastic/apm-agent-rum-js/pull/935

chore: simplify RUM JS image

---

resources/ci-builds-mapping.json
resources/scripts/generate-build-data.sh
src/test/groovy/GenerateBuildDataIntegrationTests.groovy

- Fix the bulk format (since doc is for updating and caused a top level field)
- Remove `actions` since they are empty anyway
- Flatten the `cause` and pick up the first entry, I don't see toomany cases where the cause will have more than one entry.
Fixes the existing index.

[index] bulk format and remove certain unused fields

---

resources/ci-tests-mapping.json
resources/scripts/generate-build-data.sh
src/test/groovy/GenerateBuildDataIntegrationTests.groovy
src/test/groovy/NotifyBuildResultStepTests.groovy
vars/notifyBuildResult.groovy

Split indexes in two:
* One index will contain as many docs as tests are executed per build.
* Other index will contain one doc per build.
It will be easy to create simple dashboards for overall build status versus specific ones regarding test failures.

[index] create a new index

---

resources/ci-tests-mapping.json
resources/scripts/generate-build-data.sh

Reduce the ndjson files for the bulk from 100mbs in Beats to a few kbs in the new indexes, so we won't loose any data yet since we still have the deprecated index with a multinested doc fields.
Need to sacrifice those details otherwise the 100mbs data causes issues with the `_bulk` entrypoint.

[index] populate only test failures

---

.ci/schedule-weekly.groovy

Caused by https://github.com/elastic/beats/pull/22862
Move to the new ES index

[CI] runbld is now deprecated

---

resources/github-comment-markdown.template
src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/NotificationManagerStepTests.groovy
src/test/resources/steps-errors-with-multiple.json

Reduce the number of steps failures that are related to the `Error signal` to just one.
Use header4 for the test and step failures.
`Error signal` does not provide any details but a generic message. Therefore it might mislead the end user in case the are more than 10 failed steps since it's filtered up to 10 steps to be shown.
For instance, the below screenshot shows a bit more of how it's the current issue with too many error signal steps

[report] report one error signal if multiple

---

.ci/schedule-weekly.groovy
.pre-commit-config.yaml
resources/flaky-watcher.json

Split report per active release branch:
* master
* 7.x
* 7-release -> `7.10` at the time of writing this.
It was requested by the beats team
I have not found the way to configure a watcher when using the sendEsData step easily, so it requires to override the input field. So I've decided to leave that responsaiblity to the watcher and therefore when there is a minor upgrade (from 7.10 to 7.11) we will need to change the watcher report-beats-top-failing-tests-weekly-7-release to filter by `"env.BRANCH_NAME": "7.11"`

[beats] flaky weekly email per branch

---

resources/scripts/install-tools.bat
src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithGoEnvStepTests.groovy
src/test/groovy/WithGoEnvUnixStepTests.groovy
src/test/groovy/WithGoEnvWindowsStepTests.groovy
vars/README.md
vars/withGoEnv.groovy
vars/withGoEnvUnix.groovy
vars/withGoEnvUnix.txt
vars/withGoEnvWindows.groovy
vars/withGoEnvWindows.txt

Support Windows for `withGoEnv`
Helps to refactor the support for Go projects in Windows.
Caused by https://github.com/elastic/go-windows/pull/14/files and https://github.com/elastic/go-concert/pull/36

Support Windows for withGoEnv

---

.mvn/wrapper/maven-wrapper.properties

Use maven 4 alpha from [here](https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven/job/master/70/artifact/org/apache/maven/apache-maven/4.0.0-alpha-1-SNAPSHOT/) that was found with the brew tap [module](https://github.com/mthmulders/homebrew-maven-snapshot/blob/master/Formula/maven-snapshot.rb#L4)
Test if it works as expected :)
Closes #ISSUE

Use maven 4 alpha

---

.gitignore
vars/dummy.groovy

Rename the argument `params` to `args`in the dummy step.
This step is the template for new steps, the use of `args` as name for the arguments is better and avoid conflicts/confusion with the global `params` variable.
Closes #ISSUE

chore: rename argument

---

.ci/packer_cache.sh
src/test/groovy/FilebeatStepTests.groovy
src/test/resources/filebeatTest/filebeat_container_config.json
vars/README.md
vars/filebeat.groovy
vars/filebeat.txt

* Adds Filebeat to the packer cache
* Adds the `filebeat` pipeline step to run Filebeat easily.
This new `filebeat` pipeline step allows grabbing the Docker container logs with a couple of steps.
```
pipeline {
agent { label "ubuntu" }
stages {
stage('My Docker tests') {
steps {
filebeat(workdir: "${env.WORKSPACE}")
sh('docker run busybox  ls')
}
post {
cleanup{
script {
filebeat.stop(workdir: "${env.WORKSPACE}")
}
}
}
}
}
}
```
```
pipeline {
agent { label "ubuntu" }
stages {
stage('My Docker tests') {
steps {
filebeat(workdir: "${env.WORKSPACE}"){
sh('docker run busybox  ls')
}
}
}
}
}
```

feat: filebeat pipeline step

---

src/test/groovy/BeatsWhenStepTests.groovy
vars/beatsWhen.groovy

Support a new when condition to full match the changeset
Otherwise, there is a chance that some PRs won't trigger mandatory fields since it uses a partial match at the moment.
- First commit (https://github.com/elastic/apm-pipeline-library/pull/890/commits/e1ba36d22b1b1dc09b5a0b795becf2f7f9b11db4) was a refactor, so almost all the logic for the `whenChangeset` was moved to a new function `changeset`.
- Second commit (https://github.com/elastic/apm-pipeline-library/pull/890/commits/578f4f80b197a9d6a9b21098ecb3c3e5f2d9d461), added the new when condition.

Support not_changeset_full_match for beats

---

.mvn/wrapper/maven-wrapper.properties

Use link to the latest successfull build instead a specific build
Avoid using old deleted builds.
It's not ideal but as long as mvn 4 is not released in a different manner, we cannot do much unless we archive those artifacts somewhere.
This will not add reproducibility to our builds since it'll use the latest stable artifacts, but I think once we are on mvn4 any incremental changes should be backward compatibly, if not, at least we can provide value feedback to the maven project.
I'll ask the maven project if they have another suggestion to use their latest mvn 4 artifacts

[CI][mvn4] Use lastSuccessfulBuild

---

src/test/groovy/FilebeatStepTests.groovy
vars/filebeat.groovy

* add a docker option to wait for `docker exec`
* ignore command failures and print the exit code

fix: wait for docker exec to finish

---

src/test/groovy/FilebeatStepTests.groovy
vars/filebeat.groovy

* Write/Read real files for the tests
* Use the WS in the PATH to write/read the filebeat config
Closes https://github.com/elastic/apm-pipeline-library/issues/897

fix: use WS always

---

src/test/groovy/FilebeatStepTests.groovy
vars/filebeat.groovy
vars/filebeat.txt

Use the current dir by default for all generated files.
ArchiveArtifacts uses relative routes to the current folder, so grab files outside this scope make the step complex without need, because of that we change to use the current folder as workdir for the generated files.
Closes https://github.com/elastic/apm-pipeline-library/issues/897

fix: use current folder instead of the workspace

---

src/test/groovy/GoDefaultVersionStepTests.groovy
vars/goDefaultVersion.groovy
vars/goDefaultVersion.txt

Add a new step to get the default Go version we use.
We have duplicate logic across projects to do exactly the same, also we have harcoded values we have to update manually across repos, this resolves both issues.
caused by https://github.com/elastic/ecs-logging-go-zap/pull/28

feat: goDefaultVersion step

---

src/test/groovy/StackVersionsStepTests.groovy
vars/stackVersions.groovy
vars/stackVersions.txt

It adds a new step stackVersions.
This new step returns an array of the version numbers we use for testing, also can give the version using tag names (edge, dev, release, or snapshot)
related to https://github.com/elastic/observability-robots/issues/309

feat: add stackVersions step

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/GoTestJUnitStepTests.groovy
src/test/groovy/SendBenchmarksStepTests.groovy
src/test/groovy/WithGoEnvUnixStepTests.groovy
src/test/groovy/WithGoEnvWindowsStepTests.groovy
vars/README.md
vars/goDefaultVersion.groovy
vars/goTestJUnit.groovy
vars/sendBenchmarks.groovy
vars/withGoEnv.txt
vars/withGoEnvUnix.groovy
vars/withGoEnvUnix.txt
vars/withGoEnvWindows.groovy
vars/withGoEnvWindows.txt

It changes some steps to use the new goDefaultVersion step.
This unifies the Go version used across steps and avoid duplications.
related to https://github.com/elastic/apm-pipeline-library/pull/901

feat: use goDefaultVersion

---

.pre-commit-hooks.yaml

Use https://github.com/elastic/e2e-testing/pull/497 
Binary files should not be evaluated for some linting
Closes #ISSUE

[pre-commit] exclude gif/png files

---

resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy
src/test/groovy/WithGithubNotifyStepTests.groovy
src/test/resources/steps-errors-with-also-github-environmental-issue.json
src/test/resources/steps-errors-with-github-environmental-issue.json
vars/withGithubNotify.groovy

* Add resilience when GitHub is not accessible.
* Add failed GitHub step as a PR comment when no other failed steps, to help with the build analysis.
Avoid environmental build issues when third-party systems are not accessible.
[logs](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats%2FPR-23560/detail/PR-23560/1/pipeline/#step-6672-log-1)
Created a GitHub comment in the PR without anything to highlight:
https://github.com/elastic/beats/pull/23560#issuecomment-762774196
The reason there is no failed step with those details is caused by the filtering of the githubNotify https://github.com/elastic/apm-pipeline-library/issues/747

Add resilience when GitHub got some glitches

---

.ci/scripts/markdown-lint.sh

It forces the usage of the `--progress` parameter, instead of consuming those passed by the caller of the hook.
See #918
Closes #918

fix: hardcode markdown-lint parameters

---

.ci/Jenkinsfile
src/test/groovy/NotifyBuildResultStepTests.groovy
src/test/groovy/co/elastic/mock/RunWrapperMock.groovy
vars/notifyBuildResult.groovy

Skip any GitHub Pull Request comment if an old build is still running when its next adjacent build has already finished, if any
Avoid overriding the comment with obsoleted build data when two adjacent builds were triggered, and the old one is still running.
Depends on https://github.com/elastic/apm-pipeline-library/pull/916
Closes https://github.com/elastic/apm-pipeline-library/issues/906

Skip GitHub comment for old build when the next adjacent build has already finished

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/GithubAppTokenStepTests.groovy
vars/githubAppToken.groovy

Mask the GitHub App token when using the debug traces
Avoid any leaking

Mask the GitHub app generated token

---

.ci/Jenkinsfile
src/test/groovy/NotifyBuildResultStepTests.groovy
vars/notifyBuildResult.groovy

Enable GitHub check with the build digested status. 
Transition to GitHub checks.
- See https://github.com/elastic/apm-pipeline-library/pull/921/checks?check_run_id=1764002793
I refactored a bit with https://github.com/elastic/apm-pipeline-library/pull/921/commits/16617f4e9eb6d6ec3e173da3feb8f0a5f952ebed to reuse the login behind whether to notify when the new build did already finished.
Then, the important changes are:
- https://github.com/elastic/apm-pipeline-library/pull/921/commits/147f527f106c0ec401040a21cc1097f5c36c7f43
- https://github.com/elastic/apm-pipeline-library/pull/921/commits/7a7cd6f30a91fee490cbf75410cc63ef26a0ac1e
- https://github.com/elastic/apm-pipeline-library/pull/921/commits/3309d460c5f9c42333e8341c0506ae445c23f8db

Create GitHub Check with the digested Build data

---

vars/filebeat.groovy

It retries the wait command 5 times.
Launch the Docker container in detached mode can cause the container is not available to run `curl` when the wait step is executed this causes an error.
```
[2021-01-25T12:05:00.215Z] + docker exec 90dd33fd22cc9e6c6709dfd18afd82a3b851f87952bcc057b47c136c05062ce3 curl -sSfI --retry 10 --retry-delay 5 --max-time 5 http://localhost:5066/stats?pretty
[2021-01-25T12:05:00.480Z] curl: (7) Failed to connect to ::1: Cannot assign requested address
```

fix: retry wait for filebeat

---

src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
vars/notifyBuildResult.groovy

Call the `generateBuildReport` once, for such the `notifyPR` step support:
* a new argument called `comment` then it does not need to generate the build report again.
* if the comment is empty then it will generate the data, for such it calls the `generateBuildReport` step, to avoid duplicated code.
The `notifyBuildResult` now calls the `notifyPR` step with the `comment` argument.
Remove duplicated code.

Refactor notifyPR and generateBuildReport

---

src/test/groovy/WithGoEnvUnixStepTests.groovy
vars/README.md
vars/withGoEnvUnix.groovy
vars/withGoEnvUnix.txt

Use `GOARCH` environment variable when installing the go packages:
* If `GOARCH` is set then use it (that's the current behaviour anyway)
* Otherwise it will calculate the ARCH for that particular node. So far `arm64` or `amd64`, since we do not use any other architecture for `Unix`
This will help the consumers of the `withGoEnv` to be ARCH agnostic.
Blockes https://github.com/elastic/beats/pull/PR-23592

Use GOARCH to install the package for that particular architecture

---

src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
vars/notifyBuildResult.groovy

Validate not null objects and generateBuildReport  returns now the message
Regression when merging #926
Closes #https://github.com/elastic/apm-pipeline-library/issues/930

Return the build digested output

---

src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
vars/README.md
vars/notifyBuildResult.groovy
vars/notifyBuildResult.txt

Allow to disable the GitHub issue creation when there is a flaky match.
- `notifyBuildResult` now got a new parameter called `flakyDisableGHIssueCreation` (Default: false) <-- this is consumed by the Jenkinsfiles.
- `analyzeFlakey` now got a new parameter called `disableGHIssueCreation` (Default: false) <-- this not consumed outside of the library, so `notifyBuildResult` calls this step.
Allow the teams to manage their flakiness analysis process.
If you review this PR, there are two commits:
- https://github.com/elastic/apm-pipeline-library/commit/586bdb3217cbbd4b6531ac1f6bd5cd097a20c314 is the refactor
- https://github.com/elastic/apm-pipeline-library/commit/6c20a472ec8f126ed10d21272961a3e33223f677 is the actual change for the new argument.

Support disable GitHub issue creation for flaky tests

---

vars/githubTraditionalPrComment.groovy
vars/notifyBuildResult.groovy

JSON transformation is now delegated to the githubApiCall.
Simplify consumers usage with string only format.
Regression from https://github.com/elastic/apm-pipeline-library/commit/41ff35c343c20069e44d68b6ee790d1697ae2f4b#diff-51b46d8d285372d54df7b418dd6a4ad57a3533e2c0eededca50fa48fbe8c6a84R56-R57 
See https://github.com/elastic/beats/pull/23715#issuecomment-769687240

Consumers of githubApiCall should not transform JSON

---

.ci/jobs/ecs-logging-update-specs-mbp.yml

Create MBP fro https://github.com/elastic/ecs-logging/pull/47
Automate the PR creation
Closes #ISSUE

[CI] support sending a PR to each ecs agent when spec change

---

src/test/groovy/GitCmdStepTests.groovy
vars/gitCmd.groovy

`gitCmd` uses some credentials and if `store` then let's mask any sensitive credentials
Security

mask credentials when using gitCmd

---

resources/scripts/generate-build-data.sh
src/test/groovy/PreCommitToJunitStepTests.groovy
vars/preCommitToJunit.groovy

I've seen some corner cases when testing this pipeline locally since my docker jenkins instance didn't have any `wget` so `jq` could not be installed and therefore no way to populate the test-summary with empty value since the `test-info` file was created with empty values.
when `wget` and `jq` are not installed then something bad might happen, so let's ensure we handle those use cases too.

corner cases if wget is not available and null values

---

.ci/buildDockerImages.groovy

Adds the [new integrations test reporter](https://github.com/elastic/observability-dev/tree/master/apps/automation/integrations/reporter) to the pipeline which builds Obs Docker images.
Needed for doing [the deployment of the integrations test reporter service](https://github.com/elastic/observability-dev/blob/master/apps/automation/integrations/reporter/integration-test-report-deploy.yml).
https://github.com/elastic/observability-robots/issues/251

Add Docker build for integrations test reporter

---

vars/goDefaultVersion.groovy

chore: bump Go version to 1.15.7

---

vars/withGoEnvWindows.groovy

It set the GO_VERSION environment variable in the context of install and use of Go.
If the GO_VERSION environment variable is not defined then `scripts/install-tools.bat` script fails, so we have to use the variable `version` that is the version passed as a parameter, or the value in GO_VERISON, or the value in the file `.go-version` to set the value of GO_VERSION.
```
[2021-02-04T13:18:07.159Z] C:\Users\jenkins\workspace\Beats_gosigar_PR-153>gvm.exe version 
[2021-02-04T13:18:07.417Z] gvm: error: Malformed version: version
[2021-02-04T13:18:07.417Z] 
[2021-02-04T13:18:07.417Z] C:\Users\jenkins\workspace\Beats_gosigar_PR-153>REM Install the given go version 
[2021-02-04T13:18:07.417Z] 
[2021-02-04T13:18:07.417Z] C:\Users\jenkins\workspace\Beats_gosigar_PR-153>gvm.exe --debug install …
```

fix: GO_VERSION can be undefined

---

src/test/groovy/DetailsURLStepTests.groovy
vars/detailsURL.groovy

See https://github.com/elastic/apm-pipeline-library/issues/961|
There is a bug when using the getStageId with the beats project
Disable the getStageId call temporarily that was introduced with https://github.com/elastic/apm-pipeline-library/issues/935
Relates https://github.com/elastic/apm-pipeline-library/issues/961|
https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-23879/3/console is running with the changes in https://github.com/elastic/apm-pipeline-library/commit/b4fd3a5657b34210d5dc4a4ffdc83e620e9d82fc

Disable getStageId call

---

src/test/groovy/AxisStepTests.groovy
src/test/groovy/FilebeatStepTests.groovy
src/test/groovy/IsBuildFailureStepTests.groovy
src/test/resources/filebeatTest_2/filebeat_container_worker-0676d01d9601f8191.json
vars/README.md
vars/filebeat.groovy
vars/filebeat.txt
vars/isBuildFailure.groovy
vars/isBuildFailure.txt

* new step isBuildFailure
* implement archiveOnlyOnFail for filebeat step
* add some missing annotations on the Axis step tests
Sometimes, we need to archive the Docker logs when there are errors, this new parameter allow that.

feat: Archive only on fail

---

.ci/buildDockerImages.groovy

Introduces build pipeline for the v2 version of the flaky test analyzer.
This preserves the original pipeline for the time being. My intention is to run both analyzers in parallel for a few weeks at least, while we build out and transition the necessary dashboards in Kibana and evaluate what kind of changes we may wish to make to the GitHub integration for PRs.
Eventually, this should a number of issues with the first version of the analyzer, such as poor memory usage and performance. More details on this change can be found here: https://github.com/elastic/observability-dev/blob/master/apps/automation/flaky-test-analyzer/HISTORY.md

Image build pipeline for flaky v2

---

src/test/groovy/PreCommitToJunitStepTests.groovy
vars/README.md
vars/preCommitToJunit.groovy
vars/preCommitToJunit.txt

Configure whether to enable/disable the pre-commited skipped checks as reported in the JUnit.
@SergeyKleyman found that the sanity-checks with skipped linted checks were a bit misleading since they are aggregated in the same test report with some other UTs/ITs....
Then we found out that it's worthy to use a red/green signal for this particular pre-commit checks.

Disable/Enable pre-commit skipped tests in the report

---

src/test/groovy/ReleaseNotificationStepTests.groovy
vars/README.md
vars/releaseNotification.groovy
vars/releaseNotification.txt

Create wrapper to notify by email and slack 
DRY approach, as we sue the same function in different release pipelines.

Add releaseNotification step to simplify agent release pipelines

---

src/test/groovy/GsutilStepTests.groovy
vars/gsutil.groovy

Fallback to curl in case wget is not installed
As long as gsutil is not widely available in each CI Worker we need to configure the installation, so no all the workers got wget so let's try with curl also 
Closes #ISSUE\
```bash
$ curl -sSLo gsutil.tar.gz --retry 3 --retry-delay 2 --max-time 10 https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-319.0.0-linux-x86_64.tar.gz 
$ ls -l gsutil.tar.gz 
-rw-r--r--  1 vmartinez  staff  86364996 17 Feb 09:18 gsutil.tar.gz       
x google-cloud-sdk/.install/.download/
x google-cloud-sdk/.install/anthoscli-linux-x86_64.manifest
```

Support curl in addition to wget for gsutil

---

resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy

Omit notifications with failed steps if build was success
Avoid any kind of misleading when a build was built correctly, since sometime the CI retries a few number of times certain commands which are flaky (normally when interacting with third party systems) and those details should not be shown in the digested status message.
Closes https://github.com/elastic/apm-pipeline-library/issues/991

Omit failed steps if build was success

---

local/configs/plugins.txt

Use the default way of installing plugins
@cyrille-leclerc just cut a release https://github.com/jenkinsci/opentelemetry-plugin/releases

chore: use opentelemetry release

---

vars/gsutil.groovy

Add top level folder to the PATH
Unzip does not strip components, therefore the gcloud is not available in the PATH
```
unzip google-cloud-sdk-319.0.0-windows-x86_64.zip 
Archive:  google-cloud-sdk-319.0.0-windows-x86_64.zip
creating: google-cloud-sdk/.install/.download/
inflating: google-cloud-sdk/.install/anthoscli-windows-x86_64.manifest  
inflating: google-cloud-sdk/.install/anthoscli-windows-x86_64.snapshot.json  
inflating: google-cloud-sdk/.install/anthoscli.manifest  
inflating: google-cloud-sdk/.install/anthoscli.snapshot.json  
inflating: google-cloud-sdk/.install/bq-win.manifest  
```

Unzip does not strip components

---

resources/github-comment-markdown.template
src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/NotificationManagerStepTests.groovy
src/test/resources/steps-errors-with-deleteDir-issue.json

Report only one deleteDir step failure
`deleteDir` step might not be as important as some other steps and might cause some misleading, so if multiple deleteDir failures then let's report only one.
Closes https://github.com/elastic/apm-pipeline-library/issues/1005

Report only one DeleteDir step failure

---

src/test/groovy/GsutilStepTests.groovy
vars/gsutil.groovy

Install the google cloud sdk with Python bundled for Windows
Some Windows versions got issues with the python2.exe
Though we are not the only ones suffering this issue -> https://stackoverflow.com/questions/64289902/gsutil-says-it-cannot-find-python
Python 2 is correctly configured:
And the bundled python has been validated in a W8 VM:

gsutil for windows with python

---

.ci/Jenkinsfile

Remove https://plugins.jenkins.io/junit-attachments/ dependency
https://plugins.jenkins.io/junit-attachments/ is in adoption, and let's remove a plugin that probably we won't need

Remove dependency with https://plugins.jenkins.io/junit-attachments/

---

src/test/groovy/NodeArchStepTests.groovy
vars/nodeArch.groovy

Support `arm64` arch
Otherwise

Support arm64 MacOS M1 workers

---

CHANGELOG.md
src/test/groovy/GitCheckoutStepTests.groovy
vars/gitCheckout.groovy

Adds the `noTags`  option in `gitCheclout`
We are using the apm lib in all our jobs, and we have a custom checkout function that could go away if `gitCheckout` let us chec out wih no tags
Closes #1024

add noTags - fixes #1024

---

src/test/groovy/IsStaticWorkerStepTests.groovy
vars/README.md
vars/isStaticWorker.groovy
vars/isStaticWorker.txt

Create new step to centralise the knowledge when a worker is static or ephemeral
Simplifies the login in some pipelines:
- https://github.com/elastic/beats/pull/24435/files

Add isStaticWorker step

---

resources/slack-markdown.template
src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy

Add build time
It might help to easily identify what builds are flaky because the CI enviornmental issues with the provisioner.
From the UTs
```
*Build*: `folder/mbp/master` <http://jenkins.example.com:8080/blue/organizations/jenkins/folder%2Fmbp/detail/master/1/pipeline|#49> for branch `develop` got the status `ABORTED`. (Took `3 min 22 sec`)
*Changes*: No push event to branch develop
*Tests*: `0` test/s failed out of 121 (click <http://jenkins.example.com:8080/blue/organizations/jenkins/folder%2Fmbp/detail/master/1/tests|here> for further details)
*Steps failures*: `3` (click <http://jenkins.example.com:8080/blue/organizations/jenkins/folder%2Fmbp/detail/master/1/artifacts|here> and open `build.md` for further details)
, tokenCredentialId=test})
```

Slack notification with the total build time

---

docs/RELEASE.md

It includes a link to Gren's configuration file in the automated release doc.
It will document the labels needed to create a release, for the PRs to be present in the changelog.

document Gren and GH labels for the automated release process

---

.ci/Jenkinsfile
src/test/groovy/GetFlakyJobNameStepTests.groovy
vars/README.md
vars/getFlakyJobName.groovy
vars/getFlakyJobName.txt

As a consequence of https://github.com/elastic/apm-pipeline-library/pull/1016 then let's enable a step to calculate the flaky Job Name
Test it out in our master branch

Add getFlakyJobName

---

vars/build.groovy

Distinguish the error since FlowInterruptions provides `getCauses()`. (See https://javadoc.jenkins.io/plugin/workflow-step-api/org/jenkinsci/plugins/workflow/steps/FlowInterruptedException.html#getCauses--)
Fixes some errors
```
groovy.lang.MissingMethodException: No signature of method: hudson.AbortException.getCauses() is applicable for argument types: () values: []
Possible solutions: getCause(), getClass(), initCause(java.lang.Throwable), metaClass(groovy.lang.Closure)
```

Fix the getCause and getCauses for the AbortException

---

local/Makefile

It uses `--force-recreate` instead of `--recreate` in the `make recreate-all` goal.
The flag is not supported, so that goal is not working anymore.

fix: use proper flag or recreate

---

resources/buildKibana.groovy
resources/scripts/build-kibana-docker-image.sh
src/test/groovy/BuildKibanaDockerImageStepTests.groovy
src/test/resources/buildKibana/package.json
vars/README.md
vars/buildKibanaDockerImage.groovy
vars/buildKibanaDockerImage.txt

It creates a new step to build and push the Docker image for Kibana branches or PRs.
It will allow pipelines living in different Jenkins instances (i.e. Beats CI) to call this step, instead of copying the existing pipeline in the APM CI.
Closes #1039
The original pipeline lives in the clusters repository. We should update it to consume this step once merged and released.
Another follow-up is to enable kibana repo as a reference repo for Beats CI

feat: add a new step to build and push a Docker image for Kibana

---

src/test/groovy/BuildKibanaDockerImageStepTests.groovy
vars/buildKibanaDockerImage.groovy

It exports the `KIBANA_DOCKER_TAG` env var to be used in the consumer pipelines with the value of the docker tag that was built, provided by the internal `deployName` variable.
Because there is a existing consumer reading the `DEPLOY_NAME` variable, we are exporting that variable with same value as `KIBANA_DOCKER_TAG`.
Do not break consumers.
- Relates #1039
- Completes #1040

fix: set KIBANA_DOCKER_TAG env var properly

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithAzureCredentialsStepTests.groovy
vars/README.md
vars/withAzureCredentials.groovy
vars/withAzureCredentials.txt

Add new step to interact with azure
Facilitate the consumer's pipelines.
Closes #ISSUE

Add withAzureCredentials step

---

.ci/validateWorkersBeatsCi.groovy

Update worker references in https://beats-ci.elastic.co/job/Beats/job/beats-test-infra/
`arm` workers are now ephemeral and some static workers have been deprecated.

Update beats-ci workers for the test-infra validation

---

src/test/groovy/IsStaticWorkerStepTests.groovy
vars/README.md
vars/isStaticWorker.groovy
vars/isStaticWorker.txt

static ARM workers are not a thing
Ensure the reused workers workaround works for the ephemeral ARM workers

ARM workers are now ephemeral

---

src/test/groovy/HasCommentAuthorWritePermissionsTests.groovy
vars/README.md
vars/hasCommentAuthorWritePermissions.groovy
vars/hasCommentAuthorWritePermissions.txt

it adds a new step to check the permissions of a comment author.

feat: step hasCommentAuthorWritePermissions

---

src/test/groovy/StageStatusCacheTests.groovy
vars/README.md
vars/stageStatusCache.groovy
vars/stageStatusCache.txt

It adds a new step to save/check the last execution status of a stage-based in its name and commit.
This allows skipping stages for the same commit in case of retries.

feat: stage status cache

---

src/test/groovy/BuildStatusTests.groovy
vars/buildStatus.groovy

This fixes a broken step. It was not correctly parsing HTTP results from remote Jenkins servers, causing the step to always fail.
Also adjusts the test for the step to just use a simple mock instead of a tiny server.
Fixing a bug in the apm-java release pipeline. 
cc: @eyalkoren

Fix and simplify buildStatus step

---

resources/JenkinsfileTemplate.groovy

It adds the Ubuntu 20.04 workers to the tests.

test: add Ubuntu 20.04 to the tests

---

src/test/groovy/ApmCliStepTests.groovy
vars/apmCli.groovy

replace the use of readJSON with toJSON.

fix: use toJSON instead readJSON

---

.ci/bumpStackVersion.groovy
src/test/groovy/GithubPullRequestsStepTests.groovy
vars/README.md
vars/gh.groovy
vars/githubPullRequests.groovy
vars/githubPullRequests.txt

Add a new step to query the existing PRs of the current workspace.
Support for the bump automation of either using an existing PR if only one, or create a new one.
This should help to drive the bumping automation requirements.
Closes #ISSUE
In order to run the ITs I created https://github.com/v1v/poc-bump-automation (using the apm-server docker-compose.yml and shell script)
Then I'll run a local pipeline similar to `.ci/bumpStackVersion.groovy` but without the need to checkout the source code from the internal github repository.
There is also a requirement to grant access to the service account to push changes to the above-mentioned github repo.
- `github-invitations`
- `github-accept-invitation id`
Caused
https://github.com/v1v/poc-bump-automation/pull/10 …

Support reusing an existing PR

---

.ci/Jenkinsfile
.ci/packer_cache.sh
local/configs/google.yaml

Reduce maven central issues
Fix GCE configuration
```
jenkins-lint |     "message" : "Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'projects/elastic-images-prod/global/images/elastic-apm-ci-ubuntu-1804-lts-20210302222932'. The referenced image resource cannot be found.",
jenkins-lint |     "reason" : "invalid"
```
Enable to reuse GCE workers and stay alive for 20 minutes.

download maven dependencies earlier and fix GCE configuration

---

resources/scripts/install-with-choco.ps1

Delegate the requirement to use 10.0.13 to the script instead to the workers configuration
Unblock the issues with the apm-agent-python and apm-agent-nodejs build sicne the `--all` flag does not report all the versions. See https://github.com/chocolatey/choco/issues/1843
The proposal works like a charm
```
PS C:\Users\vmartinez> choco install chocolatey -y --version 0.10.13 --allow-downgrade                                                                                                                                                 
Chocolatey v0.10.15                                                                                                                                                                                                                    
Installing the following …
```

tools: fix the chocolatey version

---

.ci/bumpStackVersion.groovy

Force the branch where the PR should be created to
Default branch will always use the git repository one instead where the PR was created from.
For instance https://github.com/elastic/beats/pull/25324 was created using a wrong base branch

Use the base branch to create the PR to

---

.ci/bumpStackVersion.groovy

7.x branch is now back to business
```bash
➜  apm-pipeline-library git:(feature/7.xbranch) ./resources/scripts/artifacts-api-latest-versions.sh 
{
"6.8": {
"start_time": "Tue, 27 Apr 2021 17:11:59 GMT",
"release_branch": "6.8",
"prefix": "",
"end_time": "Tue, 27 Apr 2021 21:11:47 GMT",
"manifest_version": "2.0.0",
"version": "6.8.16-SNAPSHOT",
"branch": "6.8",
"build_id": "6.8.16-b07c9d2a",
"build_duration_seconds": 14388
},
"7.x": {
"start_time": "Tue, 27 Apr 2021 22:57:52 GMT",
"release_branch": "7.x",
"prefix": "",
"end_time": "Wed, 28 Apr 2021 03:37:24 GMT",
"manifest_version": "2.0.0",
"version": "7.14.0-SNAPSHOT",
"branch": "7.x",
"build_id": "7.14.0-a23c7676",
"build_duration_seconds": 16772
},
```
There were some bugs with the artifacts-api and the 7.x branch was pointing to …

artifacts-api is now returning values for the 7.x branch

---

vars/stackVersions.groovy

Bump the Elastic Stack versions

chore: bump stack version

---

src/test/groovy/WithNodeStepTests.groovy
vars/withNode.groovy
vars/withNode.txt

The windows-7-32-bits workers are not working now, let's disable them from the ones we provision.
This is just a proposal and it's disabled now
Since this is something that affects the beats team, we would like to provide a quick workaround to disable what workers should be used when they are broken.
- Keep it disable.
- If the issue still persists then we can enable and apply the filter for the given workers.
Thoughts?

enable to disable a node allocation for flaky workers (disabled for time being)

---

local/Dockerfile
local/docker-compose.yml

* It add a JAVA_OPT with the classpath to allow to use the latest Infra image.
The new image uses ECS and APM and those jar files are in a folder outside the classpath so you need to pass the classpath.

fix: add a JAVA_OPTS env var to fix the container start

---

.ci/dockerImagesOpbeans.groovy
.ci/packer_cache.sh
vars/opbeansPipeline.groovy

This reverts commit 2bc37595ee87c3d9dc4f6993788f048f6ec09f10.
This is a full revert of https://github.com/elastic/apm-pipeline-library/pull/888
I believe that there should not actually be a build step for the Opbeans PHP application. I'll explain my reasoning below.
For the past several builds (and likely since [this PR was merged on January 5](https://github.com/elastic/apm-pipeline-library/pull/888)), the [builds for the Opbeans applications have been failing in the APM CI](https://apm-ci.elastic.co/job/apm-shared/job/apm-docker-opbeans-pipeline/). The reason for this appears to be that [the pipeline expects the existence of a Dockerfile](https://github.com/elastic/apm-pipeline-library/blob/master/.ci/dockerImagesOpbeans.groovy#L78-L87) and [none is …

Revert "[opbeans-php] Add docker build and cache (#888)"

---

src/test/groovy/WithGithubStatusStepTests.groovy
vars/README.md
vars/withGithubStatus.groovy
vars/withGithubStatus.txt

A proposal to avoid any build failures when the GitHub API service is down, for such it adds a new argument called `ignoreGitHubFailures` (default true) that will avoid any build failures if the GitHub API call failed for whatever reason.
Downside:
- It might hide some other misconfiguration in the project though, but users might detect it in case the GitHub commit checks are not reported.
There were some GitHub API issues caused by the GitHub API service (see https://www.githubstatus.com/incidents/fm3pp6t2ytlh) and as a GitHub notify step in the CI pipelines failed
This is a proposal to avoid waste of time to debug failures which are caused by the third-party systems. 
- What do you think?

Add resilience when the github API is down

---

.ci/bumpStackReleaseVersion.groovy
.ci/bumpStackVersion.groovy

The PR creation does a `push` action before submitting the PR, therefore in case the base branch and new branch are equal the branch will be created anyway.
Keep the branches in a good shape.
Manually tested the git diff command:
```bash
➜  apm-pipeline-library git:(feature/avoid-branch-creation-if-no-changes-to-be-applied) git --no-pager log -2 --format=oneline  
283bfe8f9ad86b97fc3cab14bc0b66b0f1065281 (HEAD -> feature/avoid-branch-creation-if-no-changes-to-be-applied, origin/feature/avoid-branch-creation-if-no-changes-to-be-applied) [bump][automation] avoid branch creation if no changes to be pushed
1408eface8ffafcb8b40b6dcfacd4cd9b29c22b5 (upstream/update-stack-version-20210511050138-master, upstream/master, master) Add resilience when the github API is down (#1105)
➜ …
```

[bump][automation] avoid branch creation if no changes to be pushed

---

.ci/bumpStackReleaseVersion.groovy

Regression caused by https://github.com/elastic/apm-pipeline-library/pull/1108 that used an undeclared variable.

Fix null value in the PRs created with the bumpStackReleaseVersion pipeline

---

resources/scripts/pytest_apm/README.md
resources/scripts/pytest_apm/pytest_apm.py
resources/scripts/pytest_apm/setup.py

Support the apm-trace-parent as parameter to use an existing trace context. In this case the one provided by the Jenkins OpenTelemetry

[pytest] Support --apm-trace-parent

---

resources/scripts/apm-cli/README.md
resources/scripts/pytest_apm/README.md
resources/scripts/pytest_apm/pytest_apm.py

Support env variables to pass the credentials instead of using the arguments in the CLI.
No issues to expose credentials in the APM UI when the process metadata provides the CLI arguments

Avoid to expose credentials in the process.args metadata

---

resources/scripts/pytest_apm/pytest_apm.py

Pytest uses [pytest_addoption(parser)](https://docs.pytest.org/en/6.2.x/example/simple.html) and therefore the `env_var` is not supported unless using the `configargparse` library but it's not something we can use ...

parser does not support the env_var

---

.ci/Jenkinsfile
.mvn/wrapper/maven-wrapper.properties
resources/scripts/jenkins/release-perform.sh

Minor changes to use the latest maven wrapper and show the toolchain versions
Since we use the latest maven4 snapshot, this should help to know what's the commit attached to that particular version and be able to report any bugs, if any.
Caused by https://github.com/elastic/apm-pipeline-library/issues/1117
```bash
./mvnw --show-version clean
```
```
Apache Maven 4.0.0-alpha-1-SNAPSHOT (b08e4d277e02abe9455e6c05e8fc6ae2b12a68fe)
Maven home: /Users/vmartinez/.m2/wrapper/dists/apache-maven-4.0.0-alpha-1-SNAPSHOT-bin/s0m0e7mg6h9hr8umuisf0sdq9/apache-maven
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /Users/vmartinez/.sdkman/candidates/java/8.0.282.j9-adpt/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

bump versions and add info details

---

src/test/groovy/WithGoEnvUnixStepTests.groovy
vars/withGoEnvUnix.groovy

Set `GOARCH` on the fly based on the current Worker platform.
The consumers won't need to configure the GOARCH but simply use the step
Closes https://github.com/elastic/apm-pipeline-library/issues/1121

Set GOARCH env variable when using the withGoEnvUnix step

---

resources/scripts/artifacts-api-latest-release-versions.sh
resources/scripts/artifacts-api-latest-versions.sh

It adds an URL param to Elastic's artifacts endpoint.
With this parameter, the download metrics won't be impacted by internal-automated hits.

chore: do not impact Elastic's download metrics

---

.ci/buildDockerImages.groovy

Build docker image for https://github.com/elastic/azure-vm-extension/pull/9
Faster builds

docker: cache the azure-vm-tools docker image

---

.mvn/wrapper/maven-wrapper.properties

I see some errors recently with the maven release process.
```
[2021-06-07T14:59:56.074Z] [INFO] ------------------------------------------------------------------------
[2021-06-07T14:59:56.074Z] [INFO] BUILD SUCCESS
[2021-06-07T14:59:56.074Z] [INFO] ------------------------------------------------------------------------
[2021-06-07T14:59:56.074Z] [INFO] Total time:  35.002 s
[2021-06-07T14:59:56.074Z] [INFO] Finished at: 2021-06-07T14:59:55Z
[2021-06-07T14:59:56.074Z] [INFO] ------------------------------------------------------------------------
[2021-06-07T14:59:56.074Z] java.lang.NullPointerException
[2021-06-07T14:59:56.074Z] 	at org.fusesource.jansi.AnsiPrintStream.uninstall(AnsiPrintStream.java:79)
[2021-06-07T14:59:56.074Z] 	at …
```

Use maven 3.8 to fix issues with the release

---

resources/scripts/artifacts-api-7.x-version.sh
vars/artifactsApi.groovy

Helper to given the branch 7.x name returns the elastic version.
This will help with some of the automation we have done to bump versions, since 7.x branch is not an easy one.
Required by https://github.com/elastic/azure-vm-extension/pull/13

Add 7.x-version action

---

.ci/.bump-stack-release-version.yml

Bump Elastic versions for the repo azure-vm-extension
To run the ITs in the cloud for the azure-vm-extension
Depends on https://github.com/elastic/azure-vm-extension/pull/13

Bump release versions for the azure-vm-extension

---

.ci/validateWorkersBeatsCi.groovy

Disable test-infra in a couple of macos workers
Docker is not enabled so let's avoid the test-infra until they are fixed.
Refs: https://github.com/elastic/infra/issues/29456

Disabled test-infra in the beats-ci workers without docker

---

.ci/.bump-stack-release-version.yml
.ci/bumpStackReleaseVersion.groovy

Support the bump of the elastic stack version for the apm-agent-rum-js
Support to customise the title since the apm-agent-rum-js uses some commit-linting and PR title linting
Automate the bump
Requires https://github.com/elastic/apm-agent-rum-js/pull/1038

Automate the release stack version for the apm-agent-rum-js

---

.ci/.bump-go-release-version.yml
.ci/bump-go-release-version.sh
.ci/bumpGoReleaseVersion.groovy
.ci/jobs/apm-pipeline-library-mbp.yml
.ci/jobs/bump-go-release-version-pipeline.yml
.ci/schedule-weekly.groovy
src/test/groovy/GoVersionStepTests.groovy
vars/README.md
vars/goVersion.groovy
vars/goVersion.txt

* `goVersion` step to interact with the go releases. It supports unstable and stable releases and also filter releases with some glob format.
* Enable the go bump automation pipeline on a weekly basis.
* Add go bump automation in the apm-pipeline-library.
First step to automate other projects similar what we have done already with the elastic stack versions.
```bash
$ .ci/bump-go-release-version.sh 1.16.1
[feature/go-versions f97a3d4] [Automation] Update go release version to 1.16.1
1 file changed, 1 insertion(+), 1 deletion(-)
commit f97a3d47529cc9142505999de7587d7afd91859e (HEAD -> feature/go-versions)
Author: Victor Martinez <VictorMartinezRubio@gmail.com>
Date:   Tue Jun 15 16:15:28 2021 +0100
[Automation] Update go release version to 1.16.1
You can now push and create a Pull Request …
```

goVersion step and automate the go bump when a new release is out

---

src/test/groovy/GoVersionStepTests.groovy
vars/goVersion.groovy

Use sort pipe
Otherwise the pipeline won't work
Closes https://github.com/elastic/apm-pipeline-library/issues/1162

Use sort semver until git version support the --sort flag

---

.ci/.bump-go-release-version.yml
.ci/.bump-stack-release-version.yml

Enable support for the 7.x branch after merging https://github.com/elastic/apm-integration-testing/pulls

Bump go version for the apm-its@7.x branch

---

vars/goDefaultVersion.groovy

Bump go release version with the latest release. 
1.16.5

[automation] update go release version 1.16.5

---

.ci/validateWorkersBeatsCi.groovy

It enables two workers disabled due to an issue.

chore: enable macOS workers again

---

.ci/.bump-go-release-version.yml

Enable go version automation for the fleet-server and beats.
No hand
Requires 
- https://github.com/elastic/fleet-server/pull/465
- https://github.com/elastic/beats/pull/26343
- https://github.com/elastic/golang-crossbuild/pull/108

Support go bump for beats, fleet-server and golang-crossbuild

---

.ci/validateWorkersBeatsCi.groovy

enable beats-ci test on a macOS workers that is again available.

chore: enable MacOs worker tests again

---

.ci/bumpGoReleaseVersion.groovy
.ci/bumpStackReleaseVersion.groovy
.ci/bumpStackVersion.groovy
src/test/groovy/GithubPrExistsStepTests.groovy
vars/README.md
vars/githubPrExists.groovy
vars/githubPrExists.txt

If there is need to create a PR for a specific bump, and there is already an open PR for the same bump, then let's skip the PR creation.
Sometimes, teams don't merge those PRs immediately, and therefore the next bump execution might detect that changes were not merged yet and create a new PR for a similar open one.
For instance:
Closes #ISSUE

Bump automation to detect if a similar open PR already exists

---

resources/slack-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy
src/test/resources/changeSet-info-empty-issues.json

Fixes
```
11:49:22  ERROR: notifySlack: Error with the slack comment
11:49:22  java.util.NoSuchElementException: Cannot access first() element from an empty List
11:49:22  Caused: groovy.text.TemplateExecutionException: Template execution error at line 4:
11:49:22           3: <% artifactsUrl = String.format("<%sartifacts|here>", jobUrl)%>
11:49:22       --> 4: <% commitUrl = String.format("<%s|%s>", changes?.issues?.first()?.url, changes?.msg)%>
11:49:22           5: <% pipelineUrl = String.format("<%spipeline|#%s>", jobUrl, build?.id ?: 'build')%>
```
In some cases the issues data structure is empty and the elvis operator does not work as expected
I've seen this error when working on https://github.com/elastic/azure-vm-extension/pull/23

Fix slackMessage when issues is empty

---

.mergify.yml

Delete branches with mergify that were created as part of the bump automation
https://github.com/elastic/apm-pipeline-library/pull/1160

[mergify] clean up branches for the bump automation

---

src/test/groovy/WithNodeStepTests.groovy
vars/withNode.groovy
vars/withNode.txt

Avoid sleep when provisioning a new node by default and delegate that responsibility to the provisioner
Slowness to provision seems to be fixed after the Improve performance when creating or deleting nodes by reducing queue-lock contention. (pull https://github.com/jenkinsci/jenkins/pull/5402, pull https://github.com/jenkinsci/jenkins/pull/540 12) that was backported in 2.289.1
Notifies https://github.com/elastic/beats/pull/26613

Skip sleep by default in the withNode step

---

src/test/groovy/StageStatusCacheTests.groovy
vars/stageStatusCache.groovy

First build can be cached when using the `options { retry(x) }`
Otherwise it will get always triggered.
Notifies https://github.com/elastic/beats/pull/26646

Verify if stageStatusCache even for the first build

---

.ci/.bump-stack-release-version.yml

Enable the automation for the obs-clusters
It was disabled

Enable automation for observability-test-environments

---

.ci/.bump-go-release-version.yml
.ci/.bump-stack-release-version.yml
.ci/bumpGoReleaseVersion.groovy
.ci/bumpStackReleaseVersion.groovy
.ci/bumpStackVersion.groovy
src/test/groovy/GithubCreatePullRequestStepTests.groovy
vars/githubCreatePullRequest.groovy

Set assignee and reviewer if they are defined in the configuration files, otherwise keep the same behaviour as usual.
Assign the `@observability-robots-on-call` reviewer.
**IMPORTANT**: Assignees cannot be a team but a user. While reviewers can be teams also.
More fine granularity to avoid PRs getting stalled or miss them.
Try out the `on-call` approach we discussed recently, where the person who is `on-call` will be assigned to the `on-call` github team and then all the notifications should be sent correctly as expected.
See [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-pipeline-library-mbp/detail/test%2Fchanges-assign-and-reviewers/6/pipeline) that was created to verify if `.ci/bumpStackReleaseVersion.groovy` works as expected …

Bump automation to set the assignee and reviewer if defined

---

.ci/bumpStackReleaseVersion.groovy
.ci/bumpStackVersion.groovy

Validate if the docker images are accessible. Test at least elasticsearch, though we might need to validate kibana too and apm-server
Avoid creating PRs https://github.com/elastic/apm-integration-testing/pull/1198 that should not be created if those docker images are not available yet.
```
[2021-07-05T15:15:32.362Z] ERROR: for elasticsearch  manifest for docker.elastic.co/elasticsearch/elasticsearch:7.13.3 not found: manifest unknown: manifest unknown
```

Validate elastic stack versions are available

---

.ci/validateWorkersBeatsCi.groovy
resources/scripts/jenkins/beats-ci/test-mac.sh

Disable MacOS worker with some docker environmental issues
When using docker https://beats-ci.elastic.co/computer/worker-c07c6107jyw0/ gets stalled 
Relates https://github.com/elastic/beats/pull/26789

[test-infra] disable worker-c07c6107jyw0 and use docker-machine if possible

---

.ci/bumpStackVersion.groovy

Pinned snapshot versions use -SNAPSHOT suffix, while the version retrieved does not contain the SNAPSHOT suffix, let's ensure it's there otherwise the validation will report the docker image is not yet available.
Otherwise the automation won't work
Build logs https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fbump-stack-version-pipeline/detail/bump-stack-version-pipeline/67/pipeline/59 for a wrong validation

[bump][pinned][version] Validate snapshot versions

---

resources/scripts/build-kibana-docker-image.sh

* set BUILD_TS_REFS_DISABLE=true
it fixes the issue 
```
[2021-07-08T23:50:54.174Z] ERROR [bootstrap] failed:
[2021-07-08T23:50:54.174Z] ERROR Error: Command failed with exit code 1: /var/lib/jenkins/workspace/apm-shared/oblt-test-env/custom-kibana-deploy/src/github.com/elastic/kibana/.nvm/versions/node/v14.17.3/lib/node_modules/yarn/bin/yarn.js run kbn:bootstrap
[2021-07-08T23:50:54.174Z]       error Command failed with exit code 1.
[2021-07-08T23:50:54.174Z]       $ node scripts/build_ts_refs --ignore-type-failures
[2021-07-08T23:50:54.174Z]        info ensuring we have the latest changelog from upstream master
[2021-07-08T23:50:54.174Z]        info determining merge base with upstream
[2021-07-08T23:50:54.174Z]       ERROR UNHANDLED ERROR
[2021-07-08T23:50:54.174Z]       ERROR Error: …
```

fix: set BUILD_TS_REFS_DISABLE=true

---

vars/README.md
vars/gitCheckout.groovy
vars/gitCheckout.txt

retry param is not needed/used, in fact, it's now delegated to the built-in git/checkout steps
It was a leftover from https://github.com/elastic/apm-pipeline-library/pull/352
Closes https://github.com/elastic/apm-pipeline-library/issues/1205

Remove retry param from gitCheckout

---

vars/goDefaultVersion.groovy

Bump go release version with the latest release. 
1.16.6
Blocked by https://github.com/elastic/beats/pull/26860

[automation] Update go release version 1.16.6

---

src/co/elastic/Nexus.groovy
src/test/groovy/NexusFindStagingIdTests.groovy
vars/nexusCloseStagingRepository.groovy
vars/nexusCloseStagingRepository.txt
vars/nexusCreateStagingRepository.groovy
vars/nexusCreateStagingRepository.txt
vars/nexusDropStagingRepository.groovy
vars/nexusDropStagingRepository.txt
vars/nexusFindStagingId.groovy
vars/nexusFindStagingId.txt
vars/nexusReleaseStagingRepository.groovy
vars/nexusReleaseStagingRepository.txt
vars/nexusUploadStagingArtifact.groovy
vars/nexusUploadStagingArtifact.txt

Fixes an error with JSON de-serialization and refactor all Nexus steps to accept a username/password instead of using Vault internally.
We want to be able to control the Vault retrieval from the pipeline in a single location instead of letting each step manage it to simplify things and to avoid errors which were happening with authentication.
Additionally, we fixed an issue that was found when de-serializing JSON responses on-the-fly. 
Refs https://github.com/elastic/observability-robots/issues/584

Fix Nexus integration

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/create_oblt_cluster.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/update_oblt_cluster.groovy

* It adds create/update pipelines for the oblt-clusters
These pipelines replaces the branches and uses configuration files only to create/update pipelines

feat: create/update clusters pipelines

---

.github/dependabot.yml

Add the oncall team instead of the obs-robots 
Reduce the notifications that are handled by the oncall person

[dependabot] change reviewer for the oncall person

---

vars/stageStatusCache.groovy

Stages should not be accessible publicly. 
Fixes an environmental issue
```
[2021-07-27T17:23:06.744Z] + gsutil -m -q cp -a public-read eC1wYWNrL29zcXVlcnliZWF0LXdpbmRvd3MtOC13aW5kb3dzLTg0MDVlMDczYjQ1ZGQyYWI5NDNkYTBkZjYxZTFhMTQ4NzkyNWQ4OTk0 gs://beats-ci-temp/ci/cache/
[2021-07-27T17:23:12.061Z] ServiceException: 401 Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object.
[2021-07-27T17:23:12.061Z] CommandException: 1 file/object could not be transferred.
script returned exit code 1
```
Build logs -> [here](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-27080/2/pipeline#step-29342-log-1)

Cache stage without public access and retry

---

src/co/elastic/BuildException.groovy

It adds a new constructor for BuildException and refactor all to use the sme constructor
We have detected that build causes now is a List
```
[2021-07-29T06:31:23.330Z] groovy.lang.GroovyRuntimeException: Could not find matching constructor for: co.elastic.BuildException(java.lang.String, hudson.model.Result, java.util.Arrays$ArrayList)
[2021-07-29T06:31:23.330Z] 	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1732)
[2021-07-29T06:31:23.330Z] 	at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1532)
[2021-07-29T06:31:23.330Z] 	at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:49)
[2021-07-29T06:31:23.330Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray …
```

fix: add a new constructor to BuildException

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/test_mbp.groovy

* It uses some old-style settings to configure the detection of PRs
The configure block does not work after jobDSL 1.74 due to a security patch, so we have to rely on deprecated setting until there is another solution.

fix: set some old settings to detect PRs

---

src/test/groovy/RandomStringStepTest.groovy
vars/randomString.groovy

Avoid a random string that starts with a `-`
Azure naming convention does not allow that
```
[2021-08-04T08:59:39.911Z] │ Error: "name" must begin with an alphanumeric character
```

randomString without starting with -

---

.ci/schedule-weekly.groovy

The emails for the different branches are combined into a single email thread by Google which is confusing. Somehow Google assumes because there is only a slight change in
the prefix that it is the same mail thread (it is not). I'm trying to prevent this by adding the branch names also to the second part of the subject.

Adjust weekly Beats headers to outsmart Google

---

local/configs/jenkins.yaml
local/configs/plugins.txt
local/docker-compose.yml

Enable the OpenTelemetry plugin that uses the ElasticStack we have in place.
https://github.com/elastic/apm-pipeline-library/pull/1051 was reverted since it created a local ElasticStack environment. So this approach uses our ES that runs in the Cloud.
To test this functionality locally and easily
This will help me to debug -> https://github.com/elastic/apm-agent-java/pull/2103 since somehow the `withOtelEnv` is not working as expected or something else is causing some issues.
You need to `make -C local clean` or destroy your local container.
Otherwise you might face issues with the existing opentelemetry version

Enable the opentelemetry

---

.ci/jobs/gather-ci-metrics-pipeline.yml
.ci/schedule-daily.groovy

Collect metrics regarding the reused workers in the CI (apm-ci).
The pipeline is defined in another repository, therefore this is only the JJBB and the job call.
We already use a similar approach for the `beats-ci`

Add reused workers metrics in the apm-ci

---

src/test/groovy/WithOtelEnvStepTests.groovy
vars/withOtelEnv.groovy
vars/withOtelEnv.txt

Opentelemetry 0.19 already supports this feature, but let's support previous versions
Simplify the consumers of the withOtelEnv and other integrations to consume `TRACEPARENT` directly rather than generating it.

Support traceparent with otel

---

.ci/bumpStackVersion.groovy
.ci/githubSyncupLabelsObsDev.groovy

Uses the main branch instead of the master branch when checking out `observability-dev`.
When using the `master` branch, we end up with an empty checkout. This causes failures such as https://apm-ci.elastic.co/job/apm-shared/job/bump-stack-version-pipeline/112/

Switch observability-dev checkouts from master branch by default to main branch

---

.ci/schedule-daily.groovy

Add explicit agent name to be searched
Otherwise it uses the default value that points to a different CI instance

Gather metrics for the apm-ci with apm-ci agents

---

.ci/Jenkinsfile
pom.xml

Added the extension to instrument this maven builds. Added the build stage
Use https://github.com/elastic/opentelemetry-maven-extension

Enable Otel maven plugin

---

resources/github-comment-markdown.template

Very minor change just to improve the readability of part of the GitHub template.
It isn't.

Minor grammar fix to GH template

---

.ci/dockerImagesOpbeans.groovy

Catches a condition where sometimes workers labled as `docker` can be Windows.
Corrects occasional build failures such as this one: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-docker-opbeans-pipeline/detail/apm-docker-opbeans-pipeline/779/pipeline

Support Windows workers for docker builds

---

.ci/buildDockerImages.groovy

* remove APM Server Docker images build
It fixes the Docker images build https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-docker-images-pipeline/detail/apm-docker-images-pipeline/1259/

fix: remove APM Server Docker images build

---

src/test/groovy/DockerLoginStepTests.groovy
vars/README.md
vars/dockerLogin.groovy
vars/dockerLogin.txt
vars/getVaultSecret.txt

Add new parameters to the dockerLogin to configure the vault with different default values.
Allow to use different role/secret-id in Vault in a different CI
`dockerLogin` steps consumes [getVaultSecret](https://github.com/elastic/apm-pipeline-library/blob/master/vars/getVaultSecret.groovy) which already provides those parameters to be configured. Therefore, there is no need to set those parameters with any default values but pass through the `args` data structure from `dockerLogin` to `getVaultSecret`.

Support role and secret vault in dockerLogin

---

.ci/validateWorkersBeatsCi.groovy

Add a new worker type for being validated.
This could be used by the integrations team in the near future

[test-infra][beats-ci] validate windows-2019 with docker

---

.ci/Jenkinsfile
resources/commands-github-comment-markdown.template
src/co/elastic/NotificationManager.groovy

* Improve the development experience with some description about what those GitHub commands do.
* In addition, I remove the support for `Jenkins run the ....` from the list of supported GitHub commands, still people can use it, but we want to deprecate it.
* Added support for `run infra tests`
`getSupportedGithubCommands` contains the list of supported GitHub commands and what they do.

Add GitHub commands with the description

---

src/co/elastic/NotificationManager.groovy

Add explicitly support for the GitHub commands in Beats:
- https://github.com/elastic/beats#pr-comments
Those commands are defined in another pipelines therefore they cannot be accessed directly. Such as:
- https://github.com/elastic/beats/blob/master/.ci/packaging.groovy#L37
- https://github.com/elastic/beats/blob/master/.ci/beats-tester.groovy#L22

Add GitHub commands for the Beats project

---

resources/flaky-github-comment-markdown.template

Remove the test summary in the flaky comment.
It's already duplicated in the GitHub build comment which it runs always by default. So this could help to reduce the verbosity in the GitHub comments .

Remove test stats in the Flakyness github comment

---

resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy
src/test/resources/build-info_aborted_allowed_to_run.json
src/test/resources/steps-errors-allowed-to-run.json

Exclude certain errors from the GitHub comment.
Those errors don't provide any value to the contributor/reviewer. And might cause some misleading.
See https://github.com/elastic/ecs-logging-nodejs/pull/101#issuecomment-925092969

Exclude errors related to the approval-list and githubPrCheckApproved in the GitHub comment

---

resources/scripts/generate-build-data.sh
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_abort_runs_1_steps-f9074b7b-7552-4ad1-b753-22349b0f4aaf.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_empty_runs_1_steps-d0c9398e-e195-4670-a60c-42f6137c3e6a.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_error_runs_1_steps-61d5f603-0b12-44f1-a722-b476a42c0cdc.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_multitestfailures_runs_1_steps-d56fb1f2-cfe1-4f48-9b1a-5040f0109bef.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_success_runs_1_steps-fb5412aa-feea-4ccd-a33f-60d6bc76e741.json
src/test/resources/mappings/blue_rest_organizations_jenkins_pipelines_it_getbuildinfojsonfiles_unstable_runs_1_steps-0152ed4b-b083-4072-830e-7768364a3597.json
src/test/resources/mappings/mapping-blue-rest-organizations-jenkins-pipelines-it-getBuildInfoJsonFiles-cobertura-runs-1-steps-7nqjX.json

Retrieve more steps that are consumed to generate the GitHub comment with the build status
Some pipeline are that big that their build comment in GitHub does not provide all the errors:
See https://github.com/elastic/beats/pull/27878

Retrive 3x times more steps

---

.ci/.bump-go-release-version.yml

Add `backport-skip` label for certain projects that use the automated bump process
Avoid missing backport labels in the notifications
Caused by https://github.com/elastic/beats/pull/28022 and https://github.com/elastic/fleet-server/pull/723

[bump][automation] skip backports for the automation

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/manage-user-oblt-clusters.groovy

* Rename CCS job to a more generic name
* 
The job will manage all the user cluster types not only the CCS.

chore: rename CCS job to a more generic name

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/IsBeforeGo1_16StepTests.groovy
src/test/groovy/WithGoEnvUnixStepTests.groovy
src/test/groovy/WithGoEnvWindowsStepTests.groovy
vars/README.md
vars/isBeforeGo1_16.groovy
vars/isBeforeGo1_16.txt
vars/withGoEnvUnix.groovy
vars/withGoEnvWindows.groovy

This change fixes Go executable package installation for Go versions at and above Go version 1.16.
Currently, the installation method used by `withGoEnv` is `go get -u` which modifies go.mod and go.sum, causing subsequent tests to fail if building with a go1.16+ toolchain. The preferred method for installation of executable packages since Go 1.16 is `go install host.dom/path/to/pkg@version` with `@version` being `@latest` for the equivalent to the `-u` currently used with `go get` (see [here](https://go.dev/blog/go116-module-changes) under "Installing an executable at a specific version").
Fixes #1299

fix: teach withGoEnv about Go executable package installation for Go 1.16 and up

---

local/Dockerfile
local/configs/plugins.txt

Bump version to consume the latest OpenTelemetry plugin version
Otherwise it fails the local jenkins instance

[dependencies] bump for the local jenkins instance

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithDockerEnvStepTests.groovy
vars/README.md
vars/dockerLogin.groovy
vars/withDockerEnv.groovy
vars/withDockerEnv.txt

It adds `withDockerEnv` as a new step, so that it will run a closure adding the DOCKER_USER and DOCKER_PASSWORD environment variables to the closure.
It's copying the very same logic that the existing `dockerLogin` step, which I'd like to deprecate in favour of this one:
```groovy
def call(Map args = [:]){
withDockerEnv(args) {
// NOOP
}
}
```
In the e2e-testing framework we are seeing that pulling from observability-ci private registry is not possible with the current Go code, which uses the Docker client library to Pull images. This code needs Auth credentials to be set, never mind if we already performed a docker-login in the machine.
Closes #1305

feat: add a new step for adding Docker context to closures

---

src/co/elastic/NotificationManager.groovy

Add GitHub commands for the `observability-test-environments` project
Help with the usability

[github][commands] for the observability-test-environments

---

.ci/.bump-stack-release-version.yml

Tidying up the branches for the obs-test-env repo
Those branches don't exist anymore

bump: obs-test-env is not a multibranch repo

---

src/test/groovy/GhStepTests.groovy

Add test coverage for the `gh` step to validate the same field can be set several times.
To illustrate this is possible

Add test coverage for multi field arguments in gh

---

src/test/groovy/ListGithubReleasesStepTests.groovy
vars/listGithubReleases.groovy

Use the tab separator
Otherwise the list of github releases is always 1!
Until https://github.com/cli/cli/issues/4572 is supported
Using tabs in the UTs
Verified locally in a local jenkins instance

Use tab separator for listGithubReleases

---

src/test/groovy/GhStepTests.groovy
src/test/groovy/GithubIssuesStepTests.groovy
src/test/groovy/GithubPullRequestsStepTests.groovy
src/test/groovy/ListGithubReleasesStepTests.groovy
vars/README.md
vars/gh.groovy
vars/gh.txt

Support for `Windows`, `Darwin` and `Arm`
`isUnix()` returns true for `Darwin` and `Arm`, therefore there was a chance that the consumers run the gh step in one of those OS/Arch, this should avoid that issue
Support for Windows in case it's needed...

Support for macos, arm and windows in the gh step

---

vars/listGithubReleases.groovy

Pin the gh version for the listGithubReleases step
It parses the output, therefore let's ensure any format changes in the output don't affect the step

Pin the gh version for the listGithubReleases step

---

local/configs/jenkins.yaml

Add a default arch in the local worker
`isArm` and some other steps read the labels to be able to know the arch
Otherwise, when testing a pipeline locally if any of those steps are called then it will fail.

chore: add arch

---

src/test/groovy/FindOldestSupportedVersionStepTests.groovy
vars/findOldestSupportedVersion.groovy

* Add support for "or" conditions in `findOldestSupportedVersion`.
* Add support for ">=" operator.
* Tests use `assert` instead of `assertTrue` so they display the checked values in case of failure.
* We may need packages that support multiple majors, for that we need to support expressions such as `^7.16.0 || ^8.0.0`.
- Issue with these expressions found in https://github.com/elastic/integrations/pull/2122.

Find oldest version with or conditions

---

.github/CODEOWNERS
.mergify.yml

Use mergify to auto-assign the PRs to the PR creator and assign `Reviewers` with the Codeowners
Less manual actions

[mergify][codeowners] Auto-assign and add reviewers with Codeowners

---

src/test/groovy/FindOldestSupportedVersionStepTests.groovy
vars/findOldestSupportedVersion.groovy

Add support for the `~` operator in `findOldestSupportedVersion`.
In some packages we may want to play safe by now, see https://github.com/elastic/integrations/pull/2125#discussion_r742613627.

Add support for minor constraints in findOldestSupportedVersion

---

.ci/bumpStackReleaseVersion.groovy
vars/stackVersions.groovy

Enable `bumpUtils.getNextMinorReleaseFor7()` when running the bump script.
The version with the next minor release was removed when refactoring the source of truth with the versions.

Bump release stack version: support for the dev version

---

src/test/groovy/IsInstalledStepTests.groovy
vars/README.md
vars/gh.groovy
vars/isInstalled.groovy
vars/isInstalled.txt

Add version validation in the `isInstalled` step and enable this validation in the `gh` step
Avoid installing if no `forceInstallation` is enabled in the `gh` step in addition enhance the existing step for verifying if the tools are installed.
Notifies https://github.com/elastic/apm-pipeline-library/pull/1358

Enable version validation in the isInstalled step

---

resources/commands-github-comment-markdown.template
src/co/elastic/NotificationManager.groovy

Add the rebuild docs GitHub command.
This is a core feature for some of the GitHub repositories we work with. So let's filer the ones we already know they use it. Such as, all the APM agents, APM Server, Fleet Server, Beats
I could not find what to run so I have to search in another repository to find it.
Unfortunately, we cannot change this behaviour, so we will use the above format but split with `run` `elasticsearch-ci/docs` (this will ensure there is no a space between run and elasticsearch but `)

Add GH command for rebuilding the docs builds

---

.mergify.yml

Notify the backported PRs from mergify if they have not been merged.
To test https://github.com/elastic/e2e-testing/pull/1792 (this PR is a subset of the e2e-testing one)

[mergify] notify to the assignee if PR was not merged yet

---

.mergify.yml

Fixes
It uses the same approach as explained in https://github.com/Mergifyio/mergify-engine/blob/b6b2fc695c75f510e879281ecabd28e1c889ddbc/docs/source/configuration.rst#template
Notify correctly

[mergify] transform assignee list in GitHub users

---

resources/ci-builds-mapping.json
resources/scripts/generate-build-data.sh

Remove metric for liveness issues with nodes in the CI
This can be only searched outside of the build context.
```
[2021-11-11T16:14:25.545Z] [Pipeline] End of Pipeline
[2021-11-11T16:14:27.032Z] Also:   java.lang.Exception: computer does not correspond to a live node
[2021-11-11T16:14:27.032Z] Also:   java.lang.Exception: computer does not correspond to a live node
[2021-11-11T16:14:27.032Z] Also:   java.lang.Exception: computer does not correspond to a live node
[2021-11-11T16:14:27.032Z] Also:   java.lang.Exception: computer does not correspond to a live node
[2021-11-11T16:14:27.032Z] Also:   java.lang.Exception: computer does not correspond to a live node
[2021-11-11T16:14:27.032Z] Also:   java.lang.Exception: computer does not correspond to a live node
[2021-11-11T16:14:27.032Z] …
```

Metrics: cannot be search within the build context

---

.grenrc.js

There is a trailing-whitespace in `.grenrc.js`

fix: trailing-whitespace

---

.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/stack_docker_images.groovy

* It reimplements the dynamic generation of the Docker images jobs but without the need for approval classes.  
* Adds a new job to pull/push the Elastic Stack Docker images 
The new jobs are created for Docker image that allow tracking issue on a single image, the jobDSL job makes it easy to add new docker images.

feat: build docker images isolated

---

src/test/groovy/IsUpstreamTriggerStepTests.groovy
vars/isUpstreamTrigger.groovy

Supports https://javadoc.jenkins-ci.org/hudson/model/Cause.UpstreamCause.html
Otherwise in some cases the `isUpstreamTrigger` won't detect those builds.

Fix upstream build reasons

---

.mergify.yml

Notify if a backported PR has not been updated in the last two days and there is at least one assigned person
This could help with the notifications with a certain `schedule` since it will only report if they are at least 2 days without any activity
See https://github.com/Mergifyio/mergify-engine/blob/b6b2fc695c75f510e879281ecabd28e1c889ddbc/docs/source/configuration.rst#relative-timestamp
cc @jsoriano since you asked about this in https://github.com/elastic/beats/pull/28964

[mergify] notify backported PRs without changes in the last 2 days and at least one assigned person

---

local/Dockerfile
local/Makefile

Update the local docker image to the latest release
```
make build start
WARNING: The VAULT_TOKEN variable is not set. Defaulting to a blank string.
[+] Building 15.7s (8/8) FINISHED                                                                                                                                                                                                      
=> [internal] load build definition from Dockerfile                                                                                                                                                                              0.0s
=> => transferring dockerfile: 230B …
```

[local] bump docker version to 2.303.3

---

resources/versions/releases.properties
vars/stackVersions.groovy

`current_7` is now 7.15.2, aka latest release
`edge` is now `8.1.0`

bump: releases

---

vars/buildKibanaDockerImage.groovy

* Fix the target Docker image name for tag and push operation.
The target Docker image does not change in the current implementation so it tries to push Docker images to the wrong place.
Related to https://github.com/elastic/apm-pipeline-library/pull/1391

fix: tag and push to the image target name

---

docs/CONTRIBUTING.md

Fix the reference to the development section since the code guidelines is pointed out later on in a different section

Docs: add link to the development doc

---

vars/buildKibanaDockerImage.groovy

* Use a different image name for cloud images
The previous implementation is overwriting the Docker images

fix: use a diferent target for cloud images

---

vars/notifyBuildResult.groovy

Reenable the deleteDir in the notifyBuildResult.
I saw some weird behaviour with the test reporting in the GitHub comments.
A file timestamp was wrong 
Tests are not present
But the json with the tests files is filled with probably some data from a previous build:
I wonder if something is cached in the Jenkins controller ?
Initially enabled in https://github.com/elastic/apm-pipeline-library/pull/511
Removed in https://github.com/elastic/apm-pipeline-library/pull/904

ci: delete workspace after notifying

---

pom.xml
resources/github-comment-markdown.template
src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
src/test/groovy/co/elastic/mock/RunMock.groovy

Support for DisableConcurrentBuildsJobProperty in order to notify the build status in the GitHub comment if the build was aborted when using the new property.
Keep the DX similar to what we have already in place with the CancelPreviousBuild.
Closes https://github.com/elastic/apm-pipeline-library/issues/1420

Support for DisableConcurrentBuildsJobProperty

---

.ci/build-docker-images.groovy

* Add `$HOME/bin`, and `$HOME/go/bin` to the PATH
We have cases in which we install tools and they should be in the path.
```
11:34:41  + cat ../../.go-version
11:34:41  + gvm 1.17.2
11:34:48  + eval export GOROOT="/var/lib/jenkins/workspace/apm-shared/docker-images/metricbeat-integrations-images-x-pack/.gvm/versions/go1.17.2.linux.amd64" export PATH="/var/lib/jenkins/workspace/apm-shared/docker-images/metricbeat-integrations-images-x-pack/.gvm/versions/go1.17.2.linux.amd64/bin:$PATH"
11:34:48  + export GOROOT=/var/lib/jenkins/workspace/apm-shared/docker-images/metricbeat-integrations-images-x-pack/.gvm/versions/go1.17.2.linux.amd64 export PATH=/var/lib/jenkins/workspace/apm-shared/docker-images/metricbeat-integrations-images-x-pack/.gvm/versions/go1.17.2.linux.amd64/bin:/usr/local/bin:/us …
```

fix: add HOME folders to the PATH

---

.ci/Jenkinsfile
resources/JenkinsfileTemplate.groovy
vars/README.md
vars/cancelPreviousRunningBuilds.groovy
vars/cancelPreviousRunningBuilds.txt

Avoid killing builds for branches/tags but only for PRs
Otherwise builds running on branches are killed
Closes https://github.com/elastic/apm-pipeline-library/issues/1439

Abort on PR basis if an old running build

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/WithOtelEnvStepTests.groovy
src/test/groovy/co/elastic/mock/OtelHelperMock.groovy
vars/withOtelEnv.groovy

Support the fallback case to run the body when no otel plugin configuration has been defined
Ensure we allow the CI to run correctly when misconfigured

Support the case when OTEL plugin has not been configured

---

src/test/groovy/WithOtelEnvStepTests.groovy
vars/withOtelEnv.groovy

We can now support the case of running an endpoint in a secured environment without the need of a credentials.
Be able to send traces :)

Support for no credentials but endpoint

---

.ci/updateStackReleaseVersion.groovy

`7.17` branch is a new one, therefore let's  enable the next minor 7 version.
Keep the automation running

Add 7.17 branch versions

---

.ci/buildDockerImages.groovy

Use `--no-cache                Do not use cache when building the image`
Node:16 and Node:17 cached docker images point to node:8
Relates to https://github.com/elastic/ecs-logging-nodejs/issues/112

docker: no cache flag when building the image

---

.ci/updateStackReleaseVersion.groovy

Bump latest releases for 7 and 6 lines
Keep the bump automation working as expected

Bump 7.16.2 and 6.8.22 versions

---

.ci/schedule-weekly.groovy

Support two 7 minor branches (7.16 and 7.17)
`7.17` was not reported while `7.16` is also active.
Thanks @ruflin for pointing out about this
How to dynamically know if there are two active 7.minor branches
Requires https://github.com/elastic/apm-pipeline-library/pull/1470

Beats: notify 7 next minor branch and 7 current branch

---

src/test/groovy/BumpUtilsStepTests.groovy
vars/README.md
vars/bumpUtils.groovy
vars/bumpUtils.txt

Support a way to know the current active branches by consuming `bump.getNextMinorRelease` and similar steps
Then we won't need elastic/beats#29602 since we can use bump.branch(bump.getNextMinorReleaseFor7) that returns 7.17 rather than 7.17.0

Support major.minor ElasticStack versions for the current/next releases

---

src/test/groovy/BumpUtilsStepTests.groovy
vars/bumpUtils.groovy

Use a version rather than the alias.
To be agnostic to the aliases and allow other use cases.

Use string versions for the getMajor* helper functions

---

src/test/groovy/WithGCPEnvStepTests.groovy
vars/README.md
vars/withGCPEnv.groovy
vars/withGCPEnv.txt

Enable vault customisation for the withGCPEnv
Similar to https://github.com/elastic/apm-pipeline-library/pull/1435

Allow to customise the vault token in withGCPEnv

---

src/test/groovy/WithGCPEnvStepTests.groovy
vars/README.md
vars/withGCPEnv.groovy
vars/withGCPEnv.txt

Support the `value` field in addition to the existing support for the `credentials` one.
Some secrets are managed with terraform and therefore the field is not matching the default one.
Let's keep backward compatibility with the existing credentials one.
For context, `credentials` was aimed to be the mandatory field in order to early detect wrong vault secrets, since `value` is the default field then a secret could be used wrongly and the failure will not be detected earlier but when running the `gcloudAuth` method.

withGCPEnv: support for value default field in the vault secret

---

src/test/groovy/WithAWSEnvStepTests.groovy
vars/withAWSEnv.groovy

Add support for ARM 
See https://aws.amazon.com/blogs/developer/aws-cli-v2-now-available-for-linux-arm/
Required to use ARM
Caused by https://github.com/elastic/apm-aws-lambda/pull/101

withAWSEnv: add support for ARM

---

.ci/.bump-stack-version.yml
.ci/bumpStackVersion.groovy
src/test/groovy/GetBranchNameFromArtifactsAPIStepTests.groovy
vars/README.md
vars/getBranchNameFromArtifactsAPI.groovy
vars/getBranchNameFromArtifactsAPI.txt

- chore: copy stack version bumps from oblt-dev
- chore: use apm-pipeline library as repository for stack version bumps
- feat: add a step to retrieve the branch name supporting multiple minors
- chore: use new step to retrieve the branch name for the stack update
It adds a new step that supports passing a branch with a specific format:
- major.minor
- major.<minor>
- major.<minor-$index>
The index will be used to retrieve a previous minor version of the stack
It could be the case where there are multiple minors in development at the same time, 7.16 and 7.17, and with previous behaviour, the automation discarded those cases where the project needed a bump in two minors (See e2e-tests, that needs bumps in 7.16 and 7.17)

Minor index

---

.ci/.bump-stack-version.yml

Enable `7.minor-1` for the ElasticStack bump automation in the remaining projects.
Support the active branches
Uses https://github.com/elastic/apm-pipeline-library/pull/1503

automation: enable 7.<minor-1> alias for the beats, fleet-server and apm-server projects

---

src/co/elastic/NotificationManager.groovy

Use the REPO or REPO_NAME to enable the GitHub commands
Keep the code cleaner with repo filtering rather than comment patterns

github: filter by the repo env variable

---

src/test/groovy/GetBranchNameFromArtifactsAPIStepTests.groovy
vars/getBranchNameFromArtifactsAPI.groovy

Fix a bug when parsing the `main`/`master` branch
Otherwise the automation for the bump wont' work in the default branches
Fixes

fix: skip branch parsing when format is not major.minor.patch based

---

resources/custom-build-report-mapping.json
resources/scripts/generate-build-data.sh
vars/notifyBuildResult.groovy

Enable a new index for the https://github.com/elastic/integrations project as it relies in the test data structure to report when tests are not executed or skipped
Enable the contract we had with the `jenkins-build` index while we will spend time in a long term proposal to migrate the existing implementation to something else.
Enable partially https://github.com/elastic/apm-pipeline-library/pull/1417 for the https://github.com/elastic/integrations
```
PUT /ci-integrations-builds-000001
PUT /ci-integrations-builds-000001/_mapping
{
}
POST /_aliases
{
"actions": [
{
"add": {
"index": "ci-integrations-builds-000001",
"alias": "ci-integrations-builds",
"is_write_index": true
}
}
]
}
```

report: enable a new index for reporting tests in the integrations

---

src/co/elastic/NotificationManager.groovy

Enable new GitHub command support for the APM Agent Java.
Caused by https://github.com/elastic/apm-agent-java/pull/1705

github commands: enable windows support for the java-agent

---

resources/scripts/pytest_otel/Makefile
resources/scripts/pytest_otel/docs/demos/test/test_demo.py

* It uses a new set of tests for the demos.
Before this change we use the pytest-otel tests for the demos, we can no longer use those tests because we use the In-Memory Otel exporter and a file to check the plugin behavior, this causes not all the traces to be reported to the demo. Using a simpler test suit for the demos fixes the issue.

fix: use different tests for the demos

---

.ci/build-docker-images.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

* Refactor properties and pipeline options
The jobDSL jobs only keep the history is you don't modify them, there are some sections in pipelines that trigger a modification on the job (options, trigger, ...) this PR try to move as much as possible to jobDSL definitions and wrap the rest in a stage to avoid modify the pipeline job when you trigger it.

test: refactor options and properties to avoid modify the jobDSL job on builds

---

.ci/bump-stack-release-version.sh
.ci/updateStackReleaseVersion.groovy
src/test/groovy/StackVersionsStepTests.groovy
vars/stackVersions.groovy

* bump patch version to 8.1
* change stackVersions to use 
It reduces the manual updates we have to make

feat: move stackVersions to use bumpUtils

---

src/test/groovy/co/elastic/mock/OtelHelperMock.groovy
vars/otelHelper.groovy
vars/withOtelEnv.groovy
vars/withOtelEnv.txt

Support JENKINS_OTEL_SERVICE_NAME rather than OTEL_SERVICE_NAME
Read the servicename provided by the Jenkins opentelemetry plugin then context propagation can use it if needed.
Closes #ISSUE

Support for JENKINS_OTEL_SERVICE_NAME with the OTEL_SERVICE_NAME

---

src/test/groovy/GetBranchesFromAliasesStepTests.groovy
vars/README.md
vars/getBranchesFromAliases.groovy
vars/getBranchesFromAliases.txt

getBranchesFromAliases step to replace the code in some pipelines:
- https://github.com/elastic/apm-server/blob/main/.ci/schedule-daily.groovy#L34-L63
- https://github.com/elastic/beats/blob/9d26aea48d4dcf14f146b8a328f5b463c5cfa12d/.ci/schedule-daily.groovy#L34-L67
DRY

getBranchesFromAliases step to avoid duplicated code

---

resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy

This is a workaround to notify pipeline failures while there are no failed steps. With a new section in the build comment
Help users to debug easily when there are pipeline syntax errors or even configuration files.
Relates to https://github.com/elastic/apm-pipeline-library/issues/1555

Notify pipeline syntax/configuration errors

---

src/test/groovy/BuildStepTests.groovy
vars/build.groovy
vars/build.txt

Fixes the build signature
Otherwise:
```
[Pipeline] End of Pipeline
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: build.call() is applicable for argument types: (java.lang.String) values: [java-job]
Possible solutions: call(), call(java.util.Map), wait(), any(), wait(long), main([Ljava.lang.String;)
```
when using
```
stage('Java') {
steps {
build "java-job"
}
}
```

Support build step signature

---

.ci/docker/kibana-yarn/Dockerfile
resources/scripts/build-kibana-docker-image.sh
src/test/groovy/BuildKibanaDockerImageStepTests.groovy
vars/buildKibanaDockerImage.groovy

feat: create a cache Docker image for build Kibana Docker images
* improve build Kibana Docker images
* create a cache Docker image for build Kibana Docker images
In recent changes in the Kibana build system, it is possible to build only Ubuntu or Cloud Docker images this speeds up the build by about 7-10 min. Using a Docker image prepared with all the Node modules in cache reduces the build time of the Kibana binaries by about 25 min.

feat: improve build Kibana Docker images

---

vars/checkout.groovy
vars/git.groovy

Move away from the default first sleep for the checkout and reduce the sleep in git if a retry to 10 seconds.
Let's keep the retry to play safe.
https://issuetracker.google.com/issues/146072599 has been closed so we can assume this issue is not a problem anymore.

ci: remove sleep for git/checkout

---

.ci/.bump-go-release-version.yml
.ci/.bump-stack-version.yml

Prepare the bump automation for the elastic-agent
@narph , can you please review if `.ci/bump-stack-version.sh` and `.ci/bump-go-release-version.sh` are available in the repository? And whether they are gonna work as expected? Those scripts are the ones in charge to bump the golang version when a new one is available or bujmp the snapshot versions when needed, that's the way it works in Beats so far, 
Maybe for the `elastic-agent` is not needed...

automation: add support for elastic-agent

---

vars/runE2E.groovy

It adds the elastic-agent version as an optional parameter.
We need both versions, as the e2e tests could be triggered by Beats (a change on filebeat) and by a change in the elastic-agent
Relates https://github.com/elastic/e2e-testing/pull/2172

chore: pass elastic-agent version to runE2E

---

.ci/.bump-stack-version.yml

It removes the bumps to `7.minor-1` adding them for `8.minor-1`
7.17.1 appeared causing 7.16 to disappear 🤷 
Closes #ISSUE

fix: update maintenance branches

---

.ci/fleet-ci-schedule-daily.groovy
.ci/jobDSL/jobs/fleet-ci/fleet-shared/fleet-schedule-daily.groovy
.ci/jobDSL/jobs/fleet-ci/fleet-shared/gather-ci-metrics-pipeline.groovy

Enable the daily job in `fleet-ci` and the `ci-metrics` one.
1) Gather details about some stats we have in place for the other two CI controllers
2) Leverage the existing JJB/JJBB since it does not work with different CI controllers, while JobDSL can do the heavy-lift.

jobdsl: add daily and ci-metrics jobs in fleet-ci

---

.ci/jobDSL/jobs/fleet-ci/k8s/apm_agent_java_mbp.groovy

Enable MBP for the `v1v/apm-agent-java` (only listening for the `k8s` branch for the time being)
Evaluate the k8s implementation and how it scales in a production CI controller

jobdsl: evaluate k8s for apm-agent-java (stress testing)

---

.ci/.bump-go-release-version.yml

Enable Golang bump automation for the obs-robots project
Update Go versions to keep them up-to-date

ci: golang onboarding, bump version

---

resources/github-comment-markdown.template
resources/slack-markdown.template
src/test/groovy/GenerateBuildDataIntegrationTests.groovy
src/test/groovy/NotificationManagerStepTests.groovy

Fix the space in the env variable
We don't manage the existing CI controllers so we need to patch this temporarily. Even though it is already fixed in the plugin -> https://github.com/jenkinsci/opentelemetry-plugin/pull/361
Closes https://github.com/elastic/apm-pipeline-library/issues/1585

Fix OTEL_ELASTIC_URL with spaces

---

.ci/.bump-go-release-version.yml
.ci/bumpGoReleaseVersion.groovy

Update golang version for the https://github.com/elastic/golang-crossbuild
Maintain multiple active golang-versions without the need to manually bump those versions.
Required https://github.com/elastic/golang-crossbuild/pull/156

bump automation for golang versions

---

src/test/groovy/GetBranchesFromAliasesStepTests.groovy
vars/README.md
vars/getBranchesFromAliases.groovy
vars/getBranchesFromAliases.txt

Support `major.<minor-$index>`
The index will be used to retrieve a previous minor version of the stack
It could be the case where there are multiple minors in development at the same time, 7.16 and 7.17, and with previous behaviour, the automation discarded those cases where the project needed a bump in two minors (See e2e-tests, that needs bumps in 7.16 and 7.17)
Similar to https://github.com/elastic/apm-pipeline-library/pull/1503 and notifies https://github.com/elastic/e2e-testing/pull/2241

getBranchesFromAliases : support minor index alias

---

src/test/groovy/GoVersionStepTests.groovy
vars/goVersion.groovy

See https://github.blog/2021-09-01-improving-git-protocol-security-github/
`git` protocol does not work anymore
fixes
```
git ls-remote --tags --refs git://github.com/golang/go
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

Use https rather than git

---

src/test/groovy/GetBranchesFromAliasesStepTests.groovy
vars/getBranchesFromAliases.groovy

Fix the string transformation to remove the extra `>` and add some UTs for this particular use case
Otherwise:
```
13:33:26  parseInt: index will be considered as zero: java.lang.NumberFormatException: For input string: "1>"
```

fix <minor-1> manipulation

---

vars/tar.groovy

`7z` added the `7z` extension.
Fixes 
versus

fix tar with 7z without extension

---

resources/scripts/generate-email-template-if-no-recent-changes.sh

Use the key file to query if a new update has been done
https://github.com/elastic/beats/pull/30741 removed the support for the `oss` file

email bump automation relies on testing/environments/snapshot.yml

---

resources/github-comment-markdown.template
src/test/groovy/NotificationManagerStepTests.groovy

Notify syntax error if no aborted, otherwise
Avoid misleading messages related to aborted builds
Relates to https://github.com/elastic/apm-pipeline-library/issues/1555 and caused by https://github.com/elastic/apm-pipeline-library/pull/1557

If no aborted then notify the pipeline syntax error

---

.ci/schedule-weekly.groovy

Support weekly email reporting for the https://github.com/elastic/elastic-agent/ and https://github.com/elastic/e2e-testing/
It's now an independent repository and @mdelapenya asked for the e2e-testing one
I also created the watchers
See [build](https://apm-ci.elastic.co/job/apm-shared/job/apm-schedule-weekly/163/) that I was able to use the upstream branch `feature/elastic-agent-weekly-report` and my elastic email to avoid spamming people

weekly test report for elastic-agent and e2e-testing

---

resources/github-comment-markdown.template

fix generateBuildReport: net.sf.json.JSONNull
Corner Case
Closes [#ISSUE](https://github.com/elastic/apm-pipeline-library/issues/1616)

fix generateBuildReport: net.sf.json.JSONNull

---

.ci/.weekly-tests-email.yml
.ci/schedule-weekly.groovy

Refactor the weekly email with the top 7 days test failures with a YAML file.
Easy to onboard new projects if needed.
Additionally, It won't fail if an email stage failed.
I ran [this. build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-schedule-weekly/detail/apm-schedule-weekly/165/pipeline/28)

refactor: weekly email based on yaml file

---

resources/scripts/pytest_otel/src/pytest_otel/__init__.py

* Remove unused impor
It causes an error on pytest <6
```
File "/app/venv/lib/python3.7/site-packages/pytest_otel/__init__.py", line 11, in <module>
from _pytest import timing
ImportError: cannot import name 'timing' from '_pytest' (/app/venv/lib/python3.7/site-packages/_pytest/__init__.py)
```
Closes https://github.com/elastic/apm-pipeline-library/issues/1622

fix: remove pytest timming import

---

.ci/docker/kibana-yarn/Dockerfile

* It adds docker, buildx, and docker-compose to the kibana-yarn Docker image
Kibana now requires buildx to build the Docker images 
related to https://github.com/elastic/kibana/pull/128272

fix: add Docker, buildx, and Docker compose to the Docker image

---

resources/scripts/release-manager-analyser.sh
src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/ReleaseManagerAnalyserStepTests.groovy
src/test/groovy/ReleaseManagerNotificationStepTests.groovy
vars/releaseManagerAnalyser.groovy
vars/releaseManagerAnalyser.txt
vars/releaseManagerNotification.groovy
vars/releaseManagerNotification.txt

Centralise the releaseManagerAnalyser and releaseManagerNotification steps
Help consumers to use the pipeline step then they don't need to worry about implementing anything but using the releaseManagerNotification step to notify and enrich the details with the analyser output
Closes https://github.com/elastic/apm-server/pull/7663 as it will use the new step instead

releaseManagerAnalyser and releaseManagerNotification step

---

resources/scripts/release-manager.sh
src/test/groovy/ReleaseManagerAnalyserStepTests.groovy
src/test/groovy/ReleaseManagerStepTests.groovy
vars/README.md
vars/releaseManager.groovy
vars/releaseManager.txt
vars/releaseManagerAnalyser.groovy

Centralise the release manager step in a shared library
Simplify the consumers since they will just call a step in the pipeline. This step is not needed to run locally at all.
I decided to use a script with env variables rather than using a script with parameters since it will run within the jenkins step and it reduces the number of steps to be able to use it, from
```
def resourceContent = libraryResource("my-script")
writeFile file: scriptFile, text: resourceContent
sh(script: """#!/bin/bash +x
chmod 755 my-script
./my-script param1 param2""")
```
to
```
withEnv(["PARAM1=XXX", "PARAM2=YYY"]) {
sh(script: libraryResource('my-script'))
}
```

Add releaseManager step

---

.ci/updateStackReleaseVersion.groovy

Automate the versions when a new release is out, for such it uses the `artifacts-api` in addition to the incremental patch version.
Add a FORCE flag to create the PR regardless if those versions have not been created yet, that's a common use case until the first snapshot build for `main` or `7.17` is not yet public available, with the new version.
This [build](https://apm-ci.elastic.co/job/apm-shared/job/update-stack-release-version-pipeline/118/) produced https://github.com/elastic/apm-pipeline-library/pull/1634

Automate release versions for 7 and last 8

---

vars/beatsWhen.groovy

There are some runtime issues while using the `noncps` with a `sh` step
It was intended to fix the issues with the serialisation but added a regression by running the noncps with a `sh` step.
https://www.jenkins.io/doc/book/pipeline/cps-method-mismatches/
https://github.com/elastic/apm-pipeline-library/pull/1636#issuecomment-1087855671

Fix Using the node  or sh  steps from this method is illegal

---

.ci/updateStackReleaseVersion.groovy
resources/versions/releases.properties
src/test/groovy/BumpUtilsStepTests.groovy
vars/README.md
vars/bumpUtils.groovy
vars/bumpUtils.txt

Support for the `edge` alias for the version in the `main` branches, therefore
- currentX -> points to the latest release.
- nextMinorX -> points to the upcoming minor release, it supports releases or BCs
- nextPatchX -> points to the upcoming minor release, it supports releases or BCs
As long as there are releases, BCs, and potential `main` release, we need a new alias to distinguish the `main` versions from releases or BCs
See https://github.com/elastic/apm-pipeline-library/pull/1641
This dry-run [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fupdate-stack-release-version-pipeline/detail/update-stack-release-version-pipeline/125/pipeline/61) produced
```
[current_6:6.8.23,
current_7:7.17.2,
next_minor_7:7.17.3,
next_patch_7:7.17.3,
current_8:8.1.2, …
```

Enable edge 8 alias

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/CoverageReportStepTests.groovy
vars/coverageReport.groovy

Enrich the CI with the source integration as stated in https://github.com/elastic/elastic-package/pull/585#issuecomment-970071779
Add source code coverage report
Supersedes https://github.com/elastic/integrations/pull/2986 and https://github.com/elastic/elastic-package/pull/775

ci: enable publishCoverage

---

.ci/.weekly-tests-email.yml
.ci/schedule-weekly.groovy
vars/runWatcher.groovy

* Use the right primitive in the validation
* add `next-minor` to resolve the `8.2` branch
* Use reverse logic for the dry-run
Validated in this [build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fapm-schedule-weekly/detail/apm-schedule-weekly/168/pipeline)

Update weekly email to use the right condition and support 8.2

---

.ci/bumpGoReleaseVersion.groovy
src/test/groovy/GithubPrExistsStepTests.groovy
vars/githubPrExists.groovy
vars/githubPrExists.txt

Filter by all PRs
Avoid duplicated PRs for the Golang bump when PRs are closed
For instance, https://github.com/elastic/beats/pulls?q=is%3Apr+Update+go+release+version+1.18+is%3Aclosed then a new PR should not be created.
https://apm-ci.elastic.co/blue/organizations/jenkins/apm-shared%2Fbump-go-release-version-pipeline/detail/bump-go-release-version-pipeline/62/pipeline/168

Add state filter for the bumpGoReleaseVersion

---

.ci/jobDSL/jobs/apm-ci/folder.groovy
.gitignore

The path of the folder.groovy was changed in the pipeline but the file was in the same place this make the Job generator to fail. This PR move the file and adds a path created by VSCode to .gitignore
related to https://github.com/elastic/apm-pipeline-library/pull/1578

hotfix: move folder.groovy to the root CI jobDSL path

---

src/test/groovy/ApmBasePipelineTest.groovy
src/test/groovy/IsCommentTriggerStepTests.groovy
src/test/groovy/IsMemberOfOrgStepTests.groovy
vars/README.md
vars/isCommentTrigger.groovy
vars/isCommentTrigger.txt
vars/isMemberOfOrg.groovy
vars/isMemberOfOrg.txt

Enable GitHub comments from GitHub users with write permissions. For such, I refactored the `isCommentTrigger` step and created the `isMemberOfOrg`.
Add a new use case when the user has been granted with write permissions in the repository, therefore it's allowed to run in the CI.
Closes https://github.com/elastic/apm-pipeline-library/issues/1650

isCommentTrigger: support for write and org member

---

src/test/groovy/GithubPrCheckApprovedStepTests.groovy
vars/githubPrCheckApproved.groovy

Allow Elasticians to run builds in the CI even if they don't have write access
Otherwise Elasticians cannot contribute smoothly
See https://github.com/elastic/elastic-agent-shipper/pull/21

githubPrCheckApproved with support for Elastic members

---

src/test/groovy/GithubPrCheckApprovedStepTests.groovy
src/test/groovy/GithubRepoGetUserPermissionStepTests.groovy
src/test/groovy/HasCommentAuthorWritePermissionsTests.groovy
src/test/groovy/IsCommentTriggerStepTests.groovy
vars/githubPrCheckApproved.groovy
vars/githubRepoGetUserPermission.groovy
vars/hasCommentAuthorWritePermissions.groovy
vars/isCommentTrigger.groovy

Avoid failing but returning something instead
There are some issues with the API call:
```
githubApiCall: The REST API call https://api.github.com/repos/integrations/collaborators/v1v/permission return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/repos/integrations/collaborators/v1v/permission : httpRequest: Failure connecting to the service https://api.github.com/repos/integrations/collaborators/v1v/permission[](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-3063/14/pipeline/26/#step-67-log-2)[](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-3063/14/pipeline/26/#step-67-log-3) : 
Code: 404
Error: {"message":"Not …
```

githubPrCheckApproved: avoid failing and add UTs

---

src/test/groovy/GithubPrCheckApprovedStepTests.groovy

Interestingly the [PR](https://github.com/elastic/apm-pipeline-library/pull/1659) didn't fail but the merge commit failed :/

fix UT for test_no_allowed_but_member_of_elastic

---

resources/scripts/pytest_otel/requirements.txt

* It updates the OpenTelemetry SDK to 1.11.0
I ran into the issue reported on https://github.com/open-telemetry/opentelemetry-python/issues/2288 when attempting to run filebeat module integration tests (process on https://www.elastic.co/guide/en/beats/devguide/current/filebeat-modules-devguide.html#_test). This occurred while reviewing https://github.com/elastic/beats/pull/31286
Updating to 1.11.0 resolves the error.
To run using this copy against my filebeat integration tests I had to:
1. activate the python env
2. `pip uninstall pytest-otel; pip uninstall opentelemetry-sdk`
3. `pip install pip install ../../apm-pipeline-library/resources/scripts/pytest_otel`
I was able to confirm the correct version was being used via `pip freeze | grep opentelemetry`
At one point I also did a `pip …

feat: Update OpenTelemetry SDK to 1.11.0

---

src/test/groovy/CoverageReportStepTests.groovy
vars/README.md
vars/coverageReport.groovy
vars/coverageReport.txt

Add Map arguments for the coverageReport
Allow to customise the coverage file and location
Notifies https://github.com/elastic/observability-test-environments/pull/2242

Support arguments for the coverageReport step

---

.ci/updateStackReleaseVersion.groovy

Add a section in the description regarding the release might not be available yet
The bump automation runs on a weekly basis, so it's not push based, and consumers are the ones that might consume the latest available release or the upcoming one (they are the ones that decide what to do). Therefore the automation might differ a bit in terms of what files and versions are changed.
In order to avoid any misleading when a PR is created, let's add a more semantic in the description in terms of a PR could fail in the CI if the release has not been published yet.
See the below example:

Add description regarding the releases might not be available yet

---

.ci/.bump-go-release-version.yml

This is my first PR on the automation side of things, apologies if I break something. This adds the `elastic-agent-shipper` to the version bump automation. We already have the bash script in place on the repo side.
Related: https://github.com/elastic/elastic-agent-shipper/issues/4

Add shipper to version bump CI

---

src/test/groovy/RunE2EStepTests.groovy
vars/README.md
vars/runE2E.groovy
vars/runE2E.txt

It removes the NIGHTLY_SCENARIOS from the build step.
That parameter has been deprecated and it's of no use. The e2e are focusing in providing profile descriptors, driven by the `testMatrixFile`
Related to https://github.com/elastic/e2e-testing/pull/2531

chore: remove deprecated parameter

---

.ci/.bump-go-release-version.yml
.ci/bumpGoReleaseVersion.groovy

Allow consumers to specify what Golang major.minor version should be used for their bump automation.
It does not support multiple branches.
Given the version 1.17 and 1.18, and `1.18` the last minor release, then the automation for Beats will try to bump `1.18.patch` rather than `1.17.patch` since the branch main drives the latest minor version for Golang.
Therefore bumps will be closed https://github.com/elastic/beats/pull/31629 since 1.18 is not yet something to be enabled but the bump for `1.17`
Closes #ISSUE

automate the bump of beats@main with go 1.17

---

.ci/.bump-go-release-version.yml

Add fleet-server to the override golang version
Similar to https://github.com/elastic/apm-pipeline-library/pull/1693

override go version for fleet-server

---

src/test/groovy/NotifyBuildResultStepTests.groovy
vars/notifyBuildResult.groovy

Skip coverage markdown creation if there are no entries in the test-coverage.json file
Run if needed only

coverage only if entries in the test-coverage.json file

---

.ci/jobs/apm-pipeline-library-mbp.yml
.ci/jobs/apm-test-pipeline-mbp.yml
.ci/jobs/apm-update-specs-mbp.yml
.ci/jobs/chatops.yml
.ci/jobs/ecs-logging-update-specs-mbp.yml
.ci/jobs/observability-robots-mbp.yml

Use `github-app-apm-ci` credentials
Increase the GitHub API rate limit
Leverage the Multibranch Pipelines with further integrations:
- https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#warnings-checks-for-github-projects
- https://github.com/jenkinsci/checks-api-plugin#pipeline-usage

jjbb: use github-app-apm-ci credentials

---

.ci/.bump-go-release-version.yml

Onboard new projects to the Golang auto-bump
Notifies https://github.com/elastic/elastic-agent-autodiscover/pull/11 https://github.com/elastic/elastic-agent-libs/pull/53 and  https://github.com/elastic/elastic-agent-system-metrics/pull/29

golang: onboard new projects to the autobump

---

local/Dockerfile

Bump the version matching the existing version in production

core: bump docker image for the jenkins local instance

---

.ci/.bump-go-release-version.yml

onboard elastic-agent-inputs for the golang autobump, it uses the current golang version `1.18` rather than `1.17`
Uses https://github.com/elastic/elastic-agent-inputs/pull/13
Closes https://github.com/elastic/apm-pipeline-library/issues/1712

golang: onboard elastic-agent-inputs

---

.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

Build the docker images for the opbeans-php
Cache artifacts
Caused by https://github.com/elastic/opbeans-php/pull/10

ci: build opbeans-php

---

src/co/elastic/NotificationManager.groovy
src/test/groovy/NotificationManagerStepTests.groovy
vars/notifyBuildResult.groovy
vars/notifyBuildResult.txt

Leverage the build notifications to support GitHub issues creation when the build in the CI fails or when it's forced to do it so.
Centralise the notifications in GitHub so the person on-call need to look for certain issues with some filters
Notifies https://github.com/elastic/beats/pull/31954

Add new signature to notify results as GitHub issues

---

vars/README.md
vars/withElasticsearchDeploymentEnv.groovy
vars/withElasticsearchDeploymentEnv.txt

Add `ELASTICSEARCH_` env variables and keep support for the existing ones for backward compatibility reasons.
Those are the env variables used by some other projects, such as the e2e-testing and it seems they are the official ones
There is also support for `ELASTICSEARCH_HOSTS` but for the time being I'll not include
Notifies https://github.com/elastic/e2e-testing/pull/2626

Add ELASTICSEARCH env variables for the withElasticsearchDeploymentEnv

---

src/test/groovy/ApmBasePipelineTest.groovy
vars/withCloudEnv.groovy
vars/withCloudEnv.txt

Update the vault secret to use the one with the specific cloud deployment details
`ec-deployment` is not supported anymore
Relates https://github.com/elastic/observability-test-environments/pull/2352

Read k8s-elasticsearch for the cloud deployment

---

src/test/groovy/WithClusterEnvStepTests.groovy
vars/README.md
vars/withClusterEnv.groovy
vars/withClusterEnv.txt

Keep the default behaviour but allow to disable the Elasticsearch env variables.
Fine granularity to configure the step accordingly.

Enable to disable Elasticsearch in withClusterEnv

---

src/test/groovy/WithVaultTokenStepTests.groovy
vars/withVaultToken.groovy

Retry logic only for the vault access in withVaultToken
Otherwise it runs the given body, but the retry was only aimed to add stability while accessing Vault.

Retry only for the vault access in withVaultToken

---

vars/withTerraformEnv.groovy

Add retry to download terraform
Reduce environmental issues
Reported in https://github.com/elastic/beats/issues/32075

add retry for the withTerraform

---

.github/CODEOWNERS

Updates CODEOWNERS to `observablt-ci`.
Refs https://github.com/elastic/observability-robots/issues/1280

Update codeowners to new CI group

---

src/test/groovy/IsBranchStepTests.groovy
vars/isBranch.groovy

`isBranch` returned true for git tags since `BRANCH_NAME` was evaluated
Fix the misbehaviour since there are some GitHub issues created for tag releases https://github.com/elastic/beats/issues/32140 while the condition is only about `isBranch()` -> https://github.com/elastic/beats/blob/e85d8b9a77d79be3f7defdaa7d99bfa93aae0e11/Jenkinsfile#L207

Fix isBranch to filter out tags

---

.ci/.bump-go-release-version.yml
.ci/bumpGoReleaseVersion.groovy

Enable to customise the PR description for the `golang` autobump.
@cmacknz asked about a particular PR that was failing -> https://github.com/elastic/beats/pull/31827#issuecomment-1168846705
This proposal could help with adding further context regarding the `golang-crossbuild` dependencies with Beats and Elastic Agent.
Currently
Proposal
The existing automation is stateless so, it does not look after cross-project dependencies, so by adding the description with more semantic, I'd expect to answer those questions, what do you think?

automation: enable extended description for the Golang autobump

---

.github/workflows/build-test.yml
.github/workflows/opentelemetry.yml

Enable the OpenTelemetry exporter for GitHub actions with JUnit support
Keep iterating on this so we can gather further insights and see how the existing integration with https://github.com/jenkinsci/opentelemetry-plugin could be also reused (attributes, dashboards) if possible.
For some reason, I cannot test the GitHub actions on this PR but only when it's merged, I don't know whether this will work, since we run some docker containers as part of the UTs.

action: opentelemetry exporter

---

.ci/bumpGoReleaseVersion.groovy
.ci/bumpStackReleaseVersion.groovy
.ci/bumpStackVersion.groovy
.ci/chatops.groovy
.ci/fleet-ci-schedule-daily.groovy
.ci/schedule-daily.groovy
.ci/schedule-weekly.groovy
.ci/updateStackReleaseVersion.groovy
.ci/validateWorkersBeatsCi.groovy

Initial attempt to use the `k8s` gobld workers in those pipelines which are not critical or likely platform specific.
Validate if we can start using it
I triggered manually some pipelines by forcing the `label` to `k8s`:
* https://apm-ci.elastic.co/job/apm-shared/job/apm-schedule-daily/812/console
* https://apm-ci.elastic.co/job/apm-shared/job/apm-schedule-weekly/187/console
```
15:21:45  [Pipeline] Start of Pipeline
15:21:45  [Pipeline] node
15:22:01  Running on [apm-ci-immutable-jenkins-swarm-1657290110773068510](https://apm-ci.elastic.co/computer/apm-ci-immutable-jenkins-swarm-1657290110773068510/) in /home/jenkins/workspace/apm-shared/apm-schedule-weekly
15:22:01  [Pipeline] {
```
* https://apm-ci.elastic.co/job/apm-shared/job/bump-go-release-version-pipeline/84/console

ci: enable k8s workers

---

.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/edge_lite.groovy
.ci/jobDSL/jobs/apm-ci/apm-shared/oblt-test-env/manage_user_oblt_clusters.groovy

Configure the Generic Webhook Trigger on the jobDSL definition.
This defines the trigger at creation time is not needed to run the job one time to configure the triggerts.

feat: add Generic Webhook trigger configuration

---

.ci/docker/Makefile
.ci/docker/jenkins-agent/Dockerfile
.ci/docker/tests/tests_without_run.bats
.ci/jobDSL/jobs/apm-ci/apm-shared/docker-images/build_docker_images.groovy

Host the jenkins-agent docker image
Then we can add the required toolchain and use it when running Jenkins `k8s` workers with `Gobld`. For instance https://github.com/elastic/apm-pipeline-library/pull/1800 is a way to use this particular image
As long as the existing docker image uses centos we are forced to use the hack with the mirrors, already reported to the CI Systems team.
the jenkins-agent container requires some env variables, so the TAP UTs will fail, so `simple-test` contains a subset of tests to be executed
Caused by https://github.com/elastic/apm-pipeline-library/commits/main

Prepare jenkins-agent with the required tools

---

src/co/elastic/NotificationManager.groovy

Remove mention of the `/hey-apm` command in the apm-server repo bot comments.
I'm going to remove the command.
None

Remove mention of "/hey-apm" from apm-server

---

.ci/updateStackReleaseVersion.groovy

Fix the pipeline for the bump versions
It requires docker and k8s workers don't provide that functionality yet

ci: use cloud workers

---

vars/generateGoBenchmarkDiff.groovy

Use nested folders
Otherwise the file cannot contain any nested folders and won't work as expected
https://github.com/elastic/apm-agent-go/pull/1264/files

Fix copyArtifacts for generateGoBenchmarkDiff to use the folder structure

---

.ci/Jenkinsfile

Prepare the context, since the worker is requested and the stage didn't prepare the workspace
Fix a breaking change done with the k8s/github action

ci: fix the workspace setup

---

.ci/.bump-go-release-version.yml

Part of https://github.com/elastic/beats/issues/32328
Allow the Go version bump automation to create PRs upgrading agent+beats repositories to Go 1.18.

Allow agent projects to auto-upgrade to Go 1.18.

---

.ci/updateStackReleaseVersion.groovy

If the list of versions are empty then default to the previous value
Artifacts API might not provide what are the current releases as they are cleaned up after certain time...
I ran this [build](https://apm-ci.elastic.co/job/apm-shared/job/update-stack-release-version-pipeline/217/console) and it worked fine

fix empty list of 7 releases

---

.ci/.bump-go-release-version.yml

Prevents versions bumps to Go 1.19 until we are ready to update, we are
still working to support Go 1.18.

Freeze Go version at 1.18.

---

.ci/.bump-go-release-version.yml

1.16 is not anymore supported and main points to 1.19 now
Closes #ISSUE

golang: enable 1.18 and 1.17

---

.ci/.bump-go-release-version.yml
.ci/.bump-stack-release-version.yml
.ci/.bump-stack-version.yml
.ci/updateStackReleaseVersion.groovy
.github/dependabot.yml

Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
Use `elastic/observablt-robots` group instead of `elastic/observablt-robots-on-call`.
There is no rotation anymore for on-call.

Move from observablt-robots-on-call to observablt-robots

---

test-infra/apm-ci/test_installed_tools.py

Skip test-infra for arm , using https://testinfra.readthedocs.io/en/latest/modules.html#testinfra.modules.systeminfo.SystemInfo.arch
Java Agent doesn't use ARM anymore

test-infra: java for arm is not required

---

src/test/groovy/ApmBasePipelineTest.groovy
vars/sendBenchmarks.groovy

Update vault secret so it can be used by some other teams within the observability org
Unblocks https://github.com/elastic/go-libaudit/pull/123

Update default vault secrets for sendBenchmarks

---

pom.xml

Reverts elastic/apm-pipeline-library#1818
https://github-redirect.dependabot.com/jenkinsci/workflow-job-plugin/issues/279 is the one causing issues in our CI when running the release
```
[2022-08-30T12:15:33.563Z] [INFO] [INFO] BUILD FAILURE
[2022-08-30T12:15:33.563Z] [INFO] [INFO] ------------------------------------------------------------------------
[2022-08-30T12:15:33.563Z] [INFO] [INFO] Total time:  13.996 s
[2022-08-30T12:15:33.563Z] [INFO] [INFO] Finished at: 2022-08-30T12:15:33Z
[2022-08-30T12:15:33.563Z] [INFO] [INFO] ------------------------------------------------------------------------
[2022-08-30T12:15:33.563Z] [INFO] [ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.13.1:compileTests (default) on project jenkins-library: Error occurred while …
```

Revert "chore(deps-dev): bump workflow-job from 1203.v7b_7023424efe to 1232.v5a_4c994312f1"

---

src/test/groovy/SendBenchmarksStepTests.groovy
vars/sendBenchmarks.groovy
vars/sendBenchmarks.txt

Add `useGoBench` parameter so it can use the `gobench` library
There is no need to approve the indices but use the flag instead

Support for gobench transformation

---

.github/dependabot.yml

Run less often the dependabot bumps
There is no need to be up-to-date immediately, so we can reduce the code review overhead/notifications a bit

dependabot: less often

---

.ci/validateWorkersBeatsCi.groovy

Update the list of workers where the test-infra runs against to.

test-infra: update ephemeral workers and osx static workers

---

resources/scripts/pytest_otel/README.md
resources/scripts/pytest_otel/pyproject.toml
resources/scripts/pytest_otel/setup.cfg

Add hard-requirements as [explained here](https://realpython.com/pypi-publish-python-package/#specify-your-package-dependencies)
Those dependencies are defined in https://github.com/elastic/apm-pipeline-library/blob/dcbf2c4c6026925b905ec1bdfe4ba2ba7a9469e1/resources/scripts/pytest_otel/requirements.txt#L6
Help consumers so they can use the library with the needed dependencies.
Closes https://github.com/elastic/apm-pipeline-library/issues/1839

pytest_otel: add hard dependencies

---

src/test/groovy/IsBranchUnifiedReleaseAvailableStepTests.groovy
vars/isBranchUnifiedReleaseAvailable.groovy

Add support for reading different files in case there is no match with the first search
DRA validation failed after some re-org in the internal repository. This will ensure there are a couple of alternatives to search for those branches that are Unified Release based.
https://github.com/elastic/apm-pipeline-library/pull/1824 solved the original bug

Fallback for isBranchUnifiedReleaseAvailable

---

.github/workflows/build-test.yml

See https://github.com/actions/setup-java\#caching-packages-dependencies
Cache maven build dependencies
Faster builds

actions: cache maven dependencies

---

.ci/.bump-go-release-version.yml

Enable golang auto-bump for https://github.com/elastic/cloudbeat
Use same automation as done for other projects, hence https://github.com/elastic/cloudbeat/pull/304 won't be manually created anymore
Requires https://github.com/elastic/cloudbeat/pull/368

go-bump-automation: enable for cloudbeat

---

resources/commands-github-comment-markdown.template

Collapse the GitHub comments sections by default
Less verbose details for the shake of usability

cosmetic: github comment section to be collapsed

---

.ci/.bump-go-release-version.yml
vars/goDefaultVersion.groovy

Go Version is normally being driven by Beats and similar projects. So let's use the same versioning
Avoid weird surprises regarding the version used in the pipeline:
- https://github.com/elastic/elastic-agent/pull/1204

go 1.18 for apm pipeline

---

.ci/.bump-go-release-version.yml

Enrol the `elastic/stream.git` project for the golang autobump.
Team won't need to monitor if a new version is out but use our existing automation
Requires https://github.com/elastic/stream/pull/42

golang: automate bump for elastic/stream.git

---

resources/scripts/pytest_otel/CHANGELOG.md
resources/scripts/pytest_otel/Makefile

We have to add the installation of wheel before to make the package if not the following error happens
```bash
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: setup.py cmd --help
error: invalid command 'bdist_wheel'
```

fix: install weel before to make a package

---

src/test/groovy/OpbeansPipelineStepTests.groovy
vars/opbeansPipeline.groovy

opbeans-$lang Jenkins builds are currently failing on the "Integration Tests"
step with:
Failed to trigger build of apm-integration-tests-selector-mbp/main
They all run the `opbeansPipeline()` that is defined here.
https://github.com/elastic/apm-integration-testing/pull/1524 removed
the integration tests from apm-integration-testing.git and its Jenkinsfile.
* * *
- node.js: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-nodejs%2Fopbeans-node-mbp/detail/main/124/pipeline
- python: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fopbeans-python-mbp/detail/main/150/pipeline
- go: https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-go%2Fopbeans-go-mbp/detail/main/98/pipeline
I'm pretty sure this is the correct "fix", but to be honest I'm a …

fix: Remove "Integration Tests" stage from opbeansPipeline

---

.ci/.bump-stack-version.yml

Change the owner for those auto-bumps
For instance https://github.com/elastic/e2e-testing/pull/3069 only notifies the `ci` team

update owner for the auto-bump in the e2e-testing

---

src/test/groovy/MetricbeatStepTests.groovy
src/test/resources/metricbeatTest_2/metricbeat_container_worker-0676d01d9601f8191.json
vars/metricbeat.groovy
vars/metricbeat.txt

Support `archiveOnlyOnFail` in the `metricbeat` step
`archiveOnlyOnFail` was added to the consumer `dockerContext` but it was not implemented in `metricbeat`.

Honour archiveOnlyOnFail in metricbeat

---

.ci/jobs/apm-pipeline-library-mbp.yml

* filter all branches except main and PRs in the main Jenkins pipeline
There is about 30 branches that should not have job for this pipeline.

fix: remove branches jobs creation

---

src/test/groovy/StackVersionsStepTests.groovy
vars/stackVersions.groovy
vars/stackVersions.txt

Move `release` to the 8 series while `release7` is added for the 7 series.
Reflect what's the latest major release

Support release7 alias

---

vars/preCommit.groovy

install pre-commit regardless of the exiting installation in the CI workers
Cannot trust the CI workers since the pre-commit can be corrupted

pre-commit install always

---

.ci/.bump-go-release-version.yml

Force `Fleet Server` to use 1.18 instead 1.19
Fleet Server uses `1.18` at the moment

golang: autobump for fleet-server against 1.18

---

.github/actions/version-framework/action.yml

Generate the `include` list to be consumed by the GitHub matrix workflows
Reuse the component so the APM Agents could potentially use this action
Requires by https://github.com/elastic/apm-agent-ruby/pull/1320

action: generate matrix output for the given list of versions, frameworks and exclusions

---

vars/goDefaultVersion.groovy

Remove a spurious quote that is producing an unexpected string.
This prevents `goDefaultVersion` to find the Go version in  `env.BASE_DIR`, as it tries to find `.go-version'`.
Found in https://github.com/elastic/integrations/pull/4717, where the default version of Go is being unexpectedly installed.

Remove spurious quote when looking for .go-version

---

.github/actions/docker-layer-caching/action.yml

On a different workflow the action can fail because of too many requests to the caching API (especially on matrix jobs). Which is why `continue-on-error` is recommended to be `true` always.
There is some complication for inputs that are not strings.
Instead of trying to fix the input, I'm removing the input and set `continue-on-error` to `true` always.
```
Error: Unexpected error: Error: Cache service responded with 429 during commit cache.
...
Error: The step failed and an error occurred when attempting to determine whether to continue on error.
Error: The template is not valid. elastic/apm-pipeline-library/current/.github/actions/docker-layer-caching/action.yml (Line: 35, Col: 26): Unexpected value 'true'
````
> Source: https://github.com/elastic/ecs-logging-ruby/actions/runs/3766344912/ …

Fix docker-layer-caching action

---

.github/actions/setup-git/action.yml
.github/workflows/actions-test.yml

Add `GIT_USER` and `GIT_EMAIL` to `GITHUB_ENV` when using the `setup-git` action so it is available in subsequent steps
Closes #ISSUE

Add GIT_USER and GIT_EMAIL to GITHUB_ENV

---

.github/workflows/publish-docker-images.yml

After merging https://github.com/elastic/apm-pipeline-library/pull/1986, I tried to verify the final behaviour of `publish-docker-images` with `workflow_dispatch`. Unfortunately, the push condition is wrong, which I consciously commented out during development.
The `push` property is defined as `default: true` in the schema and therefore left out.
This change should make the expression true if the `push` property is empty or `true`.
The workflow is already merged and running on a schedule, but nothing is pushed because the condition is wrong.
- https://github.com/elastic/apm-pipeline-library/pull/1986

Fix push condition in publish-docker-images wokrflow

---

.github/workflows/publish-docker-images.yml

The fix in https://github.com/elastic/apm-pipeline-library/pull/1995 did not work as expected.
The culprit is that in GH Actions Expressions, they do loose comparisons, which causes unexpected behaviour:
```javascript
${{ '' != false }} // false
${{ '' == false }} // true
${{ null != false }} // false
${{ null == false }} // true
// when used to evaluate matrix.push, which can be true, false or undefined
// ${{ matrix.push != false }}
```
By putting the `matrix.push` into a environment variable, the expression will be evaluated using string comparison and therefore gives the expected result.
The publish-docker-images workflow is already merged and the old build-docker-images Jenkinsfile is already removed. Hence, it's not working ATM.
- …

Fix publish-docker-images workflow v2

---

.github/workflows/publish-docker-images.yml

Sets the working directory for each step in publish-docker-images workflow using the `defaults` attribute.
I forgot to add the working directory for the push step and the workflow is failing for images with a custom `push_script`.

Fix working directory in publish-docker-images workflow

---

.github/workflows/publish-docker-images.yml

The `push_script` was failing because I forgot to set the working directory for it in case it's undefined.
This change sets the default working directory for the whole job.
I was able to verify it with a manually dispatched workflow here: https://github.com/elastic/apm-pipeline-library/actions/runs/3849476101
The publish-docker-images workflow is failing.

Set default working directory for publish-docker-images workflow

---

.ci/Jenkinsfile
.ci/schedule-daily.groovy
.ci/schedule-weekly.groovy
resources/scripts/pytest_otel/Makefile
resources/scripts/pytest_otel/tests/it/test_basic_plugin.py
resources/scripts/pytest_otel/tests/it/test_failure_code_plugin.py
resources/scripts/pytest_otel/tests/it/test_failure_plugin.py
resources/scripts/pytest_otel/tests/it/test_skip_plugin.py
resources/scripts/pytest_otel/tests/it/test_success_plugin.py
resources/scripts/pytest_otel/tests/it/test_xfail_no_run_plugin.py
resources/scripts/pytest_otel/tests/it/test_xfail_plugin.py
resources/scripts/pytest_otel/tests/it/utils/__init__.py
src/test/groovy/GetVaultSecretStepTests.groovy
src/test/resources/jobs/dockerLogin.dsl
vars/README.md
vars/codecov.groovy
vars/codecov.txt
vars/opbeansPipeline.groovy
vars/preCommit.groovy
vars/preCommit.txt
vars/writeVaultSecret.groovy
vars/writeVaultSecret.txt

It changes to use the `observability` namespace instead the `apm` namespace for grabbing vault secrets.
We have to update only the `observability` secrets. The use of the `apm` should be deprecated.

fix: use observability Vault namespace

---

.github/workflows/opentelemetry.yml

use the original action rather than the forked one and enable to all the workflows

action: export traces with the OTEL GH action

---

.github/workflows/actions-test.yml
.github/workflows/build-test.yml
.github/workflows/opentelemetry.yml
.github/workflows/pytest_otel.yml
.github/workflows/test-reporter.yml

* rename workflows with some IDs rather than meaningful names
* user explicit workflow names otherwise the workflow won't run as it's required

action: use explicit workflow names

---

.github/actions/opentelemetry/README.md
.github/actions/opentelemetry/action.yml

Create a reusable action and hide all the credentials by using Vault
Consumers don't need to worry about the internals and it uses Vault so much protected approach
@kuisathaverat made a good point regarding abstracting the secrets by using Vault, see https://github.com/elastic/apm-pipeline-library/pull/2007#issuecomment-1384004736

action: reusable action for the OTEL export

---

.github/workflows/opentelemetry.yml

Use the current composite action with the default arguments
Reuse the component
Bear in mind, I updated the `current` tag manually

action: use .github/actions/opentelemetry@current

---

.github/actions/opentelemetry/README.md
.github/actions/opentelemetry/action.yml

Restore the secrets since:
> The secrets context contains the names and values of secrets that are available to a workflow run. The secrets context is not available for composite actions due to security reasons.
See https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context

action: composite cannot access to secrets

---

.ci/.docker-images.schema.json
.ci/.docker-images.yml
.github/workflows/publish-docker-images.yml

- Fixes the `azure-vm-tools` image build
- Adds ability to specify a branch for debugging.
Verified to be working here: https://github.com/elastic/apm-pipeline-library/actions/runs/3932458276/jobs/6725049141
During the migration there were images that failed already on Jenkins. This is a follow-up PR.
- https://github.com/elastic/apm-pipeline-library/issues/1992

Fix azure-vm-tool docker image

---

.ci/.docker-images.yml

- Re-enables the `test-plans` image build
Verified to be working here: https://github.com/elastic/apm-pipeline-library/actions/runs/3938527741/jobs/6737329340
During the migration there were images that failed already on Jenkins. This is a follow-up PR.
- https://github.com/elastic/apm-pipeline-library/issues/1992

Re-enable test-plans docker image

---

resources/scripts/pytest_otel/CHANGELOG.md
resources/scripts/pytest_otel/README.md
resources/scripts/pytest_otel/docs/demos/elastic/elastic-stack.yml
resources/scripts/pytest_otel/mypy.ini
resources/scripts/pytest_otel/pyproject.toml
resources/scripts/pytest_otel/requirements.txt
resources/scripts/pytest_otel/setup.cfg
resources/scripts/pytest_otel/tox.ini

* Remove support for Python 3.6 and 3.7
* add support for Python 3.11
* Bump OpenTelemetry SDK to 1.15.0
* Update Elastic demo to 8.6.0

feat: bump Python OpenTelemetry SDK to 1.15

---

.ci/.bump-stack-version.yml

Enable the automation for bumping snapshots
No more downgrades such as https://github.com/elastic/apm-integration-testing/pull/1549
Although it will create two different PRs, the one that we are familiar with and the one related to the snapshot `major.minor.0` version, that happens not often though (every 2/3 months or so)
Uses https://github.com/elastic/apm-integration-testing/pull/1550

automation: bump version for the apm-integration-testing@main

---

.github/workflows/release.yml

Fix a missing key in the GitHub action definition
Otherwise, it won't work

action: fix missing run

---

.github/workflows/release.yml

Use PAT
as long as github actions cannot bypass the branch protection
Otherwise:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:50 min
[INFO] Finished at: 2023-01-24T15:15:18Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project jenkins-library: Unable to commit files
Error:  Provider message:
Error:  The git-push command failed.
Error:  Command output:
Error: [ERROR] remote: error: GH006: Protected branch update failed for refs/heads/main.        
Error: [ERROR] remote: error: You're not …
```

action: use PAT

---

.github/workflows/release.yml

Enable `setup-git`
Otherwise:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project jenkins-library: Unable to commit files
Error:  Provider message:
Error:  The git-commit command failed.
Error:  Command output:
Error:  Author identity unknown
Error:  
Error:  *** Please tell me who you are.
Error:  
Error:  Run
Error:  
Error:    git config --global user.email "you@example.com"
Error:    git config --global user.name "Your Name"
Error:  
Error:  to set your account's default identity.
Error:  Omit --global to set the identity only in this repository.
```

action: setup-git required for the releases

---

.github/workflows/release.yml

Set write permissions
Otherwise:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare (default-cli) on project jenkins-library: Unable to commit files
Error:  Provider message:
Error:  The git-push command failed.
Error:  Command output:
Error:  remote: Permission to elastic/apm-pipeline-library.git denied to github-actions[bot].
Error:  fatal: unable to access 'https://github.com/elastic/apm-pipeline-library.git/': The requested URL returned error: 403
Error:  -> [Help 1]
```

action: fix permissions in the release

---

.github/workflows/release.yml

Set a new env variable to be populated for the releases.
Somehow it is not working with the PAT

actions: use hashicorp/vault-action to prepare the github release

---

.github/workflows/release.yml
pom.xml

Use default behaviour
> The auth token is persisted in the local git config. This enables your scripts to run authenticated git commands. The token is removed during post-job cleanup. Set persist-credentials: false to opt-out.
That's the way to force the push coming from the PAT rather than `github-actions[bot]`

actions: enable releases with the default behaviour

---

.ci/.bump-go-release-version.yml

Avoid bumping versions for the oblt-robots in terms of new golang versions
Jenkins is not the CI for the future, so automation is not needed for that project for this particular regard

automation: remove golang bump for obl-robots

---

.ci/.bump-go-release-version.yml

Support minor-1 releases, aka 1.19
https://github.com/elastic/golang-crossbuild/pull/260 has been merged hence `main` does not use `1.19` anymore, so the automation requires to listen for `1.19` versions in the `1.19` branch

golang: 1.20

---

.ci/.bump-go-release-version.yml

Allow creating automated PRs for Beats and Agent repositories.
I know we are working to replace this workflow, but I am hoping to get one final pass in of updating the version of every project at once.

Bump overrideGoVersion to 1.19 for Beats,Agent

---

.github/dependabot.yml

Remove maven dependabot since it's not production ready this code, as we don't use those dependencies at runtime but consume them from the CI controllers.
Jenkins ecosystem at Elastic is deprecated, hence the Jenkins shared library won't need any updates on that regard eventually.
Reduce the PR review overhead that won't be needed in the near future
Closes #ISSUE

dependabot: remove maven

---

.ci/.docker-images.yml

After fixing the upstream issues in https://github.com/elastic/apm-integration-testing/pull/1554
Enable building the docker images for the apm-integration-testing-all
```
➜  apm-integration-testing git:(fix/apm-server-docker-image) make -C docker all-tests
HEAD is now at c706d14 Bats 1.1.0
12-alpine: Pulling from library/node
Digest: sha256:d4b15b3d48f42059a15bd659be60afe21762aae9d6cbea6f124440895c27db68
Status: Image is up to date for node:12-alpine
docker.io/library/node:12-alpine
Synchronizing submodule url for 'tests/test_helper/bats-assert'
Synchronizing submodule url for 'tests/test_helper/bats-support'
1..5
ok 1 apm-server - build image
ok 2 apm-server - clean test containers
ok 3 apm-server - create test container
ok 4 apm-server - test container with 0 as exitcode
ok 5 apm-server …
```

docker: enable apm-integration-testing-all

---

.ci/docker/shellcheck/Dockerfile

Use the official docker pinned version with the latest `0.9.0` version
Fix the issue while compiling the project from the source code. I tried by bumping the OS version and went through the build system but somehow I could not make it work.
Since we don't use this often, I'd say to use this approach in favour of having something working. Otherwise we could remove it from the project since I don't see much benefit for buidlilng over and over from scratch for the same pinned version

shellcheck: use official pinned version 

---

.github/actions/elastic-stack-snapshot-branches/README.md
.github/actions/elastic-stack-snapshot-branches/action.yml

GitHub composite action to fetch the current list of active branches with snapshots in the Unified Release.
so consumers don't need to reimplement anything but use this.
Requires https://github.com/elastic/apm-pipeline-library/pull/2069
Notifies https://github.com/elastic/apm-server/pull/10222

action: list active branches with snapshots in the Unified Release

---

.github/workflows/generate-elastic-stack-snapshots.yml

Upload the elastic stack manifests to a google bucket
Automate the bump with `updatecli` so there is no need to parse or run specific shell scripts but pretty much query the google bucket for the given branch

populate: elastic stack manifests

---

.pre-commit-config.yaml

Remove linters for unexisting type of files (jjbb and pipelines)
Remove legacy code since this project doesn't run in Jenkins anymore

pre-commit: remove jjbb and jenkinsfile linters

---

.ci/bump-aliases.yml
.github/actions/docker-login/action.yml
.github/actions/updatecli/action.yml

`bump-aliases` uses the environmental context that has already access to the prviate docker registry
Use docker-login and env variables are reseted after the login has happened, hence it's not accessible by env variables
I used the `.ci/bump-aliases.yml` locally with the username/password as I was already logged in and it worked.

action: bump-aliases use docker login

---

.github/actions/is-member-elastic-org/README.md
.github/actions/is-member-elastic-org/action.yml
.github/workflows/opentelemetry.yml
.github/workflows/test-is-member-elastic-org.yml

Support action to verify if the given GitHub user is member of the `elastic` org using 
https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#check-organization-membership-for-a-user 
This will help us to move forward with the GitHub command ops to run specific actions based on specific GitHub commands
see [this workflow](https://github.com/elastic/apm-pipeline-library/actions/runs/4218017592/jobs/7322214514) that tested these changes
Supersedes https://github.com/elastic/apm-pipeline-library/pull/2087

action: is-member-elastic-org composite action

---

.github/actions/workflow-run/README.md
.github/actions/workflow-run/action.yml
.github/workflows/test-workflow-run.yml

GitHub composite action to trigger workflows between GitHub repositories using the [repository_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch)
This will help us to interconnect different workflows with different even types, such as, a GitHub command will trigger a workflow in a different repository (even private repositories)
This [build](https://github.com/elastic/apm-pipeline-library/actions/runs/4224575367/jobs/7335706206), caused by  https://github.com/elastic/apm-pipeline-library/pull/2094/commits/0c4069e90f643ffaf45a397894024f0ddb19267a, triggered the build in one of our internal playground GitHub repositories:

action: workflow event composite action

---

.github/actions/notify-build-status/README.md
.github/actions/notify-build-status/action.yml

Add ability to add custom message to notify-build-status action
```
with:
message: Hello, World!
```
In some cases you wan't to add additional message to the notification.
Closes #ISSUE

Add ability to add custom message to notify-build-status action

---

.github/actions/oblt-cli/README.md
.github/actions/oblt-cli/action.yml
.github/workflows/test-oblt-cli.yml

Composite action to interact with the oblt-cli tool
Simplify consumers so they can directly use the CLI but without the need to download the binary
See this [build](https://github.com/elastic/apm-pipeline-library/actions/runs/4232636127/jobs/7352610773) that triggered the `oblt-cli`

action: oblt-cli action

---

.ci/bump-aliases.yml
.ci/bump-elastic-stack.yml

When a new minor will happen then the patch for the 8 line will not point to an existing version.
Current releases are already supported with the GitHub releases
Those conditions are not required

bump: tweak conditions for current releases and upcoming patches

---

.github/actions/opentelemetry/README.md
.github/actions/opentelemetry/action.yml

Use the new secret
Elastic cloud deployment will be renamed so this will help us with the renaming
Additionally, I created the vault folder `secret/observability-team/ci/observability-ci/` so the `apm-credentials` will only contain the relevant data

action: migrate to observability-ci

---

.ci/bump-aliases.yml
.ci/bump-elastic-stack.yml
.ci/bump-golang.yml

updatecli: use GITHUB_RUN_ID for the branch name
Avoid reusing the same branch so PRs get created for each workflow execution, then no unrequired PRs are created.

updatecli: use GITHUB_RUN_ID for the branch name

---

.github/actions/is-pr-author-member-elastic-org/README.md
.github/actions/is-pr-author-member-elastic-org/action.yml
.github/workflows/opentelemetry.yml
.github/workflows/test-is-pr-author-member-elastic-org.yml

Given a PR id, and its repository then evaluate whether its author is an Elastic member.
An action helper functional for some other consumers
See https://github.com/elastic/apm-pipeline-library/actions/runs/4286615925/jobs/7466417811

action: is-pr-author-member-elastic-org

---

.mergify.yml

Update mergify to reflect the current state of the art:
remove unused rules, change merge conditions, delete updatecli branches
Otherwise `updatecli` reuses the same branch and causes misleading PRs.

mergify: remove unused rules, change merge conditions, delete updatecli branches

---

.github/actions/snapshoty-simple/action.yml

* Use bucket name var present in Vault secret
* It allows redirecting artifacts to another bucket.
* It allows credentials rotation.

[snapshoty] use bucket name from secret

---

.github/actions/updatecli/README.md
.github/actions/updatecli/action.yml
.github/workflows/test-updatecli.yml

Notify if the `updatecli` failed with some customisation 
Proactive failure notification

action: notify when updatecli failed

---

.ci/.docker-images.yml
.github/workflows/publish-docker-images.yml

- Adds the ability to push to dockerhub
- Pushes jruby images to dockerhub instead
This is needed to be able to run PR tests in https://github.com/elastic/apm-agent-ruby/pull/1366 without the necessity of GH secrets.
- Depends on https://github.com/elastic/apm-agent-ruby/pull/1367
- Needed in https://github.com/elastic/apm-agent-ruby/pull/1366

Publish jruby images in dockerhub

---

.github/actions/check-dependent-jobs/README.md
.github/actions/check-dependent-jobs/action.yml
.github/actions/notify-build-status/README.md
.github/actions/notify-build-status/action.yml

Add ability to set notification status explicitly for the `notify-status-build` action.
this way it can be use in conjuction with `check-dependent-job-status`
Usage:
```yaml
steps:
- id: check
uses: elastic/apm-pipeline-library/.github/actions/check-dependent-jobs@current
with: ${{ toJSON(needs) }}
- uses: elastic/apm-pipeline-library/.github/actions/notify-build-status@current
with:
status: ${{ steps.check.outputs.status }}
vaultUrl: ${{ secrets.VAULT_ADDR }}
vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
slackChannel: "#some-channel"
```
- Send a notifcation regardless of the `job.status`

Add ability to set notification status explicitly

---

.ci/bump-golang.yml

1.18 is dead, and we can use 1.20, consumers are teh ones defining what version to be used, so we can enforce to use the latest one by default

update golang bump to listen for new releases

---

.github/actions/deploy-my-kibana/README.md
.github/actions/deploy-my-kibana/action.yml

Support the deploy-my-kibana composite action that can request a new deployment using the GitHub issues automation
Entrypoint for the consumers that use GitHub commands to deploy a particular Kibana instance using the Oblt Test environments

action: deploy-my-kibana

---

.github/dependabot.yml

As explained in https://github.com/dependabot/dependabot-core/issues/4178
Enable dependabot for the composite actions
Get the benefits of dependabot so we can track updates easily or no...
If https://github.com/dependabot/dependabot-core/issues/5137 then we can simplify our dependabot configuration...

dependabot enabled for the github actions composite

---

.github/actions/buildkite/action.yml
.github/actions/docker-login/action.yml
.github/actions/github-token/action.yml
.github/actions/opentelemetry/action.yml
.github/actions/publish-report/action.yml
.github/actions/setup-vault-cli/action.yml
.github/actions/slack-message/action.yml

* Update github action vault version to 2.5.0
* Version prior 2.4.3 use deprecated [set-output](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) command.

chore: upgrade github action vault

---

.github/actions/snapshoty/package.json

* Change snapshoty license to Apache-2.0
* The project is under Apache-2.0.
* Avoid mixed licenses.
Closes #2038

snapshoty: change license to apache-2.0

---

.ci/.docker-images.yml

Publishes apm-agent-python docker images for testing in dockerhub so it can be accessed publicly in GH Actions workflows.
Optimizes the test time
- depends on https://github.com/elastic/apm-agent-python/pull/1794

Publish apm-agent-python docker images in dockerhub

---

.github/actions/oblt-cli/action.yml

It adds the environment variable `ELASTIC_APM_ENVIRONMENT=CI` to the `oblt-cli` action to distinct CI operation from user operations.
We make a lot of calls to oblt-cli from CI we have to distinguish them from the user iterations, we are interested on the way users use `oblt-cli`, we know how the CI does it.

chore: set APM environment to CI

---

.github/actions/elastic-stack-snapshot-branches/action.yml
.github/actions/elastic-stack-snapshot-branches/script.py
.github/workflows/test-elastic-stack-snapshot-branches.yml

* Add exclude branches input on elastic stack snapshot branches action.
* Refactor the script in a separate file.
* Some use cases require excluding branches from the list of active branches.

ci: add exclude branches on elastic stack snapshot branches 

---

.github/actions/setup-npmrc/README.md
.github/actions/setup-npmrc/action.yml

- Creates a GH Action named `setup-npmrc`, similarly to `withNpmrc` Jenkins Global Variable.
- Can be used in GH Actions workflows with npm registry operations like publishing, etc.
Closes #ISSUE

Add setup-npmrc action

---

.mergify.yml
updatecli/updatecli.d/bump-aliases.yml
updatecli/updatecli.d/bump-elastic-stack.yml
updatecli/updatecli.d/bump-golang.yml

Add labels so mergify can delete the branches when PRs are merged/closed
Reuse PRs when needed - golang and aliases don't need unique PRs since it's the same content, otherwise it will create duplicated PRs.
Automate some leftovers

updatecli and mergify:  automate delete branches and when to reuse PRs

---

.github/actions/publish-report/action.yml

* Upgrade github-script dependency to 6.4.1.
* Use the latest bug fixes.
* Unblock [dependabot](https://github.com/elastic/apm-pipeline-library/pull/2183) PRs.
Closes #2183

build(github-actions): upgrade to github-script 6.4.x

---

.ci/generate-snapshots.sh

Create a `<branch>.json` when the `<branch>` is created from the `main` branch but the Unified Release has not been executed yet. 
Fixes
```
d13bda82c47f75988b87ca1422ebcddad994f6f5	refs/heads/7.17
7.17
8b8607111451b5b32c0f264f69142b26a696574d	refs/heads/8.6
8.6
d917f5648890b6dcbd23e623f1f1bf8f82ce5523	refs/heads/8.7
8.7
c90baf5e77ea3a932e06de126e30c95377b331e8	refs/heads/8.8
8.8
4e69fa102ffe583a224b11c36[49](https://github.com/elastic/apm-pipeline-library/actions/runs/4814611121/jobs/8587535969#step:3:50)c82784dd91a3e	refs/heads/main
main
jq: error: Could not open file 8.8.json: No such file or directory
Error: Process completed with exit code 2.
```
And
```
latestVersion
-------------
ERROR: ✗ file "https://storage.googleapis.com/artifacts-api/snapshots/8.8.json" does not exist
Pipeline …
```

snapshots: when release branch is not yet available in the Unified Release

---

.github/actions/deploy-my-kibana/README.md
.github/actions/deploy-my-kibana/action.yml

Deploy to a serverless cluster
Notifies https://github.com/elastic/kibana/pull/158237
If no `main` branch -> https://github.com/elastic/apm-pipeline-library/actions/runs/5055753199/jobs/9072363464
If `main` branch -> https://github.com/elastic/apm-pipeline-library/actions/runs/5055688365

oblt: support github command for serverless

---

.github/actions/buildkite/README.md
.github/actions/buildkite/action.yml
.github/actions/buildkite/download_artifacts.py
.github/actions/buildkite/run.sh

Adds the ability to download artifacts from the targeted buildkite pipeline and upload it in GH actions artifacts.
Successful test run: https://github.com/elastic/apm-agent-java/actions/runs/5176206539/jobs/9324729641?pr=3158
Needed in apm-agent-java migration to transfer artifacts built and uploaded in buildkite to the GH Actions workflow.

Add ability to transfer artifacts from Buildkite to GH in the buildkite action

---

.github/workflows/test-is-pr-approved.yml

* Validate dist package with pull_request and push event.
* The validation fails on the main branch due to the push event.

ci: better dist validation for is-pr-approved

---

.github/actions/oblt-cli/action.yml

The banner add some time and contains info not interested for the CI users
chore: disable banner when oblt-cli run on CI

chore: disable banner when oblt-cli run on CI

---

.github/actions/buildkite/action.yml

This will allow the buildkite action to download artifacts even if the buildkite job failed.
Closes #ISSUE

Allow buildkite action to download artifacts also when the build failed

---

.github/workflows/publish-docker-images.yml

Adds slack notificaiton to the publish-docker-images workflow
Closes #ISSUE

Add slack notification to publish-docker-images workflow

---

.github/actions/oblt-cli/action.yml
.github/actions/setup-oblt-cli/README.md
.github/actions/setup-oblt-cli/action.yml
.github/actions/setup-oblt-cli/download.sh

Add an action that sets up `oblt-cli`
In a new workflow that is currently in the works, I have a shell script that uses `oblt-cli`. 
I need this action to make oblt-cli available in the `PATH`.
Closes #ISSUE

Add setup-oblt-cli action

---

.github/actions/oblt-cli-create-custom/README.md
.github/actions/oblt-cli-create-custom/action.yml

Enable the flag for the random cluster name.
We can support reusing cluster deployments.
Caused by https://github.com/elastic/observability-test-environments/pull/9314

action: support flag to disable random cluster name

---

.github/workflows/release.yml

Support releases using the service account
Branch protection does not allow to use the maven release out of the box. This should help us to use it while we move away from Jenkins.
similar to https://github.com/elastic/apm-agent-java/pull/3178

action: release automation

---

.ci/.docker-images.yml

Those docker images are not consumed by the `apm-agent-ruby`.
The `apm-agent-ruby` build process already builds those docker images. Hence there is no need to build them again.
We could potentially change the `apm-agent-ruby` to consume them if they exist rather than building them again from scratch. But for the time being, I'd prefer we remove the logic in this repository

docker: remove some docker image generation for ruby

---

vars/nodeJSDefaultVersion.groovy

Upgrades the node version to the latest LTS version, this was breaking synthetics tests that depend on node 14 features.
I'm not sure if other Jenkins stuff would have an issue with this version.
Unblocks development of heartbeat
https://github.com/elastic/beats/pull/36147/

Update nodeJSDefaultVersion.groovy to 18.17.1

---

.github/workflows/test-notify-build-status.yml

PRs don't have access to secrets let's use feature branches.
Fixes https://github.com/elastic/apm-pipeline-library/pull/2354 that failed when accessing the secrets

action: PRs don't have access to GH secrets

---

.github/actions/deploy-my-kibana/action.yml

serverless-oblt was replaced by serverless-qa-oblt
fix: update the serverless cluster reference
The command /obl-deploy-serverless is failing. It requires a release of the library.

fix: update the serverless cluster reference

---

.github/actions/kibana-docker-image/README.md
.github/actions/kibana-docker-image/action.yml
.github/actions/kibana-docker-image/build-and-push.sh
.github/actions/kibana-docker-image/setup-vars.sh
.github/workflows/test-kibana-docker-image-action.yml

This PR creates an action to build and push kibana docker images.
Tested in 
- https://github.com/elastic/apm-pipeline-library/actions/workflows/test-kibana-docker-image-action.yml
- https://github.com/elastic/apm-pipeline-library/actions/workflows/test-build-and-publish-kibana-docker-image-action.yml

Build Kibana Docker Image Action

---

.github/actions/kibana-docker-image/action.yml
.github/actions/kibana-docker-image/setup-vars.sh
.github/workflows/test-kibana-docker-image-action.yml

Adds the output `git-commit-sha` and `stack-version` to the `kibana-docker-image` action.
This output can be used in further steps. 
E.g. 
- creating a commit status
- using the stack version for oblt-cli
Closes #ISSUE

Add outputs to `kibana-docker-image` action

---

.github/actions/updatecli/action.yml
.github/workflows/test-updatecli.yml

Add `messageIfFailure` in the updatecli
Other teams can customise who should be notified and what message to be sent if any failure
https://github.com/elastic/apm-pipeline-library/actions/runs/6189566360 produced two messages

action: support messageIfFailure in the updatecli

---

.github/actions/buildkite/action.yml
.github/actions/buildkite/cancel.sh

Add ability to cancel BK build when workflow is cancelled
When we have a long running BK build and `waitFor == true` and we want to cancel the workflow.
Closes #ISSUE

Add ability to cancel BK build when workflow is cancelled

---

.github/actions/buildkite/action.yml
.github/actions/buildkite/run.sh

- Add `pipelineCommit` and `pipelineBranch` inputs to buildkite action.
- deprecates `pipeline
This is in line with the [Buildkite Builds API](https://buildkite.com/docs/apis/rest-api/builds#create-a-build).
For testing purposes I was not able to trigger the pipeline from a specific branch, it would always checkout the main.
This gives us the ability to do so.
Closes #ISSUE

Add pipelineCommit and pipelineBranch inputs to buildkite action

---

.github/actions/kibana-docker-image/build-and-push.sh

create the arm64 Kibana Docker image for serverless
The current implementation only generates amd64 Docker images that are no longer valid for serverless projects in QA. We split the command to better maintainability due to Kibana build flags can impact each other. We need to review if it is possible to skip something else in the serverless build because it takes longer than before.

fix: create the arm64 Kibana Docker image for serverless

---

updatecli/updatecli.d/bump-aliases.yml

Use groups to get the first one
Otherwise it will return something else
```
✗ [docker_edge8] Is docker image elasticsearch:80852-SNAPSHOT available
```
See https://github.com/elastic/apm-pipeline-library/actions/runs/6509890106/job/17682399721

updatecli: use groups

---

updatecli/updatecli.d/bump-aliases.yml

`[0-9]` is not supported but `\d` instead.
Otherwise it won't work

updatecli: use digits

---

.ci/.docker-images.yml

Remove apm-integration-testing docker image generation
We don't use apm-integration-testing these days.

docker: remove apm-integration-testing docker image generation

---

.github/dependabot.yml

Update dependabot to run on [Sundays](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) and [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) by github action update.
Add some missing github actions
Unfortunately it's not possible to pass different directories yet, see https://github.com/dependabot/dependabot-core/issues/2178
Reduce the noise during the week and create one PR with all the changes for the same github-action/workflow.

dependabot: run weekly on sundays and group by

---

.github/actions/oblt-cli-create-ccs/action.yml

remove parameters when using `cluster create ccs`
since it's not supported

fix: parameters when using ccs

---

.ci/.docker-images.yml

Remove some container image generation for some deprecated services
They are now gone

chore: remove docker build for obsoleted elastic-apps

---

.github/workflows/bump-aliases.yml
updatecli/updatecli.d/bump-aliases.yml

Remove the workaround to support the auditing of what github workflow produced the PR with the updatecli changes
It's now supported in updatecli itself, see https://github.com/elastic/apm-server/pull/12044:
Closes #ISSUE

update-cli: workflow link is now supported natively

---

.github/actions/deploy-my-kibana/action.yml

Rename it
Otherwise it won't work
```
$ python3 .ci/scripts/find_cluster_config_by_name.py serverless-qa-oblt
```
while
```
$ python3 .ci/scripts/find_cluster_config_by_name.py keep_serverless-qa-oblt
.../environments/users/robots/keep_serverless-qa-oblt/config-cluster.yml
```

fix: name of the serverless qa environment

---

.ci/.docker-images.yml

Specialised docker images for the APM Agent Nodejs are not used anymore.
Playwright - node 14. https://github.com/elastic/apm-agent-rum-js/blob/7cd5f5ecbe02ee4ddc3e648927fa4ac0ce3dbb28/.ci/scripts/benchmarks.sh#L7
Build what's needed

docker-images: update to reflect what we use these days

---

.github/actions/deploy-my-kibana/action.yml

Remove branch validation for serverless
Serverless is supported from 8.10 branch hence there is no need to exclude the serverless deployments to main anymore

chore: support serverless regardless of the branch

---

.ci/get-next-minor-version.sh
resources/scripts/artifacts-api-latest-release-versions.sh

Sort by semver
Otherwise versions are not sorted correctly
Similarly done in https://github.com/elastic/apm-server/pull/12229

fix: sort by semver

---

.ci/generate-releases.sh
.github/workflows/generate-elastic-stack-releases.yml
.github/workflows/opentelemetry.yml
.gitignore

Store the release properties file in the Google Bucket called https://storage.googleapis.com/artifacts-api/releases/
Back in the day, we enabled [releases.properties](https://github.com/elastic/apm-pipeline-library/blob/main/resources/versions/releases.properties) to provide the current releases or upcoming ones given the major/minor/patch versions.
https://github.com/elastic/apm-pipeline-library/pull/1197 is the original request.
Further details can be found in:
- https://github.com/elastic/apm-pipeline-library/pull/1641, so only when the release is available.
- https://github.com/elastic/apm-pipeline-library/pull/1645, to distinguish BCs/releases from main.
It generates files that contain the version for the given aliases:
- next minor
- next patch
- current
- edge
The file's name will …

releases: provide api with the google bucket

---

.ci/generate-releases.sh
.github/workflows/generate-elastic-stack-releases.yml

Set GH_TOKEN
Add debug traces
Notify if any failures
Otherwise, it fails when running on the CI with the error below:
> To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable

release: set GH_TOKEN, add debug traces and notify if failures

---

.gcloudignore
.gitignore

Create file to avoid generated credentials to be published accidentally
Fixes 
> The "process_gcloudignore" option is true, but no .gcloudignore file was found. If you do not intend to process a gcloudignore file, set "process_gcloudignore" to false
See https://github.com/elastic/apm-pipeline-library/actions/runs/7335622889

ignore: generated credentials

---

.github/actions/buildkite/action.yml

Reverts elastic/apm-pipeline-library#2474
Otherwise, consumers need to use v4 and we have not done that yet

Revert "chore(deps): bump the github-actions group in /.github/actions/buildkite with 1 update"

---

.github/actions/buildkite/run.sh

Adds a notice annotation to the github workflow summary when using the buildkite action.
Example screenshot:
Easier to find the downstream buildkite build url
Closes #ISSUE

Add notice annotation to summary when using the buildkite action

---

catalog-info.yaml

Add a couple of github workflows (release and opentelemetry)
Add a few Github composite actions.
Create dependencies between them
Help to visualise those things in Backstage
Closes #ISSUE

backstage: add github action and composite actions

---

vars/githubTraditionalPrComment.groovy

I've just discovered that `https://api.github.com/repos/elastic/beats/issues/37853/comments/1925884269` is not working but `https://api.github.com/repos/elastic/beats/issues/comments/1925884269` then the GitHub comment with the build results are not reused but create a new one every time a build happens.
https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#list-issue-comments-for-a-repository is the command to list all the comments for any given issues/pull-request
https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#update-an-issue-comment is the one for changing existing GitHub comments.
I cannot understand the reason for the previous implementation and whether it never surfaced since there was a fallback for using the GitHub app.. maybe the scope of …

fix: github API comment is different when modigying an existing one

---

resources/github-comment-markdown.template
vars/notifyBuildResult.groovy

Following the migration from Jenkins to Buildkite, docs previews are now available at <repo>_bk_<PR>.
More context in https://github.com/elastic/docs/pull/2898
Closes #ISSUE

Update docs-preview link

---

.github/actions/await-maven-artifact/action.yml
.gitignore

Adds an action which allows to wait for a certain maven-central artifact to be available.
I've tested the action in a dummy-repo on my account.
When releasing artifacts to be maven central, the output of the release task is usually not useful: sometimes the output says failed, even though the artifact was published. Sometimes the release task is successfull, but the artifact wasn't published.
For this reason it is beneficial to just ignore the output of the release step and instead check the presence of the desired artifact on maven central, which is accomplished using this task.
In addition in the future we could enhance this task to provide the artifact as an output, so that we can for example publish it as artifact on the GH release.

Added action to wait for maven-central artifacts to be available

---

.github/actions/test-report/action.yml

Bump the version for `phoenix-actions/test-reporting@v12` that points to https://github.com/phoenix-actions/test-reporting/commit/41efe7ebebe7ef156ef46f6b0acf50ec0f10315b
The version contains already the fix
Closes #ISSUE

github-action: use phoenix-actions/test-reporting@v12

---

.github/actions/oblt-cli-cluster-credentials/action.yml
.github/actions/setup-oblt-cli/download.sh

PIn the version to `6.5.3`
Prepare for the secrets system migration so consumers don't get affected by the change.
Migrate to the new secret system store

oblt-cli: pin version 6.5.3

---

.github/workflows/codeql.yml

⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just contents read.
Please checkout this branch and add the necessary permissions to the workflows.
Merging this PR as is might cause workflows that need more permissions to fail.

security: add permissions block to workflows

---

.ci/.docker-images.yml

Remove unused docker image
Migrated to Buildktie https://github.com/elastic/azure-vm-extension/pull/93 or will be migrated shortly

docker: azure-vm-utils is not something belong to us

---

.ci/.docker-images.yml

Remove jenkins agent docker. generation
We don't need it anymore
Closes #ISSUE

docker: jenkins agent is not something we use nowadays

---

.ci/get-next-minor-version.sh

Filter a version from the list
It seems a bug has been introduced recently in the artifacts-api, so let's play safe and filter it

fix: avoid unexpected versions for the time being

---

.github/actions/setup-oblt-cli/README.md
.github/actions/setup-oblt-cli/action.yml
.github/actions/setup-oblt-cli/download.sh

- Add the ability to install a specific version of oblt-cli while defaulting to 6.5.3
- We need to be able to install the latest version of oblt-cli in gatekeeper.

feat: ability to install a specific version of oblt-cli

---

.github/actions/kibana-docker-image/build-and-push.sh

Disable the CDN thing for Kibana
Otherwise, serverless deployments use the CDN thing... 
Caused by https://github.com/elastic/kibana/pull/169707

github-action(kibana-docker-image): skip CDN

---

.github/actions/undeploy-my-kibana/README.md
.github/actions/undeploy-my-kibana/action.yml

GitHub composite action to centralise the logic for undeploying Kibana PRs
Keep it simple

github-action: undeploy my kibana

---

.github/actions/undeploy-my-kibana/action.yml

Fixes the name of the header
Otherwise the automation won't work
Closes #ISSUE

github-action: use the right contract for destroying PRs

---

.github/actions/oblt-cli-destroy-cluster/README.md
.github/actions/oblt-cli-destroy-cluster/action.yml

Configure username for destroy cluster
This will help consumers access their specific deployments
Closes #ISSUE

github-action: configure username for destroy cluster

---

.github/workflows/pytest_otel.yml
src/test/groovy/NotifyBuildResultStepTests.groovy
vars/notifyBuildResult.groovy
vars/notifyBuildResult.txt

Disable sending telemetry dta
Jenkins sunset, so we can decommission the infrastructure
Closes #ISSUE

jenkins: disable send telemetry data by default

---

.github/actions/buildkite/action.yml

Run cancel event before cleaning up the secrets
Otherwise, cancel won't work

fix(buildkite): run cancelled step before tearing down the secret

---

.github/workflows/build-test-docs.yml
.github/workflows/build-test-no-jenkins.yml
.github/workflows/build-test.yml

Run faster builds if no Jenkins
Run smarter what's needed

github-actions: run faster builds if no jenkins

---

.github/workflows/bump-aliases.yml
updatecli/updatecli.d/bump-aliases.yml

Use GitHub secrets for the updatecli integration with Slack notifications.
Use https://github.com/elastic/oblt-actions/tree/main/updatecli/run-and-notify
Secure

ci: use updatecli with github secrets

---

.github/actions/await-maven-artifact/action.yml

The publication on maven central may publish
This happened at least once during the following release execution: https://github.com/elastic/apm-agent-java/actions/runs/9266640000/attempts/1 where the AWS lambda layer could not be built as the artifact was missing.
However, in this case it seemed that the redirect may have worked as the `pom` was properly published (which I assume is used to properly redirect), but not the `.jar` file.
This PR does two things:
- use `-L` to follow the redirect link
- use `-I` to not download the artifact file but just print the HTTP response headers
This makes the release process more robust and actually checks that the artifact is accessible and can be downloaded, rather than assuming that it is when we get a non 404 response.

await-maven-artifact check redirect

---

.github/actions/check-dependent-jobs/action.yml

Support typescript
Fixes:
```
/home/runner/work/_temp/252df3fb-73a5-45df-9c44-acb862991f65.sh: command substitution: line 53: syntax error near unexpected token `('
```
That happens since the needs contains the outputs and bash is not clever enough to parse it correctly if containing `'` or similar special chars.
Closes #ISSUE

fix: use typescript to support other type of datastructures

---

.github/workflows/generate-elastic-stack-releases.yml
.github/workflows/generate-elastic-stack-snapshots.yml

The following workflows have been failing for a week, and we did not get notified.
- https://github.com/elastic/apm-pipeline-library/actions/workflows/generate-elastic-stack-releases.yml
- https://github.com/elastic/apm-pipeline-library/actions/workflows/generate-elastic-stack-snapshots.yml
Closes #ISSUE

Add slack notifications to generate-elastic-stack-* workflows

---

.github/workflows/bump-aliases.yml

⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
Use https://github.com/tibdex/github-app-token to generate ephemeral tokens with the required
permissions only
This is the alternative to moving away from finer-grained GitHub tokens and reducing the
cumbersome of rotating them as we do nowadays.
We have used the same GitHub action in other places.
If there are any questions, please reach out to the @elastic/observablt-ci

github-action: use ephemeral tokens with the required permissions
